;(function(){
  const D=window.T20_CLASS_FEATURE_DETAILS||(window.T20_CLASS_FEATURE_DETAILS={});
  const clean=text=>String(text||"").replace(/\s+/g," ").trim();
  const set=(key,desc,extra={})=>{
    D[key]={...(D[key]||{}),...extra,desc:clean(desc),full:true};
  };

  set("*|magias",`Você aprende e lança magias conforme a lista, atributo-chave e regras da sua classe. A tabela de progressão indica o maior círculo de magia que você pode lançar no nível atual. Sempre que a classe disser que você soma o atributo-chave aos PM, isso já deve ser considerado no total de PM da ficha.`);
  set("arcanista|magias",`Você pode lançar magias arcanas de 1º círculo. A cada quatro níveis, pode lançar magias de um círculo maior: 2º círculo no 5º nível, 3º círculo no 9º nível, 4º círculo no 13º nível e 5º círculo no 17º nível. Você começa com três magias de 1º círculo e, a cada nível, aprende uma magia de qualquer círculo que possa lançar. Seu atributo-chave é definido pelo Caminho do Arcanista e você soma esse atributo ao seu total de PM.`);
  set("bardo|magias",`Escolha três escolas de magia. Você pode lançar magias arcanas dessas escolas, começando com magias de 1º círculo. À medida que sobe de nível, libera círculos maiores: 2º círculo no 6º nível, 3º círculo no 10º nível e 4º círculo no 14º nível. Você começa com duas magias de 1º círculo e, a cada nível par, aprende uma magia de qualquer círculo e escola que possa lançar. Pode lançar essas magias vestindo armaduras leves sem testes de Misticismo. Seu atributo-chave é Carisma e você soma Carisma aos PM.`);
  set("clerigo|magias",`Você pode lançar magias divinas de 1º círculo. A cada quatro níveis, libera um círculo maior: 2º círculo no 5º nível, 3º círculo no 9º nível, 4º círculo no 13º nível e 5º círculo no 17º nível. Você começa com três magias de 1º círculo e, a cada nível, aprende uma magia de qualquer círculo que possa lançar. Seu atributo-chave é Sabedoria e você soma Sabedoria aos PM.`);
  set("druida|magias",`Escolha três escolas de magia. Você pode lançar magias divinas dessas escolas, começando com magias de 1º círculo. À medida que sobe de nível, libera círculos maiores: 2º círculo no 6º nível, 3º círculo no 10º nível e 4º círculo no 14º nível. Você começa com duas magias de 1º círculo e, a cada nível par, aprende uma magia de qualquer círculo e escola que possa lançar. Seu atributo-chave é Sabedoria e você soma Sabedoria aos PM.`);
  set("frade|magias",`Você pode lançar magias divinas de 1º círculo. A cada quatro níveis, libera um círculo maior: 2º círculo no 5º nível, 3º círculo no 9º nível, 4º círculo no 13º nível e 5º círculo no 17º nível. Você começa com três magias de 1º círculo e, a cada nível, aprende uma magia de qualquer círculo que possa lançar. Pode lançar essas magias usando armaduras leves; se estiver usando armadura pesada, precisa fazer teste de Misticismo como um conjurador arcano. Seu atributo-chave é Sabedoria e você soma Sabedoria aos PM.`);
  set("ermitao|magias",`Você lança magias como o druida básico: escolhe três escolas, lança magias divinas dessas escolas e usa Sabedoria como atributo-chave. A progressão do ermitão libera círculos maiores nos níveis indicados pela tabela.`);
  set("magimarcialista|magias",`Você lança magias como o bardo básico, escolhendo escolas e usando Carisma como atributo-chave. Suas magias interagem com Cadência Magimarcial: lançar magia de bardo gera carga arcana, usada por suas habilidades de combate mágico.`);
  set("necromante|magias",`Você lança magias como o arcanista básico, mas seu Caminho do Necromante altera sua lista: você pode aprender magias de necromancia divinas como se fossem arcanas, não pode aprender magias de encantamento e pelo menos metade das magias que aprender deve ser de necromancia.`);
  set("usurpador|magias",`Você pode lançar magias divinas de 1º círculo. A cada quatro níveis, libera um círculo maior: 2º círculo no 5º nível, 3º círculo no 9º nível, 4º círculo no 13º nível e 5º círculo no 17º nível. Você não começa com nenhuma magia e não aprende magias automaticamente como um clérigo; usa Usurpar para lançá-las. Seu atributo-chave é Carisma e você soma Carisma aos PM.`);

  set("*|devotofiel",`Você se torna devoto de um deus maior. Ao contrário de devotos normais, recebe dois poderes concedidos por se tornar devoto, em vez de apenas um, e deve seguir as Obrigações & Restrições da divindade. Como alternativa, algumas classes permitem cultuar o Panteão como um todo, com regras próprias de arma preferida, canalização e obrigações.`);
  set("*|abencoado",`Você soma seu Carisma ao seu total de PM no 1º nível. Além disso, torna-se devoto de uma divindade adequada à classe e recebe dois poderes concedidos por isso. Como alternativa, o paladino pode cultuar o bem como um todo, sem poderes concedidos e sem Obrigações & Restrições além do Código do Herói.`);
  set("santo|abencoado",`Como o paladino básico, você soma seu Carisma ao seu total de PM e se torna devoto de uma divindade adequada, recebendo dois poderes concedidos. Entretanto, o santo não pode escolher ser um santo do bem.`);
  set("*|codigodoheroi",`Você deve sempre manter sua palavra e nunca pode recusar um pedido de ajuda de alguém inocente. Além disso, nunca pode mentir, trapacear ou roubar. Se violar o código, perde todos os seus PM e só pode recuperá-los a partir do próximo dia.`);
  set("*|codigodehonra",`Você não pode atacar um oponente pelas costas; em termos de jogo, não pode se beneficiar do bônus de flanquear. Também não pode atacar um oponente caído, desprevenido ou incapaz de lutar. Se violar o código, perde todos os seus PM e só pode recuperá-los a partir do próximo dia.`);
  set("*|baluarte",`Quando sofre um ataque ou faz um teste de resistência, você pode gastar 1 PM para receber +2 na Defesa e nos testes de resistência até o início do seu próximo turno. A cada quatro níveis, pode gastar +1 PM para aumentar o bônus em +2. A partir do 7º nível, quando usa esta habilidade, pode gastar 2 PM adicionais para fornecer o mesmo bônus a todos os aliados adjacentes. A partir do 15º nível, pode gastar 5 PM adicionais para afetar aliados em alcance curto.`);
  set("*|duelo",`Você pode gastar 2 PM para escolher um oponente em alcance curto e receber +2 em testes de ataque e rolagens de dano contra ele até o fim da cena. Se atacar outro oponente, o bônus termina. A cada cinco níveis, pode gastar +1 PM para aumentar o bônus em +1.`);
  set("*|evasao",`Quando sofre um efeito que permite um teste de Reflexos para reduzir o dano à metade, você não sofre dano algum se passar. Se falhar, sofre o dano normal. Esta habilidade exige liberdade de movimentos; você não pode usá-la se estiver de armadura pesada ou na condição imóvel.`);
  set("*|evasaoaprimorada",`Quando sofre um efeito que permite um teste de Reflexos para reduzir o dano à metade, você não sofre dano algum se passar e sofre apenas metade do dano se falhar. Esta habilidade exige liberdade de movimentos; você não pode usá-la se estiver de armadura pesada ou na condição imóvel.`);
  set("*|esquivasobrenatural",`Seus instintos são tão apurados que você consegue reagir ao perigo antes que seus sentidos o percebam. Você nunca fica surpreendido.`);
  set("*|olhosnascostas",`Você consegue lutar contra diversos inimigos como se fossem apenas um. Você não pode ser flanqueado.`);
  set("*|empatiaselvagem",`Você pode se comunicar com animais por meio de linguagem corporal e vocalizações. Pode usar Adestramento com animais para mudar atitude e persuasão, como faria com Diplomacia.`);
  set("ermitao|empatiaselvagem",`Como o druida básico, mas você também pode se comunicar com criaturas vegetais não inteligentes (Int -4 ou -5) e espíritos.`);
  set("*|briga",`Seus ataques desarmados causam 1d6 pontos de dano e podem causar dano letal ou não letal, à sua escolha. A cada quatro níveis, esse dano aumenta, conforme indicado na tabela da classe. O dano indicado é para criaturas Médias; criaturas Pequenas diminuem esse dano em um passo e criaturas Grandes aumentam em um passo.`);
  set("*|cascagrossa",`Você soma sua Constituição na Defesa, limitado pelo seu nível e apenas se não estiver usando armadura pesada. Além disso, em níveis mais altos recebe bônus adicional na Defesa conforme indicado na progressão.`);
  set("*|engenhosidade",`Quando faz um teste de perícia, você pode gastar 2 PM para somar sua Inteligência no teste. Você não pode usar esta habilidade em testes de ataque.`);
  set("*|orgulho",`Quando faz um teste de perícia, você pode gastar uma quantidade de PM a sua escolha, limitada pelo seu Carisma. Para cada PM gasto, recebe +2 no teste.`);
  set("*|insolencia",`Você soma seu Carisma na Defesa, limitado pelo seu nível. Esta habilidade exige liberdade de movimentos; você não pode usá-la se estiver de armadura pesada ou na condição imóvel.`);
  set("*|esquivasagaz",`Você recebe bônus na Defesa e em Reflexos, conforme indicado pela tabela da classe. Esta habilidade exige liberdade de movimentos; você não pode usá-la se estiver de armadura pesada ou na condição imóvel.`);
  set("*|marcadapresa",`Você pode gastar uma ação de movimento e 1 PM para analisar uma criatura em alcance curto. Até o fim da cena, recebe +1d4 nas rolagens de dano contra essa criatura. A cada quatro níveis, pode gastar +1 PM para aumentar o bônus de dano conforme a tabela da classe.`);
  set("*|rastreador",`Você recebe +2 em Sobrevivência. Além disso, pode se mover com seu deslocamento normal enquanto rastreia sem sofrer penalidades no teste de Sobrevivência.`);
  set("*|explorador",`Escolha um tipo de terreno entre aquático, ártico, colina, deserto, floresta, montanha, pântano, planície, subterrâneo ou urbano. A partir do 11º nível, também pode escolher área de Tormenta. Quando estiver no terreno escolhido, soma sua Sabedoria, mínimo +1, na Defesa e em testes de Acrobacia, Atletismo, Furtividade, Percepção e Sobrevivência. A cada quatro níveis, escolha outro terreno ou aumente o bônus de um terreno já escolhido em +2.`);
  set("*|instintoselvagem",`Você recebe +1 em rolagens de dano, Percepção e Reflexos. A cada seis níveis, esse bônus aumenta em +1.`);

  set("arcanista|caminhodoarcanista",`A magia tem fontes distintas e cada uma opera conforme suas próprias regras. Escolha uma das opções a seguir; uma vez feita, essa escolha não pode ser mudada. Bruxo: você lança magias através de um foco e precisa empunhá-lo ou fazer teste de Misticismo (CD 20 + custo em PM da magia); se falhar, a magia não funciona, mas os PM são gastos. O foco tem RD 10 e PV iguais à metade dos seus; se for destruído, você fica atordoado por uma rodada e pode recuperá-lo com uma semana de trabalho e T$ 100. Seu atributo-chave é Inteligência. Feiticeiro: você lança magias por poder inato, escolhe uma linhagem e recebe sua herança básica. Não depende de item ou estudo, mas aprende magia nova apenas a cada nível ímpar. Seu atributo-chave é Carisma. Mago: você lança magias por estudo e memorização; só pode lançar magias memorizadas. Para memorizar, estuda o grimório por uma hora e escolhe metade das magias que conhece, uma vez por dia. O grimório tem as mesmas estatísticas de um foco e pode ser recuperado da mesma forma. Você começa com uma magia adicional e aprende uma magia adicional sempre que ganha acesso a um novo círculo. Seu atributo-chave é Inteligência.`);
  set("arcanista|altaarcana",`No 20º nível, seu domínio das artes arcanas é total. O custo em PM de suas magias arcanas é reduzido à metade, após aplicar aprimoramentos e quaisquer outros efeitos que reduzam custo.`);
  set("sentinela|magias",`Como o arcanista básico, você lança magias arcanas, começando com magias de 1º círculo. A progressão do sentinela libera 2º círculo no 5º nível, 3º círculo no 9º nível, 4º círculo no 13º nível e 5º círculo no 17º nível. Seu Caminho do Sentinela define Inteligência como atributo-chave para lançar magias.`);
  set("sentinela|caminhodosentinela",`Você lança magias misturando combate e feitiçaria. Para lançar uma magia em combate, deve empunhar uma arma com a qual seja proficiente com uma mão e gesticular com a outra, ou fazer um teste de Misticismo (CD 20 + o custo em PM da magia). Se falhar, a magia não funciona, mas você gasta os PM mesmo assim. Fora de combate, deve pelo menos estar com uma das mãos sobre esta arma, como segurando no cabo de uma espada embainhada, ou precisa fazer o mesmo teste. Você não precisa fazer testes de Misticismo para lançar magias arcanas se estiver usando uma armadura leve, e também recebe uma armadura leve como equipamento inicial no 1º nível. Seu atributo-chave para lançar magias é Inteligência. Além disso, sentinelas recebem proficiência com armas marciais.`);
  set("sentinela|gladiomancia",`Você pode gastar uma ação de movimento e 2 PM para evocar palavras de poder mágico e imbuir essência arcana em uma arma corpo a corpo leve ou ágil que esteja empunhando. Enquanto empunhar esta arma ou até o fim da cena, o que acontecer primeiro, você pode somar sua Inteligência em vez de Destreza na Defesa. Além disso, usa Inteligência em testes de Luta, em vez de Força, e pode somar sua Inteligência em rolagens de dano usando esta arma, limitado pelo seu nível.`,{cost:"2 PM",action:"Movimento"});
  set("sentinela|magodecombate",`Quando faz um ataque usando uma arma sob efeito de Gladiomancia, você soma o círculo máximo de magias que pode lançar à rolagem de dano. Além disso, a mão da arma é considerada livre para lançar magias.`);
  set("sentinela|ataqueextra",`A partir do 8º nível, quando usa a ação agredir, você pode gastar 2 PM para realizar um ataque adicional uma vez por rodada.`,{cost:"2 PM",action:"Ao agredir"});
  set("sentinela|mestrearcanocombatente",`No 20º nível, você pode usar Gladiomancia como ação livre. Enquanto empunhar uma arma sob o efeito de Gladiomancia, suas habilidades de sentinela, incluindo magias, têm seu custo em PM reduzido pela metade, após aplicar aprimoramentos e quaisquer outros efeitos que reduzam custo.`);

  set("barbaro|furia",`Você pode gastar 2 PM para invocar uma fúria selvagem. Recebe +2 em testes de ataque e rolagens de dano corpo a corpo, mas não pode fazer nenhuma ação que exija calma e concentração, como usar Furtividade ou lançar magias. A cada cinco níveis, pode gastar +1 PM para aumentar os bônus em +1. A Fúria termina se, ao fim da rodada, você não tiver atacado nem sido alvo de um efeito hostil.`);
  set("barbaro|reducaodedano",`A partir do 5º nível, graças a seu vigor e força de vontade, você ignora parte de seus ferimentos. Você recebe redução de dano 2; todo dano que sofre é reduzido em 2. A cada três níveis, sua RD aumenta em 2, até RD 10 no 17º nível.`);
  set("barbaro|furiatitanica",`No 20º nível, o bônus que você recebe nos testes de ataque e rolagens de dano quando usa Fúria é dobrado. Por exemplo, se gastar 5 PM, em vez de um bônus de +5, recebe +10.`);

  set("bardo|inspiracao",`Você pode gastar uma ação padrão e 2 PM para inspirar as pessoas com sua arte. Você e todos os seus aliados em alcance curto ganham +1 em testes de perícia até o fim da cena. A cada quatro níveis, pode gastar +2 PM para aumentar o bônus em +1.`);
  set("bardo|ecletico",`A partir do 2º nível, quando vai fazer um teste de perícia, você pode gastar 1 PM para receber os benefícios de ser treinado nessa perícia para este teste.`);
  set("bardo|artistacompleto",`No 20º nível, você pode usar Inspiração como uma ação livre. Enquanto estiver sob efeito de sua Inspiração, suas habilidades de bardo, incluindo magias, têm custo em PM reduzido pela metade, após aplicar aprimoramentos e quaisquer outros efeitos que reduzam custo.`);

  set("bucaneiro|audacia",`Quando faz um teste de perícia, você pode gastar 2 PM para somar seu Carisma no teste. Você não pode usar esta habilidade em testes de ataque.`);
  set("bucaneiro|panache",`A partir do 5º nível, sempre que faz um acerto crítico em combate ou reduz um inimigo a 0 PV, você recupera 1 PM. Você também recupera 1 PM quando cumpre uma bravata. A recuperação por Panache é limitada pelo seu Carisma por cena.`);
  set("bucaneiro|sortedenimb",`No 20º nível, uma vez por rodada, quando faz um teste, você pode rolar novamente o dado. Você deve aceitar o segundo resultado, mesmo que seja pior.`);

  set("cacador|caminhodoexplorador",`No 5º nível, você pode atravessar terrenos difíceis sem sofrer redução em seu deslocamento e a CD para rastrear você aumenta em +10. Esta habilidade só funciona em terrenos nos quais você tenha a habilidade Explorador.`);
  set("cacador|mestrecacador",`No 20º nível, você pode usar Marca da Presa como uma ação livre. Além disso, quando usa a habilidade, pode pagar 5 PM para aumentar sua margem de ameaça contra a criatura em +2. Se reduz uma criatura contra a qual usou Marca da Presa a 0 PV, recupera 5 PM.`);

  set("cavaleiro|caminhodocavaleiro",`No 5º nível, escolha entre Bastião ou Montaria. Bastião: se estiver usando armadura pesada, você recebe redução de dano 5, cumulativa com a RD de Especialização em Armadura. Montaria: você recebe um cavalo de guerra com o qual possui +5 em Adestramento e Cavalgar. Ele fornece benefícios de parceiro veterano de seu tipo; no 11º nível, passa a parceiro mestre. Se a montaria morrer, você pode comprar outra pelo preço normal e treiná-la com uma semana de trabalho.`);
  set("cavaleiro|resoluto",`A partir do 11º nível, você pode gastar 1 PM para refazer um teste de resistência contra uma condição que esteja afetando você, como abalado ou paralisado. O segundo teste recebe +5 e, se você passar, cancela o efeito. Você só pode usar esta habilidade uma vez por efeito.`);
  set("cavaleiro|bravurafinal",`No 20º nível, sua virtude vence a morte. Se for reduzido a 0 PV ou menos, pode gastar 3 PM para continuar consciente e de pé. Esta habilidade tem duração sustentada. Quando se encerra, você sofre os efeitos de seus PV atuais, podendo cair inconsciente ou morrer.`);

  set("clerigo|maodadivindade",`No 20º nível, você pode gastar uma ação completa e 15 PM para canalizar energia divina. Ao fazer isso, lança três magias divinas quaisquer, de qualquer círculo e incluindo magias que não conhece, como uma ação livre e sem gastar PM, mas ainda precisa pagar outros custos. Você pode aplicar aprimoramentos, mas precisa pagar por eles. Após usar esta habilidade, fica atordoado por 1d4 rodadas, mesmo se for imune a esta condição.`);

  set("druida|caminhodosermos",`No 2º nível, você pode atravessar terrenos difíceis sem sofrer redução em seu deslocamento e a CD para rastrear você aumenta em +10. Esta habilidade só funciona em terrenos naturais.`);
  set("druida|forcadanatureza",`No 20º nível, você diminui o custo de todas as suas magias em -2 PM e aumenta a CD delas em +2. Esses bônus dobram, para -4 PM e +4 na CD, se você estiver em terrenos naturais.`);

  set("guerreiro|ataqueespecial",`Quando faz um ataque, você pode gastar 1 PM para receber +4 no teste de ataque ou na rolagem de dano. A cada quatro níveis, pode gastar +1 PM para aumentar o bônus em +4. Você pode dividir os bônus igualmente; por exemplo, no 17º nível, pode gastar 5 PM para receber +20 no ataque, +20 no dano ou +10 em cada.`);
  set("guerreiro|durao",`A partir do 3º nível, sua rijeza muscular permite absorver ferimentos. Sempre que sofre dano, você pode gastar 3 PM para reduzir esse dano à metade.`);
  set("guerreiro|ataqueextra",`A partir do 6º nível, quando usa a ação agredir, você pode gastar 2 PM para realizar um ataque adicional uma vez por rodada.`);
  set("guerreiro|campeao",`No 20º nível, o dano de todos os seus ataques aumenta em um passo. Além disso, sempre que faz um Ataque Especial ou Golpe Pessoal e acerta o ataque, recupera metade dos PM gastos nele.`);

  set("inventor|prototipo",`Você começa o jogo com um item superior, ou com 10 itens alquímicos, com preço total de até T$ 500.`);
  set("inventor|fabricaritemsuperior",`No 2º nível, você recebe um item superior com preço de até T$ 2.000 e passa a poder fabricar itens superiores com uma melhoria. Nos níveis 5, 8 e 11, pode substituir esse item por um item superior com duas, três e quatro melhorias, respectivamente, e passa a poder fabricar itens superiores com essa quantidade de melhorias. Considera-se que você estava trabalhando nesses itens e não gasta dinheiro ou tempo neles, mas gasta em itens que fabricar futuramente.`);
  set("inventor|comerciante",`No 3º nível, você pode vender itens 10% mais caro. Este benefício não é cumulativo com barganha.`);
  set("inventor|encontrarfraqueza",`A partir do 7º nível, você pode gastar uma ação de movimento e 2 PM para analisar um objeto em alcance curto. Se fizer isso, ignora a redução de dano dele. Você também pode usar esta habilidade para encontrar fraqueza em um inimigo; se ele estiver de armadura ou for um construto, recebe +2 em testes de ataque contra ele. Os benefícios duram até o fim da cena.`);
  set("inventor|fabricaritemmagico",`No 9º nível, você recebe um item mágico menor e passa a poder fabricar itens mágicos menores. Nos níveis 13 e 17, pode substituir esse item por um item mágico médio e maior, respectivamente, e passa a poder fabricar itens mágicos dessas categorias. Considera-se que você estava trabalhando nos itens que recebe e não gasta dinheiro, tempo ou PM neles, mas gasta nos itens que fabricar futuramente.`);
  set("inventor|olhododragao",`A partir do 10º nível, você pode gastar uma ação completa para analisar um item. Você automaticamente descobre se o item é mágico, suas propriedades e como utilizá-las.`);
  set("inventor|obraprima",`No 20º nível, você fabrica sua obra-prima, aquela pela qual seu nome será lembrado em eras futuras. Você é livre para criar as regras do item, mas ele deve ser aprovado pelo mestre. Como linha geral, pode ter benefícios equivalentes aos de um item com cinco melhorias e quatro encantos. Considera-se que você estava trabalhando no item e não gasta dinheiro, tempo ou PM nele.`);

  set("ladino|ataquefurtivo",`Uma vez por rodada, quando atinge uma criatura desprevenida com um ataque corpo a corpo ou em alcance curto, ou uma criatura que esteja flanqueando, você causa 1d6 pontos de dano extra. A cada dois níveis, esse dano extra aumenta em +1d6. Uma criatura imune a acertos críticos também é imune a ataques furtivos.`);
  set("ladino|especialista",`Escolha um número de perícias treinadas igual à sua Inteligência, exceto bônus temporários, mínimo 1. Ao fazer um teste de uma dessas perícias, você pode gastar 1 PM para dobrar seu bônus de treinamento. Você não pode usar esta habilidade em testes de ataque.`);
  set("ladino|apessoacertaparaotrabalho",`No 20º nível, você se torna um mestre da ladinagem. Ao fazer um ataque furtivo ou usar uma perícia da lista de ladino, você pode gastar 5 PM para receber +10 no teste.`);

  set("lutador|golperelampago",`Quando usa a ação agredir para fazer um ataque desarmado, você pode gastar 1 PM para realizar um ataque desarmado adicional.`);
  set("lutador|golpecruel",`No 5º nível, você acerta onde dói. Sua margem de ameaça com ataques desarmados aumenta em +1.`);
  set("lutador|golpeviolento",`No 9º nível, você bate com muita força. Seu multiplicador de crítico com ataques desarmados aumenta em +1.`);
  set("lutador|donodarua",`No 20º nível, seu dano desarmado aumenta para 2d10, para criaturas Médias. Além disso, quando usa a ação agredir para fazer um ataque desarmado, pode fazer dois ataques em vez de um, podendo usar Golpe Relâmpago para fazer um terceiro.`);

  set("nobre|autoconfianca",`Você pode usar seu Carisma em vez de Destreza na Defesa, mas continua não podendo somar um atributo na Defesa quando usa armadura pesada.`);
  set("nobre|espolio",`Você recebe um item a sua escolha com preço de até T$ 2.000.`);
  set("nobre|palavrasafiadas",`No 2º nível, você pode gastar uma ação padrão e 1 PM para fazer um teste de Diplomacia ou Intimidação oposto ao teste de Vontade de uma criatura inteligente (Int -3 ou maior) em alcance curto. Se vencer, causa 2d6 pontos de dano psíquico não letal; se perder, causa metade. Se a criatura for reduzida a 0 PV ou menos, em vez de cair inconsciente, ela se rende se você usou Diplomacia, ou fica apavorada e foge se usou Intimidação. A cada quatro níveis, pode gastar +1 PM para aumentar o dano conforme a tabela da classe.`);
  set("nobre|riqueza",`No 3º nível, você passa a receber dinheiro de sua família, patrono ou negócios. Uma vez por aventura, pode fazer um teste de Carisma com bônus igual ao seu nível de nobre. Você recebe Tibares de ouro iguais ao resultado do teste. O uso depende de sua relação com a fonte do dinheiro e de onde você está.`);
  set("nobre|gritarordens",`A partir do 4º nível, você pode gastar uma quantidade de PM a sua escolha, limitada pelo seu Carisma. Até o início do seu próximo turno, todos os seus aliados em alcance curto recebem bônus nos testes de perícia igual à quantidade de PM gasta.`);
  set("nobre|presencaaristocratica",`A partir do 5º nível, sempre que uma criatura inteligente tentar machucá-lo, causando dano com ataque, magia ou habilidade, você pode gastar 2 PM. Se fizer isso, a criatura faz um teste de Vontade (CD Car). Se falhar, não consegue machucá-lo e perde a ação. Você só pode usar esta habilidade uma vez por cena contra cada criatura.`);
  set("nobre|realeza",`No 20º nível, a CD para resistir à sua Presença Aristocrática aumenta em +5 e uma criatura que falhe no teste de Vontade por 10 ou mais se arrepende tanto de tentar machucá-lo que passa a lutar ao seu lado e seguir suas ordens, se puder entendê-lo, pelo resto da cena. Além disso, uma criatura reduzida a 0 PV por Palavras Afiadas não sofre esse dano; em vez disso, passa a lutar ao seu lado pelo resto da cena.`);

  set("paladino|golpedivino",`Quando faz um ataque corpo a corpo, você pode gastar 2 PM para desferir um golpe destruidor. Você soma seu Carisma ao teste de ataque e +1d8 à rolagem de dano. A cada quatro níveis, pode gastar +1 PM para aumentar o dano em +1d8.`);
  set("paladino|curapelasmaos",`A partir do 2º nível, você pode gastar uma ação de movimento e 1 PM para curar 1d8+1 PV por luz em um alvo em alcance corpo a corpo, incluindo você. A cada quatro níveis, pode gastar +1 PM para aumentar a cura em +1d8+1. Esta habilidade causa dano de luz a mortos-vivos (CD Car). A partir do 6º nível, pode gastar +1 PM ao usar Cura pelas Mãos para anular uma condição afetando o alvo entre abalado, apavorado, atordoado, cego, doente, exausto, fatigado ou surdo.`);
  set("paladino|aurasagrada",`No 3º nível, você pode gastar 1 PM para gerar uma aura com 9m de raio a partir de você e duração sustentada. A aura emite luz dourada e agradável. Você e aliados dentro da aura somam seu Carisma em testes de resistência.`);
  set("paladino|bencaodajustica",`No 5º nível, escolha Égide Sagrada ou Montaria Sagrada. Égide Sagrada: você pode gastar uma ação de movimento e 2 PM para recobrir seu escudo ou símbolo sagrado de energia até o fim da cena; você e aliados adjacentes somam seu Carisma na Defesa. A partir do 11º nível, quando faz um teste de resistência contra magia lançada contra você, pode gastar 5 PM para rolá-lo novamente; se passar e a magia tiver apenas você como alvo, ela é revertida ao conjurador. Montaria Sagrada: você pode gastar uma ação de movimento e 2 PM para invocar uma montaria sagrada, que aparece ao seu lado e fica até o fim da cena, ou pode ser tratada como montaria mundana em campanhas mais realistas.`);
  set("paladino|vingadorsagrado",`No 20º nível, você pode gastar uma ação completa e 10 PM para se cobrir de energia divina, assumindo forma de vingador sagrado até o fim da cena. Nesta forma, recebe deslocamento de voo 18m e RD 20. Além disso, seu Golpe Divino tem custo reduzido pela metade e causa mais dois dados de dano.`);

  set("treinador|direcionar",`Se o seu melhor amigo estiver em alcance curto e fizer um teste de perícia, você pode gastar 2 PM para somar seu Carisma no teste dele.`);
  set("treinador|melhoramigo",`Você recebe um melhor amigo, um parceiro especial que acompanha você em suas aventuras. Ele começa com dois truques à sua escolha e recebe um novo truque a cada três níveis seguintes. Caso seu melhor amigo morra, você fica atordoado por 1d4 rodadas. Você pode treinar um novo melhor amigo com um mês de trabalho.`);
  set("treinador|domarcriatura",`A partir do 2º nível, você pode gastar uma ação de movimento e 1 PM para fazer um teste de Adestramento oposto ao teste de Vontade de uma criatura não inteligente em alcance curto. Se vencer, causa 2d8 pontos de dano psíquico não letal à criatura; se perder, causa metade. Se ela for reduzida a 0 PV ou menos, rende-se em vez de cair inconsciente. A cada quatro níveis, pode gastar +1 PM para aumentar o dano em +2d8. A partir do 5º nível, quando rende uma criatura com ND igual ou menor que seu nível, pode gastar PM iguais ao ND dela para curá-la totalmente e controlar suas ações até o fim da cena. A partir do 8º nível, se o ND for igual ou menor que seu nível -3, ela fica com você até o fim do dia. Enquanto controlada, conta em seu limite de parceiros. Algumas criaturas podem ser indomáveis, a critério do mestre.`);
  set("treinador|treinoespecializado",`No 5º nível, escolha entre Conquistar pelos Números e Treino Intensivo. Conquistar pelos Números: você recebe um segundo melhor amigo e, uma vez por rodada, quando faz uma ação padrão com um deles, pode gastar 3 PM para fazer uma ação padrão com o outro. Treino Intensivo: seu melhor amigo recebe +4 PV por nível, RD 5 e um truque; no 11º nível a RD aumenta para 10 e ele recebe outro truque; no 17º nível a RD aumenta para 15.`);
  set("treinador|sincroniadecombate",`A partir do 6º nível, uma vez por rodada, quando seu melhor amigo acerta um ataque usando a ação agredir, você pode gastar 2 PM para fazer um ataque contra o mesmo alvo.`);
  set("treinador|sincroniaperfeita",`No 20º nível, você pode gastar uma ação de movimento e 6 PM para entrar em sincronia perfeita com um de seus melhores amigos. Até o fim da cena, o tamanho dele aumenta em uma categoria. Além disso, uma vez por rodada, quando usa uma ação padrão consigo mesmo, você recebe uma ação padrão extra para usar com ele.`);

  set("frade|erudicao",`Quando faz um teste de perícia, exceto ataque, você pode gastar uma quantidade de PM à sua escolha, limitada pela sua Inteligência. Para cada PM gasto, recebe +2 no teste.`);
  set("frade|versiculario",`No 2º nível, você recebe um versiculário, um livro de anotações religiosas pessoais. Uma vez por dia, pode gastar 1 hora estudando suas anotações. Quando faz isso, escolha uma quantidade de magias igual à sua Inteligência, limitada pelo seu nível. Até o próximo dia, quando lança uma dessas magias, recebe +1 PM para gastar em aprimoramentos. Se perder seu versiculário, pode escrever outro com 1 semana de trabalho e T$ 100.`);
  set("frade|dadivadafe",`No 5º nível, você recebe Proteção Sagrada se sua divindade canaliza energia positiva, ou Cólera Divina se canaliza energia negativa. Proteção Sagrada: você pode gastar uma ação de movimento e até 2 PM por círculo de magia a que tem acesso para energizar seu símbolo sagrado até o fim da cena; enquanto empunha o símbolo, ele projeta aura de 9m e criaturas à sua escolha dentro dela recebem RD igual à metade dos PM gastos. Cólera Divina: funciona da mesma forma, mas criaturas à sua escolha dentro da aura recebem bônus em rolagens de dano igual à metade dos PM gastos.`);
  set("frade|solosantificado",`No 20º nível, o raio de sua Dádiva da Fé muda para 30m e criaturas afetadas por ela também somam o bônus concedido pela habilidade na CD de suas próprias habilidades.`);

  set("alquimista|laboratoriopessoal",`Você começa o jogo com instrumentos de alquimista aprimorados e 10 itens alquímicos com preço total de até T$ 300.`);
  set("alquimista|alquimistainiciado",`No 2º nível, você recebe o poder Alquimista Iniciado.`);
  set("alquimista|misturabasica",`A partir do 3º nível, você pode usar catalisadores em itens alquímicos como se fossem magias.`);
  set("alquimista|aplicacaorapida",`No 5º nível, você pode gastar uma ação completa e 2 PM para usar dois preparados alquímicos ao mesmo tempo. Você precisa ter ambos em suas mãos ou ser capaz de sacá-los como ação livre.`);
  set("alquimista|magiaengarrafada",`No 7º nível, você pode usar Mistura Básica e Aplicação Rápida em poções.`);
  set("alquimista|odoresalquimicos",`A partir do 8º nível, você pode gastar uma ação completa para detectar a presença de itens alquímicos e poções em alcance médio. No caso de itens alquímicos, descobre seu tipo, como preparado ou veneno, e uso geral, como curar ou fornecer bônus. Para poções, identifica qual magia ela emula e com quantos PM foi fabricada.`);
  set("alquimista|fabricaremulsao",`No 9º nível, você aprende a fabricar emulsões com um encanto. Nos níveis 13 e 17, aprende a fabricar emulsões com respectivamente dois e três encantos.`);
  set("alquimista|mestrealquimista",`No 10º nível, você recebe o poder Mestre Alquimista.`);
  set("alquimista|bombardeioeficiente",`A partir do 11º nível, quando usa um preparado alquímico ou uma poção que causa dano, você pode gastar 1 PM para que esse item ignore 10 pontos da redução de dano das criaturas atingidas.`);
  set("alquimista|pedrafilosofal",`No 20º nível, você recebe uma pedra filosofal. Enquanto estiver de posse dela, tem Cura Acelerada 10 e, quando faz teste de Fortitude, rola dois dados e usa o melhor resultado. Além disso, se você ou um aliado em alcance curto for reduzido a 0 PV ou morrer, pode sacrificar a pedra para salvar essa criatura, fornecendo o efeito básico de Segunda Chance e reconstruindo o corpo se tiver sido destruído ou desintegrado. Você só pode ter uma pedra filosofal por vez; se perdê-la, pode fabricar outra com uma semana de trabalho e T$ 18.000.`);

  set("atleta|facanhaatletica",`Você é treinado para feitos físicos extremos. Esta habilidade representa a base atlética do personagem e funciona em conjunto com as demais habilidades de atleta, especialmente Briga e Arremesso Atlético.`);
  set("atleta|arremessoatletico",`Quando ataca com armas de arremesso adequadas ao seu treinamento, pode usar o dano da habilidade Briga no lugar do dano básico da arma. A partir do 10º nível, seus ataques com armas de arremesso contam como ataques desarmados para efeito de suas habilidades de lutador.`);
  set("atleta|poderiomuscular",`No 2º nível, você aprende e pode lançar Primor Atlético, mas apenas em si mesmo. Esta não é uma habilidade mágica e provém de seu extenso treinamento físico.`);
  set("atleta|maisaltoemaisrapido",`No 5º nível, seu deslocamento aumenta em +3m. Além disso, você recebe deslocamento de escalada e natação igual à metade do seu deslocamento normal; se já possui esses deslocamentos, eles aumentam em +3m. Esse deslocamento de natação não permite respirar debaixo d'água, mas você soma seu nível de atleta ao total de rodadas em que consegue prender a respiração.`);
  set("atleta|disciplinaatletica",`A partir do 9º nível, quando falha em um teste de resistência, você pode gastar 2 PM para rolar esse teste novamente, usando Atletismo no lugar da perícia original.`);
  set("atleta|corpoideal",`No 20º nível, você atinge o ápice físico de um corpo mortal. Recebe imunidade a cansaço, condições de metabolismo e veneno, RD 10 e seu dano desarmado e com armas de arremesso aumenta para 2d10, para criaturas Médias.`);

  set("burgues|meiosdeproducao",`No início de cada aventura, você recebe T$ 100 em dinheiro, itens mundanos ou poções à sua escolha. Esse valor aumenta para T$ 300 no patamar veterano, T$ 600 no campeão e T$ 1.000 no lenda.`);
  set("burgues|podermonetario",`Quando usa uma habilidade com custo em PM, você pode consumir uma quantidade de tibares de ouro limitada pelo seu Carisma. Cada TO consumido paga 1 PM do custo da habilidade. Você pode consumir um número de TO por dia igual ao seu nível; no 5º nível, esse limite aumenta para o dobro do seu nível.`);
  set("burgues|desmoralizar",`No 2º nível, você aprende e pode lançar Perdição, e pode usar seus aprimoramentos como se tivesse acesso aos mesmos círculos de magia que um clérigo de seu nível. Entretanto, pode lançá-la apenas em criaturas inteligentes (Int -3 ou maior). Esta não é uma habilidade mágica e provém da sua capacidade de abalar a autoconfiança de outras pessoas.`);
  set("burgues|negociantenato",`No 3º nível, quando chega a uma nova comunidade, pode gastar 1 dia fazendo contatos com o comércio local e fazer um teste de Diplomacia (CD 20). Se passar, pode vender itens nessa comunidade por 60% do preço, em vez de 50%. Para cada 10 pontos pelos quais exceder a CD, aumenta o preço de venda em +10%, até 100%. Esta habilidade não se acumula com barganha e NPCs ainda só compram o que desejam e conseguem pagar.`);
  set("burgues|suborno",`No 4º nível, você aprende e pode lançar Enfeitiçar, com atributo-chave Carisma. Esta não é uma habilidade mágica e provém de sua capacidade de instigar os outros com promessas de enriquecimento. A CD para resistir aumenta em +2 se você tiver consumido pelo menos 1 TO para pagar seu custo.`);
  set("burgues|ostentacao",`A partir do 5º nível, você pode se beneficiar de um item vestido adicional. Além disso, a CD para resistir às suas habilidades de burguês aumenta em +1 se você possuir um item banhado a ouro, cravejado de gemas ou de mitral. Esse aumento é cumulativo; possuir três itens diferentes com as três modificações aumenta a CD em +3.`);
  set("burgues|novorico",`No 9º nível, para cada item mágico que estiver vestindo, você recebe +1 PM por nível de poder do item, somente após 1 dia de uso.`);
  set("burgues|magnata",`No 20º nível, quando usa Desmoralizar, a penalidade em testes de ataque também se aplica à CD das habilidades das criaturas afetadas. Além disso, sempre que consome um tibar de ouro para pagar PM de uma habilidade, reforça sua pressão econômica conforme a regra de Poder Monetário.`);

  set("duelista|escoladeduelo",`No 2º nível, escolha uma escola de duelo. Escola Ambidestra: se estiver empunhando duas armas, e pelo menos uma for leve, recebe +2 na Defesa e em Reflexos. Escola Clássica: se estiver usando uma arma corpo a corpo em uma das mãos e nada na outra, recebe +2 em rolagens de dano com essa arma. Escola de Tiro: recebe proficiência com armas de fogo leves e de uma mão; caso receba essa proficiência novamente, com essas armas pode usar suas habilidades de bucaneiro normalmente usadas com armas corpo a corpo leves ou ágeis.`);
  set("duelista|truquesdecapa",`A partir do 4º nível, se estiver usando uma capa esvoaçante ou item semelhante aprovado pelo mestre, pode gastar 2 PM e a ação indicada para gerar um efeito. Capa Inoportuna (livre): reduz a ação necessária para fintar em um passo até o fim do turno. Distração Oportuna (reação): recebe +5 em um teste de Reflexos ou Vontade. Efeito Dramático (livre): recebe +5 em um teste de perícia baseada em Carisma feito nesse turno. Impulso (livre): recebe deslocamento +9m e +5 em Acrobacia e Atletismo por 1 rodada. Paraquedas (reação): reduz dano de queda em 6d6. Rasgar a Capa (reação): quando sofre dano, reduz esse dano à metade e destrói a capa.`);
  set("duelista|tecnicaavancada",`No 10º nível, aprende uma técnica conforme sua escola de duelo, que só pode usar enquanto estiver usando sua escola. Escola Ambidestra: uma vez por rodada, se uma criatura atacá-lo e errar, pode gastar 1 PM para fazer um ataque corpo a corpo contra ela, se estiver em seu alcance. Escola Clássica: o dano da escola aumenta para +5; uma vez por rodada, quando usa a ação agredir, pode gastar 1 PM e, se pelo menos um ataque for crítico, faz um ataque adicional nessa ação. Escola de Tiro: seu dano com armas de fogo aumenta em um passo e o alcance dessas armas aumenta em uma categoria.`);
  set("duelista|duelistalendario",`No 20º nível, seu domínio da escola atinge o ápice. Quando faz um ataque usando sua escola de duelo, pode gastar 1 PM para rolá-lo novamente. Quando um oponente o ataca enquanto você usa sua escola de duelo, pode gastar 1 PM para forçá-lo a rolar o teste novamente, apenas uma vez por ataque.`);

  set("ermitao|sitiosagrado",`No 3º nível, você assume um local sagrado para sua divindade: uma área erma com 5 km de raio que serve como refúgio e base. Se o sítio for destruído, você perde todos os PM e só pode recuperá-los ao criar um novo. Ao receber o sítio, escolhe um terreno associado; nesse terreno, soma Sabedoria, mínimo +1, em Furtividade, Percepção, Misticismo, Religião e Sobrevivência. No 7º nível e a cada quatro níveis, escolhe mais um terreno associado ou aumenta em +2 o bônus de perícias de um terreno já escolhido. O sítio também melhora atitudes de criaturas não inteligentes, permite caminhos sagrados e conta como base básica.`);
  set("ermitao|vinculocomaterra",`No 5º nível, quando você estiver em um terreno de um dos tipos de seu sítio sagrado, suas magias custam -1 PM, cumulativo com outras reduções. Dentro do próprio sítio sagrado, esse redutor muda para -2 PM.`);
  set("ermitao|temperadopeloclima",`No 11º nível, você recebe RD 5 contra tipos de dano correspondentes aos terrenos associados ao seu sítio sagrado: aquático (eletricidade), ártico (frio), colina (impacto), deserto (fogo), floresta (corte), montanha (perfuração), pântano (ácido), planície (luz) e subterrâneo (trevas).`);
  set("ermitao|eixodepedras",`No 20º nível, você cria um eixo de pedras ritualísticas em seu sítio sagrado. Uma vez por aventura, pode lançar no eixo uma quantidade de magias cujo custo total em PM seja igual ao seu nível + Sabedoria. Essas magias devem ter execução de movimento, padrão ou completa. Até o fim da aventura, se estiver em terreno associado ao sítio, uma vez por rodada pode descarregar uma dessas magias como ação livre sem pagar seu custo.`);

  set("inovador|dobomedomelhor",`Você começa o jogo com uma arma, armadura ou escudo superior à sua escolha, de até T$ 500. Entretanto, é considerado não proficiente em qualquer arma, armadura ou escudo que não seja superior ou mágico.`);
  set("inovador|sequenciaespecial",`Você pode gastar 2 PM para iniciar uma sequência de movimentos inovadores. A cada vez que ataca com uma arma que ainda não tenha usado nessa sequência, recebe +1 em testes de ataque e rolagens de dano, cumulativo até +2. A cada 4 níveis, pode gastar +1 PM para aumentar o limite desses bônus em +2. A sequência termina no fim da cena ou se você ficar 1 rodada sem trocar pelo menos uma arma.`);
  set("inovador|bombardeiosequencial",`No 2º nível, você pode usar Sequência Especial ao usar itens alquímicos ou poções. Nesse caso, aplica o bônus de ataque acumulado à CD para resistir ao item.`);
  set("inovador|acrobaciadefensiva",`A partir do 3º nível, quando sofre dano, você pode gastar 2 PM para executar uma pirueta defensiva. Faça um teste de Acrobacia e subtraia o resultado desse teste do dano sofrido.`);
  set("inovador|dominioexcentrico",`A partir do 4º nível, sempre que passar pelo menos uma semana carregando uma arma exótica ou de fogo superior ou mágica, recebe proficiência nela.`);
  set("inovador|tecnicaexcentrica",`A partir do 7º nível, você pode gastar 2 PM para, até o fim do combate, usar armas que esteja empunhando como se elas tivessem uma habilidade de arma à sua escolha: adaptável, ágil, alongada, dupla (use as estatísticas da arma em ambas as pontas) ou versátil para uma manobra escolhida ao usar esta habilidade. O efeito termina se você ativar a técnica novamente.`,{name:"Técnica Excêntrica"});
  set("inovador|estilounico",`No 20º nível, escolha dois poderes de guerreiro ou combate que possua. Para esses poderes, você ignora todos os requisitos e restrições relacionados a armas, incluindo propósito, empunhadura, características e habilidades das armas. O mestre tem a palavra final sobre como os poderes interagem entre si.`);

  set("machado_de_pedra|grunhidos",`Você conhece apenas o idioma rústico da pequena comunidade onde viveu e nenhum outro. É incapaz de compreender outros dialetos e se comunica com grunhidos e sons simples. Contudo, conhece uma palavra no idioma valkar por nível de machado de pedra.`);
  set("machado_de_pedra|machadodepedra",`Você não recebe proficiência com armas simples. Sabe usar apenas adaga, azagaia, clava, funda, lança, machadinha e tacape. No 9º nível, aprende a usar uma arma simples ou marcial à sua escolha. Entretanto, quando ataca com arma natural, ataque desarmado ou uma dessas armas, recebe +1 no teste de ataque e na rolagem de dano.`);
  set("machado_de_pedra|tangadepeles",`Você não recebe proficiência com armaduras leves. Entretanto, se não estiver usando armadura, soma sua Constituição na Defesa. Além disso, no 3º nível e a cada quatro níveis seguintes, recebe +1 na Defesa.`);
  set("machado_de_pedra|furiaprimitiva",`A partir do 2º nível, se não estiver usando armadura e estiver empunhando uma das armas de Machado de Pedra, o custo de sua Fúria é reduzido em -1 PM. Além disso, uma vez por cena, quando entra em fúria, recebe PV temporários iguais ao seu nível + Constituição.`);
  set("machado_de_pedra|resilienciaprimal",`A partir do 5º nível, graças a seu vigor e força de vontade, você ignora parte de seus ferimentos. Recebe RD 3. A cada três níveis, sua RD aumenta em 3, até RD 15 no 17º nível.`);
  set("machado_de_pedra|furiarustica",`No 20º nível, quando entra em fúria, você pode gastar 5 PM. Se fizer isso, durante a fúria recebe Cura Acelerada 10, cumulativa com outras Curas Aceleradas, e, quando faz a ação agredir, pode fazer um ataque desarmado adicional.`);

  set("magimarcialista|cadenciamagimarcial",`Sempre que lança uma magia de bardo, recebe uma carga arcana. Sempre que faz a ação agredir, recebe uma carga marcial. Você pode acumular um máximo de cargas de cada tipo igual ao seu Carisma e elas duram até o fim da cena.`);
  set("magimarcialista|magificacao",`Se tiver pelo menos 1 carga arcana e 1 carga marcial, recebe +2 em testes de ataque e rolagens de dano e é considerado sob Inspiração para efeitos baseados nisso. A cada cinco níveis, esses bônus aumentam em +1.`);
  set("magimarcialista|bravadomagimarcial",`No 2º nível, quando lança uma magia, pode gastar 1 carga marcial para reduzir seu custo em -1 PM, cumulativo com outras reduções. Quando faz um ataque, pode gastar 1 carga arcana para receber +1d6 na rolagem de dano.`);
  set("magimarcialista|dancadefensiva",`No 3º nível, quando faz um teste de resistência, pode gastar 1 carga marcial para receber +5 nesse teste. Quando sofre dano, pode gastar 1 carga arcana para receber RD 10 contra esse dano.`);
  set("magimarcialista|artesublime",`A partir do 7º nível, quando usa Bravado Magimarcial ou Dança Defensiva, pode gastar uma carga adicional do tipo exigido para dobrar seu efeito.`);
  set("magimarcialista|crescendovitorioso",`No 20º nível, no início de cada combate, você recebe 1 carga arcana e 1 carga marcial. Além disso, soma seu total de cargas marciais à CD para resistir às suas habilidades de bardo e o total de cargas arcanas em seus testes de ataque e rolagens de dano.`);

  set("necromante|caminhodonecromante",`Você lança magias por meio de uma conexão com a morte. Pode aprender magias de necromancia divinas como se fossem arcanas, mas não pode aprender magias de encantamento e pelo menos metade das magias que aprender deve ser de necromancia.`);
  set("necromante|falarcommortos",`Você pode se comunicar com mortos-vivos por meio de seus poderes arcanos e usar Misticismo com mortos-vivos para mudar atitude e persuasão. A partir do 3º nível, pode gastar uma ação padrão e 1 PM para conversar com um cadáver em alcance curto. Esta habilidade funciona como Voz Divina, com o aprimoramento de conceder um pouco de vida a um cadáver.`);
  set("necromante|animarcadaver",`No 2º nível, você pode gastar uma ação completa e 3 PM para animar o cadáver de uma criatura Pequena, Média ou Grande em alcance curto. O cadáver se torna um parceiro iniciante de tipo adequado ao tamanho e anatomia, não conta em seu limite de parceiros, mas você só pode ter um parceiro cadáver por vez. Quando sofre dano, pode sacrificar o parceiro cadáver para reduzir esse dano à metade; cadáveres sacrificados não podem ser reanimados. A partir do 7º nível, pode gastar 6 PM para criar parceiro veterano e, a partir do 11º, 9 PM para parceiro mestre.`);
  set("necromante|necrologia",`No 3º nível, você recebe +2 em Cura, Fortitude e na CD para resistir às suas magias de necromancia. A cada cinco níveis, esse bônus aumenta em +1.`);
  set("necromante|distorcaonecrotica",`No 4º nível, escolha uma de suas magias conhecidas de 1º círculo que não seja de necromancia. A escola dessa magia muda para necromancia. Essa mudança não tem efeitos mecânicos além da troca de escola, mas altera a aparência e a natureza do efeito.`);
  set("necromante|necropotencia",`No 5º nível, quando estabelece sua conexão com a morte, você pode gastar o dobro de PV. Se fizer isso, sempre que reduzir um ou mais inimigos vivos a 0 PV ou menos com uma magia de necromancia, recebe 2 PM temporários. Você pode ganhar no máximo PM temporários por cena iguais ao seu nível. Esses pontos desaparecem no fim da cena.`);
  set("necromante|dominiosobreamorte",`No 20º nível, o custo em PM de suas magias de necromancia é reduzido à metade, após aprimoramentos e demais reduções. Além disso, quando mata uma criatura viva com uma magia de necromancia, pode gastar 2 PM para erguer seu cadáver como morto-vivo sob seu controle. Isso funciona como Servo Morto-Vivo, mas você escolhe o tipo de parceiro entre quaisquer aprimoramentos da magia e não paga componente material. Mortos-vivos erguidos assim não contam no limite de parceiros durante a cena; ao fim dela, excedentes voltam a ser cadáveres.`);

  set("santo|ladainhadecombate",`Você pode gastar uma ação padrão e 2 PM para gerar uma aura de 9m de raio com duração sustentada. Você e aliados dentro da aura recebem +1 em testes de ataque, rolagens de dano e Defesa. A cada quatro níveis, pode gastar +2 PM para aumentar esses bônus em +1. Sua ladainha conta como Aura Sagrada para pré-requisitos e efeitos de poderes de paladino. No 5º nível, você e aliados dentro da aura causam +1d8 de dano de luz com ataques contra devotos de deuses que canalizam apenas energia negativa e criaturas malignas, a critério do mestre. No 9º nível, suas armas e as dos aliados dentro da aura recebem o encanto veloz.`);
  set("santo|santocurandeiro",`A partir do 2º nível, você pode gastar uma ação de movimento e uma quantidade de PM à sua escolha, limitada pelo Carisma. Para cada PM gasto, o aliado em alcance médio com a maior redução em seus PV recupera 2d8 PV por luz. A partir do 6º nível, quando usa Santo Curandeiro, também pode remover uma condição do alvo entre abalado, apavorado, atordoado, cego, doente, exausto, fatigado ou surdo.`);
  set("santo|vasosagrado",`A partir do 3º nível, quando faz um teste de resistência, você pode gastar 1 PM para somar seu Carisma nesse teste.`,{name:"Vaso do Espírito"});
  set("santo|martir",`A partir do 6º nível, quando um aliado em alcance médio faz um teste de resistência, você pode gastar 1 PM para conceder a ele bônus nesse teste igual ao seu Carisma. A partir do 12º nível, uma vez por cena, se ele ainda assim falhar, você pode sofrer o efeito no lugar dele, mas é afetado mesmo que seja imune ao efeito.`);
  set("santo|pirasanta",`No 8º nível, enquanto estiver sob efeito de Ladainha de Combate, você pode gastar uma ação de movimento e uma quantidade de PM à sua escolha, limitada pelo Carisma. Para cada PM gasto, o inimigo de maior ND em alcance médio sofre 2d8 pontos de dano de luz e fica ofuscado por 1 rodada. Fortitude CD Car reduz à metade.`);
  set("santo|vingadorsantificado",`No 20º nível, quando usa Ladainha de Combate, você pode gastar +5 PM. Se fizer isso, os bônus numéricos fornecidos pela Ladainha dobram e você e aliados dentro da aura recebem imunidade a acertos críticos e RD igual a 5 + seu Carisma.`);

  set("seteiro|caminhodoatirador",`Você abriu mão do treinamento convencional de caçador para abraçar o caminho do atirador. Suas habilidades de seteiro relacionadas a ataques e armas só funcionam com arcos e bestas.`);
  set("seteiro|tirodesupressao",`Sempre que causa dano com arco ou besta em uma criatura sob efeito de sua Marca da Presa, essa criatura sofre penalidade cumulativa de -1 em rolagens de dano, até um valor igual à quantidade de PM gasta em Marca da Presa, até o fim da cena.`);
  set("seteiro|disparoconstritor",`No 5º nível, quando usa a ação mirar, você pode pagar 2 PM. Se fizer isso, pode executar uma manobra entre desarmar, empurrar ou quebrar com um de seus ataques à distância feitos até o fim desse turno.`);
  set("seteiro|rajadadeflechas",`Quando usa esta habilidade, faça um ataque à distância e compare-o com a Defesa de cada inimigo num raio de 3m do alvo. Então faça uma rolagem de dano, com bônus cumulativo de +2 para cada acerto, e aplique-a a cada inimigo atingido. Você gasta apenas uma munição, independentemente de quantos inimigos acertou.`);
  set("seteiro|sentinela",`No 15º nível, uma vez por rodada, quando uma criatura sob efeito de sua Marca da Presa acerta um ataque contra um aliado, você pode gastar 1 PM para fazer um ataque contra essa criatura.`);
  set("seteiro|mestredodisparo",`No 20º nível, você pode usar Marca da Presa como ação livre. Além disso, uma vez por rodada, quando faz um ataque com arco ou besta contra um alvo de sua Marca da Presa, pode fazer um ataque adicional contra ele.`);

  set("usurpador|inimigodosdeuses",`Por roubar o poder de todos os deuses, o usurpador não é aceito por nenhum. Você não pode ter nenhuma devoção.`);
  set("usurpador|usurpar",`Você pode lançar qualquer magia divina de um círculo a que tenha acesso. Para lançar uma magia dessa forma, deve passar em um teste de Enganação (CD 15 + custo em PM da magia). Se falhar, a magia é perdida, mas os PM são gastos. Você não pode escolher 10 nesse teste, mesmo que possua habilidade que permita isso, e sofre penalidade de armadura nele. Além disso, sofre -5 se estiver em local contendo símbolo sagrado visível.`);
  set("usurpador|canalizacaofalsa",`No 2º nível, você pode canalizar tanto energia positiva quanto negativa.`);
  set("usurpador|discricaodivina",`No 3º nível, você recebe +1 em Furtividade e testes de resistência. A cada seis níveis, esse bônus aumenta em +1.`);
  set("usurpador|podercapturado",`No 4º nível, escolha um deus maior por nível e um poder concedido desse deus. Você deve cumprir os pré-requisitos e não pode escolher poderes exclusivos de classe, inclusive clérigo. Você pode gastar uma hora e fazer um teste de Enganação (CD 20 +5 para cada uso adicional no mesmo dia). Se passar, é considerado devoto desse deus para efeitos de habilidades e itens e pode usar o poder concedido escolhido, sem seguir Obrigações & Restrições. Se falhar, perde 3 PM. O efeito dura até o fim do dia ou até você usá-lo novamente.`);
  set("usurpador|roubodivino",`No 20º nível, quando lança uma magia com Usurpar, para cada 10 pontos no resultado do teste de Enganação, o total de PM que você gasta nessa magia é reduzido em -1, cumulativo com outras reduções, e a CD para resistir a ela aumenta em +1.`);

  set("vassalo|jovempajem",`Você inicia sua carreira como pajem, servindo a um sir ou dame mais experiente. Você se torna treinado em Adestramento ou Ofício (armeiro).`);
  set("vassalo|suserano",`Escolha um membro da nobreza aprovado pelo mestre. Você serve a esse nobre e é oficialmente reconhecido como parte da corte. Como regra geral, recebe +5 em Diplomacia e Intimidação ao lidar com vassalos de seu suserano de nível inferior ao seu e, nas terras dele, pode obter alojamento e alimentação sem custo. Se deixar de servir a seu suserano, perde todos os PM e só pode recuperá-los após ser aceito por outro suserano.`);
  set("vassalo|valete",`A partir do 2º nível, você acompanha seu senhor na corte e nos salões nobres. Torna-se treinado em Diplomacia ou Nobreza e recebe um poder de cavaleiro à sua escolha.`);
  set("vassalo|escudeiroaprendiz",`A partir do 3º nível, você ajuda seu senhor em batalha. Torna-se treinado em Cavalgar e recebe proficiência com armaduras pesadas. Se já tiver essa proficiência, recebe +2 na Defesa enquanto usa armadura pesada.`);
  set("vassalo|guardadocastelo",`No 4º nível, você patrulha as muralhas do castelo sozinho. Torna-se treinado em Intuição e recebe um poder de cavaleiro à sua escolha.`);
  set("vassalo|vigilantedasestradas",`A partir do 5º nível, você expande suas responsabilidades além do castelo. Recebe a habilidade Montaria e torna-se treinado em Percepção.`);
  set("vassalo|cavaleirodoreino",`No 6º nível, você recebe o título de sir ou dame. Recebe uma arma, armadura ou escudo superior com duas melhorias à sua escolha e recebe um poder de cavaleiro à sua escolha.`);
  set("vassalo|sargentodoreino",`No 7º nível, você adquire posição no exército do reino. Recebe um poder de cavaleiro ou guerreiro à sua escolha, como um guerreiro de nível igual ao seu para propósitos de pré-requisitos.`);
  set("vassalo|capitaodoreino",`No 8º nível, você se torna oficial respeitado. Recebe o poder Escudeiro e a habilidade Golpe Divino, como paladino de nível igual ao seu. Esta não é uma habilidade mágica e provém de seu senso de justiça e determinação em combate.`);
  set("vassalo|lorde",`No 9º nível, você recebe um feudo. Recebe Autoridade Feudal; se já possui esse poder, as pessoas convocadas passam a contar como parceiro veterano. Além disso, escolha Caminho do Soldado, recebendo um poder de guerreiro como guerreiro de nível igual ao seu, ou Caminho do Governante, recebendo um poder de nobre como nobre de nível igual ao seu.`);
  set("vassalo|barao",`No 10º nível, você passa a receber impostos de seus plebeus. Recebe o poder Título e um domínio de nível 1. Se já tiver um domínio, em vez disso ele recebe uma construção gratuita cujos pré-requisitos cumpra.`);
  set("vassalo|visconde",`No 11º nível, você adquire título mais alto. Se escolheu Caminho do Soldado, recebe +1 PV por nível de vassalo. Se escolheu Caminho do Governante, recebe +1 em Inteligência.`);
  set("vassalo|conde",`A partir do 12º nível, no início de cada aventura, você recebe um orçamento de T$ 30.000 para gastar em itens mágicos. Esses itens devem ser devolvidos ou reembolsados no fim da aventura. Além disso, recebe um poder de cavaleiro ou geral à sua escolha.`);
  set("vassalo|marques",`No 13º nível, se escolheu Caminho do Soldado, recebe RD 5 e +2 na Defesa. Se escolheu Caminho do Governante, passa a somar seu Carisma em testes de resistência.`);
  set("vassalo|duque",`No 14º nível, quando usa Autoridade Feudal, o nível do parceiro convocado aumenta em um passo. Além disso, recebe um poder de cavaleiro à sua escolha.`);
  set("vassalo|arquiduque",`No 15º nível, uma vez por rodada, quando uma criatura inteligente lhe causar dano, você pode gastar 5 PM para reduzir esse dano a 0.`);
  set("vassalo|conselheiroreal",`A partir do 16º nível, você recebe um poder de cavaleiro à sua escolha e aprende e pode lançar uma magia divina de até 4º círculo à sua escolha, com Carisma como atributo-chave.`);
  set("vassalo|reimercenario",`No 17º nível, se escolheu Caminho do Soldado, recebe 3 pontos de atributo para distribuir como quiser em Força, Destreza e Constituição. Se escolheu Caminho do Governante, recebe 3 pontos de atributo para distribuir como quiser em Inteligência, Sabedoria e Carisma.`);
  set("vassalo|rei",`No 18º nível, você recebe +1 em Carisma e um poder de cavaleiro à sua escolha.`);
  set("vassalo|altorei",`No 19º nível, seu orçamento de itens mágicos aumenta para T$ 100.000 e seu limite de parceiros aumenta em 2.`);
  set("vassalo|imperador",`No 20º nível, você recebe +1 em dois atributos diferentes à sua escolha e aprende e pode lançar uma magia divina de até 5º círculo à sua escolha, com Carisma como atributo-chave.`);

  set("ventanista|charme",`Você soma seu Carisma ao seu total de PM. Quando faz um teste de perícia, exceto ataque, pode gastar uma quantidade de PM à sua escolha, limitada pelo seu Carisma. Para cada PM gasto, recebe +2 no teste.`);
  set("ventanista|truquesdooficio",`Você pode lançar magias arcanas de 1º círculo, mas apenas de encantamento e ilusão. Esta não é uma habilidade mágica e provém da sua capacidade de enganar outras pessoas. À medida que sobe de nível, pode lançar magias de círculos maiores: 2º círculo no 6º nível, 3º no 10º e 4º no 14º. Você começa com duas magias de 1º círculo e, a cada nível par, aprende uma magia de qualquer círculo que possa lançar. Pode lançar essas magias vestindo armaduras leves sem testes de Misticismo. Seu atributo-chave é Inteligência.`);
  set("ventanista|disfarceelaborado",`No 3º nível, sempre que fizer teste de Enganação para disfarce, pode escolher um poder, exceto poderes da Tormenta, cujos pré-requisitos cumpra e que esteja relacionado ao disfarce. Enquanto estiver disfarçado dessa forma, sofre penalidade de -3 PM e pode usar o poder escolhido. A cada seis níveis, pode assumir penalidade adicional de -3 PM ao se disfarçar para escolher um poder adicional.`);
  set("ventanista|viraracasaca",`No 7º nível, se estiver disfarçado, você pode gastar 1 PM para remover seu disfarce. Quando faz isso, pode fazer um teste para se esconder usando Enganação no lugar de Furtividade, mesmo sem camuflagem ou cobertura disponível.`);
  set("ventanista|provocacaoousada",`A partir do 11º nível, em seu primeiro turno em cada cena, pode gastar uma ação completa para provocar seus inimigos. Pode deixar cartão de visitas visível, declarar seu plano ou fazer outra ação que alerte os inimigos. Até o fim da cena, seus inimigos recebem +2 em Percepção, Sobrevivência e Vontade contra você. Entretanto, no início de seus turnos, você recupera 2 PM. Esta habilidade só tem efeito se houver risco associado a declarar suas ações, a critério do mestre, e recupera no máximo PM por cena iguais ao seu nível.`);
  set("ventanista|ograndegolpe",`No 20º nível, no início de cada aventura, escolha uma quantidade de magias arcanas ou divinas igual à sua Inteligência; você pode escolher a mesma magia mais de uma vez. Para cada escolha, defina um tipo de cena entre ação, exploração e interpretação. Até o fim da aventura, para cada vez que uma magia foi escolhida, se estiver em uma cena do tipo definido para ela, pode lançá-la sem gastar PM, com limite de PM 20 e atributo-chave Inteligência. Esta não é uma habilidade mágica e provém da sua capacidade de enganar outras pessoas.`);
})();
