(() => {
  const byClass = {
    arcanista: [
      ["Arcano de Batalha", "Jogo do Ano"],
      ["Aumento de Atributo", "Jogo do Ano"],
      ["Caldeirão do Bruxo", "Jogo do Ano"],
      ["Conhecimento Mágico", "Jogo do Ano"],
      ["Contramágica Aprimorada", "Jogo do Ano"],
      ["Envolto em Mistério", "Jogo do Ano"],
      ["Escriba Arcano", "Jogo do Ano"],
      ["Especialista em Escola", "Jogo do Ano"],
      ["Familiar", "Jogo do Ano"],
      ["Fluxo de Mana", "Jogo do Ano"],
      ["Foco Vital", "Jogo do Ano"],
      ["Fortalecimento Arcano", "Jogo do Ano"],
      ["Herança Aprimorada", "Jogo do Ano"],
      ["Herança Superior", "Jogo do Ano"],
      ["Magia Pungente", "Jogo do Ano"],
      ["Mestre em Escola", "Jogo do Ano"],
      ["Poder Mágico", "Jogo do Ano"],
      ["Raio Arcano", "Jogo do Ano"],
      ["Raio Elemental", "Jogo do Ano"],
      ["Raio Poderoso", "Jogo do Ano"],
      ["Tinta do Mago", "Jogo do Ano"],
      ["Agrilhoar os Caídos", "Heróis de Arton"],
      ["Alquimia Arcana", "Heróis de Arton"],
      ["Apoteose Celestial", "Heróis de Arton"],
      ["Apoteose Dracônica", "Heróis de Arton"],
      ["Apoteose Feérica", "Heróis de Arton"],
      ["Apoteose Rubra", "Heróis de Arton"],
      ["Arcanista de Linha de Frente", "Heróis de Arton"],
      ["Asas de Sapo", "Heróis de Arton"],
      ["Contingência Arcana", "Heróis de Arton"],
      ["Contramágica Superior", "Heróis de Arton"],
      ["Especialista em Invocações", "Heróis de Arton"],
      ["Familiar Aprimorado", "Heróis de Arton"],
      ["Ingrediente Especial", "Heróis de Arton"],
      ["Magia Performática", "Heróis de Arton"],
      ["Memória Súbita", "Heróis de Arton"],
      ["O Próprio Sangue", "Heróis de Arton"],
      ["Raio Dividido", "Heróis de Arton"],
      ["Sifão de Mana", "Heróis de Arton"],
      ["Trama Célere", "Heróis de Arton"],
      ["Transliteração Impossível", "Heróis de Arton"]
    ],
    barbaro: [
      ["Alma de Bronze", "Jogo do Ano"],
      ["Aumento de Atributo", "Jogo do Ano"],
      ["Brado Assustador", "Jogo do Ano"],
      ["Crítico Brutal", "Jogo do Ano"],
      ["Destruidor", "Jogo do Ano"],
      ["Espírito Inquebrável", "Jogo do Ano"],
      ["Esquiva Sobrenatural", "Jogo do Ano"],
      ["Força Indomável", "Jogo do Ano"],
      ["Frenesi", "Jogo do Ano"],
      ["Fúria da Savana", "Jogo do Ano"],
      ["Fúria Raivosa", "Jogo do Ano"],
      ["Golpe Poderoso", "Jogo do Ano"],
      ["Ímpeto", "Jogo do Ano"],
      ["Investida Imprudente", "Jogo do Ano"],
      ["Pele de Aço", "Jogo do Ano"],
      ["Pele de Ferro", "Jogo do Ano"],
      ["Sangue dos Inimigos", "Jogo do Ano"],
      ["Superstição", "Jogo do Ano"],
      ["Totem Espiritual", "Jogo do Ano"],
      ["Vigor Primal", "Jogo do Ano"],
      ["Alma Inabalável", "Heróis de Arton"],
      ["Ampliar Brado", "Heróis de Arton"],
      ["Arremesso Violento", "Heróis de Arton"],
      ["Beberrão Selvagem", "Heróis de Arton"],
      ["Brado: Assombroso", "Heróis de Arton"],
      ["Brado: Retardante", "Heróis de Arton"],
      ["Brado: Sísmico", "Heróis de Arton"],
      ["Brado Vitorioso", "Heróis de Arton"],
      ["Enigma do Aço", "Heróis de Arton"],
      ["Espiritualista", "Heróis de Arton"],
      ["Fúria Bestial", "Heróis de Arton"],
      ["Fúria Elemental", "Heróis de Arton"],
      ["Impiedoso", "Heróis de Arton"],
      ["Invocar os Ancestrais", "Heróis de Arton"],
      ["Manifestar Totem", "Heróis de Arton"],
      ["Recuperação Gutural", "Heróis de Arton"],
      ["Regeneração Sobrenatural", "Heróis de Arton"],
      ["Revide", "Heróis de Arton"],
      ["Rigidez Selvagem", "Heróis de Arton"],
      ["Sede Sanguinária", "Heróis de Arton"]
    ],
    bardo: [
      ["Arte Mágica", "Jogo do Ano"],
      ["Aumentar Repertório", "Jogo do Ano"],
      ["Aumento de Atributo", "Jogo do Ano"],
      ["Dança das Lâminas", "Jogo do Ano"],
      ["Esgrima Mágica", "Jogo do Ano"],
      ["Estrelato", "Jogo do Ano"],
      ["Fascinar em Massa", "Jogo do Ano"],
      ["Melodia Restauradora", "Jogo do Ano"],
      ["Mestre dos Sussurros", "Jogo do Ano"],
      ["Paródia", "Jogo do Ano"],
      ["Prestidigitação", "Jogo do Ano"],
      ["Golpe Elemental", "Jogo do Ano"],
      ["Golpe Mágico", "Jogo do Ano"],
      ["Inspiração Marcial", "Jogo do Ano"],
      ["Lendas e Histórias", "Jogo do Ano"],
      ["Manipular", "Jogo do Ano"],
      ["Manipular em Massa", "Jogo do Ano"],
      ["Música: Balada Fascinante", "Jogo do Ano"],
      ["Música: Canção Assustadora", "Jogo do Ano"],
      ["Música: Melodia Curativa", "Jogo do Ano"],
      ["Acorde Místico", "Heróis de Arton"],
      ["Acorde Poderoso", "Heróis de Arton"],
      ["Adereço Musical", "Heróis de Arton"],
      ["Apresentação Impactante", "Heróis de Arton"],
      ["Balada do Atirador", "Heróis de Arton"],
      ["Celebridade Artoniana", "Heróis de Arton"],
      ["Dança Acrobática", "Heróis de Arton"],
      ["Espada Encantada", "Heróis de Arton"],
      ["História de Acampamento", "Heróis de Arton"],
      ["Inspiração Espirituosa", "Heróis de Arton"],
      ["Inspiração Resoluta", "Heróis de Arton"],
      ["Inspiração Revigorante", "Heróis de Arton"],
      ["Magia Performática", "Heróis de Arton"],
      ["Mago Vermelho", "Heróis de Arton"],
      ["Música: Marcha Vitoriosa", "Heróis de Arton"],
      ["Música: Réquiem Sombrio", "Heróis de Arton"],
      ["Música: Sonata da Distração", "Heróis de Arton"],
      ["Portas da Fama", "Heróis de Arton"],
      ["Ressoar", "Heróis de Arton"],
      ["Triunfo do Amor", "Heróis de Arton"]
    ],
    bucaneiro: [
      ["Apostador", "Jogo do Ano"],
      ["Ataque Acrobático", "Jogo do Ano"],
      ["Aumento de Atributo", "Jogo do Ano"],
      ["Aventureiro Ávido", "Jogo do Ano"],
      ["Abusar dos Fracos", "Jogo do Ano"],
      ["Amigos no Porto", "Jogo do Ano"],
      ["Aparar", "Jogo do Ano"],
      ["Bravata Audaz", "Jogo do Ano"],
      ["Bravata Imprudente", "Jogo do Ano"],
      ["En Garde", "Jogo do Ano"],
      ["Esgrimista", "Jogo do Ano"],
      ["Flagelo dos Mares", "Jogo do Ano"],
      ["Folião", "Jogo do Ano"],
      ["Grudar o Cano", "Jogo do Ano"],
      ["Pernas do Mar", "Jogo do Ano"],
      ["Pistoleiro", "Jogo do Ano"],
      ["Presença Paralisante", "Jogo do Ano"],
      ["Ripostar", "Jogo do Ano"],
      ["Touché", "Jogo do Ano"],
      ["Ardil Afiado", "Heróis de Arton"],
      ["Bloqueio Desconcertante", "Heróis de Arton"],
      ["Bom de Trago", "Heróis de Arton"],
      ["Charme Cafajeste", "Heróis de Arton"],
      ["Cobrir de Pólvora", "Heróis de Arton"],
      ["Cortejo de Espadas", "Heróis de Arton"],
      ["Dançar nas Cordas", "Heróis de Arton"],
      ["Entrada Triunfal", "Heróis de Arton"],
      ["Esgrima Sambur", "Heróis de Arton"],
      ["Estampido Ensurdecedor", "Heróis de Arton"],
      ["Estocada no Flanco", "Heróis de Arton"],
      ["Gole da Coragem", "Heróis de Arton"],
      ["Golpe Humilhante", "Heróis de Arton"],
      ["Onda de Sangue", "Heróis de Arton"],
      ["Passo das Ondas", "Heróis de Arton"],
      ["Pirouette", "Heróis de Arton"],
      ["Remise", "Heróis de Arton"],
      ["Introdução Calorosa", "Heróis de Arton"],
      ["Lobo do Mar", "Heróis de Arton"],
      ["Lorotas da Terra e do Mar", "Heróis de Arton"],
      ["Sucesso Atrai Sucesso", "Heróis de Arton"]
    ],
    cacador: [
      ["Ambidestria", "Jogo do Ano"],
      ["Armadilha: Arataca", "Jogo do Ano"],
      ["Armadilha: Espinhos", "Jogo do Ano"],
      ["Armadilha: Laço", "Jogo do Ano"],
      ["Armadilha: Rede", "Jogo do Ano"],
      ["Armadilheiro", "Jogo do Ano"],
      ["Arqueiro", "Jogo do Ano"],
      ["Aumento de Atributo", "Jogo do Ano"],
      ["Bote", "Jogo do Ano"],
      ["Camuflagem", "Jogo do Ano"],
      ["Chuva de Lâminas", "Jogo do Ano"],
      ["Ponto Fraco", "Jogo do Ano"],
      ["Companheiro Animal", "Jogo do Ano"],
      ["Elo com a Natureza", "Jogo do Ano"],
      ["Emboscar", "Jogo do Ano"],
      ["Empatia Selvagem", "Jogo do Ano"],
      ["Escaramuça", "Jogo do Ano"],
      ["Escaramuça Superior", "Jogo do Ano"],
      ["Espreitar", "Jogo do Ano"],
      ["Ervas Curativas", "Jogo do Ano"],
      ["Ímpeto", "Jogo do Ano"],
      ["Inimigo de (Criatura)", "Jogo do Ano"],
      ["Olho do Falcão", "Jogo do Ano"],
      ["Armadilha Alquímica", "Heróis de Arton"],
      ["Avanço do Predador", "Heróis de Arton"],
      ["Batedor Marcial", "Heróis de Arton"],
      ["Curandeiro dos Ermos", "Heróis de Arton"],
      ["Elo com a Natureza Maior", "Heróis de Arton"],
      ["Explorador Viajado", "Heróis de Arton"],
      ["Flecheiro", "Heróis de Arton"],
      ["Golpe do Predador", "Heróis de Arton"],
      ["Herói do Povo", "Heróis de Arton"],
      ["Identificar Presas", "Heróis de Arton"],
      ["Lâminas Guardiãs", "Heróis de Arton"],
      ["Lanceiro", "Heróis de Arton"],
      ["Pega!", "Heróis de Arton"],
      ["Primeiro Sangue", "Heróis de Arton"],
      ["Sequência Dilaceradora", "Heróis de Arton"],
      ["Sequência do Predador", "Heróis de Arton"],
      ["Sombra dos Ermos", "Heróis de Arton"],
      ["Tiro de Abate", "Heróis de Arton"],
      ["Tiro Trespassante", "Heróis de Arton"],
      ["Tempestade de Lâminas", "Heróis de Arton"],
      ["Tocaia Habilidosa", "Heróis de Arton"],
      ["Último Sangue", "Heróis de Arton"]
    ],
    cavaleiro: [
      ["Aumento de Atributo", "Jogo do Ano"],
      ["Autoridade Feudal", "Jogo do Ano"],
      ["Desprezar os Covardes", "Jogo do Ano"],
      ["Escudeiro", "Jogo do Ano"],
      ["Especialização em Armadura", "Jogo do Ano"],
      ["Estandarte", "Jogo do Ano"],
      ["Etiqueta", "Jogo do Ano"],
      ["Investida Destruidora", "Jogo do Ano"],
      ["Montaria Corajosa", "Jogo do Ano"],
      ["Pajem", "Jogo do Ano"],
      ["Postura de Combate: Aríete Implacável", "Jogo do Ano"],
      ["Postura de Combate: Castigo de Ferro", "Jogo do Ano"],
      ["Postura de Combate: Foco de Batalha", "Jogo do Ano"],
      ["Postura de Combate: Muralha Intransponível", "Jogo do Ano"],
      ["Postura de Combate: Provocação Petulante", "Jogo do Ano"],
      ["Postura de Combate: Torre Inabalável", "Jogo do Ano"],
      ["Solidez", "Jogo do Ano"],
      ["Título", "Jogo do Ano"],
      ["Torre Armada", "Jogo do Ano"],
      ["Armas da Cavalaria", "Heróis de Arton"],
      ["Cavaleiro das Paixões", "Heróis de Arton"],
      ["Cavaleiro Bandido", "Heróis de Arton"],
      ["Cavaleiro Sagrado", "Heróis de Arton"],
      ["Duelista Escudado", "Heróis de Arton"],
      ["Duelo Irrecusável", "Heróis de Arton"],
      ["Grão-Mestre", "Heróis de Arton"],
      ["Honra Compartilhada", "Heróis de Arton"],
      ["Inércia do Aço", "Heróis de Arton"],
      ["Investida Convicta", "Heróis de Arton"],
      ["Investida Defensiva", "Heróis de Arton"],
      ["Mestre das Posturas", "Heróis de Arton"],
      ["Paixão: Amor", "Heróis de Arton"],
      ["Paixão: Honra", "Heróis de Arton"],
      ["Paixão: Hospitalidade", "Heróis de Arton"],
      ["Paixão: Lealdade", "Heróis de Arton"],
      ["Postura de Combate: Armamento Pesado", "Heróis de Arton"],
      ["Postura de Combate: Quebra-Magia", "Heróis de Arton"],
      ["Postura de Combate: Sequência Blindada", "Heróis de Arton"],
      ["Presença de Muralha", "Heróis de Arton"]
    ],
    clerigo: [
      ["Canalizar Amplo", "Jogo do Ano"],
      ["Comunhão Vital", "Jogo do Ano"],
      ["Conhecimento Mágico", "Jogo do Ano"],
      ["Expulsar/Comandar Mortos-Vivos", "Jogo do Ano"],
      ["Liturgia Mágica", "Jogo do Ano"],
      ["Magia Sagrada/Profana", "Jogo do Ano"],
      ["Mestre Celebrante", "Jogo do Ano"],
      ["Missa: Bênção da Vida", "Jogo do Ano"],
      ["Missa: Chamado às Armas", "Jogo do Ano"],
      ["Missa: Elevação do Espírito", "Jogo do Ano"],
      ["Missa: Escudo Divino", "Jogo do Ano"],
      ["Missa: Superar as Limitações", "Jogo do Ano"],
      ["Prece de Combate", "Jogo do Ano"],
      ["Símbolo Sagrado Energizado", "Jogo do Ano"],
      ["Acólito Escudeiro", "Heróis de Arton"],
      ["Arma Divina", "Heróis de Arton"],
      ["Bênção de Batalha", "Heróis de Arton"],
      ["Canalizar Abençoado", "Heróis de Arton"],
      ["Canalizar Concentrado", "Heróis de Arton"],
      ["Canalizar Profanado", "Heróis de Arton"],
      ["Canalizar Poderoso", "Heróis de Arton"],
      ["Conversão de Fé", "Heróis de Arton"],
      ["Dizimar Infiéis", "Heróis de Arton"],
      ["Égide da Fé", "Heróis de Arton"],
      ["Força da Devoção", "Heróis de Arton"],
      ["Liturgia Marcial", "Heróis de Arton"],
      ["Missa: Compartilhar Milagre", "Heróis de Arton"],
      ["Missa: Imposição da Vontade", "Heróis de Arton"],
      ["Missa: Mente Abençoada", "Heróis de Arton"],
      ["Presente dos Deuses", "Heróis de Arton"],
      ["Punição Divina", "Heróis de Arton"],
      ["Representante Divino", "Heróis de Arton"],
      ["Solo Profanado", "Heróis de Arton"],
      ["Solo Sagrado", "Heróis de Arton"]
    ],
    druida: [
      ["Aspecto do Inverno", "Jogo do Ano"],
      ["Aspecto do Outono", "Jogo do Ano"],
      ["Aspecto da Primavera", "Jogo do Ano"],
      ["Aspecto do Verão", "Jogo do Ano"],
      ["Aumento de Atributo", "Jogo do Ano"],
      ["Companheiro Animal", "Jogo do Ano"],
      ["Companheiro Animal Aprimorado", "Jogo do Ano"],
      ["Companheiro Animal Lendário", "Jogo do Ano"],
      ["Companheiro Animal Mágico", "Jogo do Ano"],
      ["Coração da Selva", "Jogo do Ano"],
      ["Espírito dos Equinócios", "Jogo do Ano"],
      ["Espírito dos Solstícios", "Jogo do Ano"],
      ["Força dos Penhascos", "Jogo do Ano"],
      ["Forma Primal", "Jogo do Ano"],
      ["Forma Selvagem", "Jogo do Ano"],
      ["Forma Selvagem Aprimorada", "Jogo do Ano"],
      ["Forma Selvagem Superior", "Jogo do Ano"],
      ["Liberdade da Pradaria", "Jogo do Ano"],
      ["Magia Natural", "Jogo do Ano"],
      ["Presas Afiadas", "Jogo do Ano"],
      ["Segredos da Natureza", "Jogo do Ano"],
      ["Tranquilidade dos Lagos", "Jogo do Ano"],
      ["Arma Tradicional", "Heróis de Arton"],
      ["Auspício do Crepúsculo", "Heróis de Arton"],
      ["Auspício da Madrugada", "Heróis de Arton"],
      ["Auspício da Meia-Noite", "Heróis de Arton"],
      ["Banquete Selvagem", "Heróis de Arton"],
      ["Ciclo da Vida", "Heróis de Arton"],
      ["Companheiro Aberrante", "Heróis de Arton"],
      ["Companheiro Elemental", "Heróis de Arton"],
      ["Erupção Elemental", "Heróis de Arton"],
      ["Força da Natureza", "Heróis de Arton"],
      ["Forma Aberrante", "Heróis de Arton"],
      ["Forma de Cardume", "Heróis de Arton"],
      ["Forma Elemental", "Heróis de Arton"],
      ["Forma Esquelética", "Heróis de Arton"],
      ["Forma Vegetal", "Heróis de Arton"],
      ["Instinto Venenoso", "Heróis de Arton"],
      ["Metamorfose Instantânea", "Heróis de Arton"],
      ["Oráculo da Natureza", "Heróis de Arton"],
      ["Orador dos Elementos", "Heróis de Arton"],
      ["Proteção Fúngica", "Heróis de Arton"],
      ["Transformação Repugnante", "Heróis de Arton"],
      ["Xamã Místico", "Heróis de Arton"]
    ],
    guerreiro: [
      ["Ambidestria", "Jogo do Ano"],
      ["Arqueiro", "Jogo do Ano"],
      ["Ataque Reflexo", "Jogo do Ano"],
      ["Aumento de Atributo", "Jogo do Ano"],
      ["Bater e Correr", "Jogo do Ano"],
      ["Destruidor", "Jogo do Ano"],
      ["Esgrimista", "Jogo do Ano"],
      ["Especialização em Arma", "Jogo do Ano"],
      ["Especialização em Armadura", "Jogo do Ano"],
      ["Golpe de Raspão", "Jogo do Ano"],
      ["Golpe Demolidor", "Jogo do Ano"],
      ["Golpe Pessoal", "Jogo do Ano"],
      ["Ímpeto", "Jogo do Ano"],
      ["Mestre em Arma", "Jogo do Ano"],
      ["Planejamento Marcial", "Jogo do Ano"],
      ["Romper Resistências", "Jogo do Ano"],
      ["Solidez", "Jogo do Ano"],
      ["Tornado de Dor", "Jogo do Ano"],
      ["Valentão", "Jogo do Ano"],
      ["Análise Tática", "Heróis de Arton"],
      ["Arremesso de Investida", "Heróis de Arton"],
      ["Bloqueio Brutal", "Heróis de Arton"],
      ["Corte Ágil", "Heróis de Arton"],
      ["Criar Oportunidade", "Heróis de Arton"],
      ["Defesa Estratégica", "Heróis de Arton"],
      ["Determinação Inabalável", "Heróis de Arton"],
      ["Estrategista Inspirador", "Heróis de Arton"],
      ["Executor", "Heróis de Arton"],
      ["Fender Defesas", "Heróis de Arton"],
      ["Inércia do Aço", "Heróis de Arton"],
      ["Investida Ricochete", "Heróis de Arton"],
      ["Manobra Dupla", "Heróis de Arton"],
      ["Mente Disciplinada", "Heróis de Arton"],
      ["Operações Combinadas", "Heróis de Arton"],
      ["Ordens de Engajamento", "Heróis de Arton"],
      ["Recuperar Fôlego", "Heróis de Arton"],
      ["Resiliência Marcial", "Heróis de Arton"],
      ["Soldado de Infantaria", "Heróis de Arton"],
      ["Velho de Guerra", "Heróis de Arton"],
      ["Xadrez de Batalha", "Heróis de Arton"]
    ],
    inventor: [
      ["Autômato", "Jogo do Ano"],
      ["Autômato Prototipado", "Jogo do Ano"],
      ["Balística", "Jogo do Ano"],
      ["Blindagem", "Jogo do Ano"],
      ["Cano Raiado", "Jogo do Ano"],
      ["Catalisador Instável", "Jogo do Ano"],
      ["Chutes e Palavrões", "Jogo do Ano"],
      ["Conhecimento de Fórmulas", "Jogo do Ano"],
      ["Couraceiro", "Jogo do Ano"],
      ["Engenhoqueiro", "Jogo do Ano"],
      ["Farmacêutico", "Jogo do Ano"],
      ["Ferreiro", "Jogo do Ano"],
      ["Granadeiro", "Jogo do Ano"],
      ["Homúnculo", "Jogo do Ano"],
      ["Invenção Potente", "Jogo do Ano"],
      ["Maestria em Perícia", "Jogo do Ano"],
      ["Manutenção Eficiente", "Jogo do Ano"],
      ["Mestre Alquimista", "Jogo do Ano"],
      ["Mestre Cuca", "Jogo do Ano"],
      ["Mistura Fervilhante", "Jogo do Ano"],
      ["Oficina de Campo", "Jogo do Ano"],
      ["Pedra de Amolar", "Jogo do Ano"],
      ["Síntese Rápida", "Jogo do Ano"],
      ["Alquimista Exímio", "Heróis de Arton"],
      ["Alterar Programação", "Heróis de Arton"],
      ["Aparato Personalizado", "Heróis de Arton"],
      ["Armadura Avançada", "Heróis de Arton"],
      ["Armadura Mecanizada", "Heróis de Arton"],
      ["Artesão Criativo", "Heróis de Arton"],
      ["Autômato Alquímico", "Heróis de Arton"],
      ["Autômato Engenhocado", "Heróis de Arton"],
      ["Catalisador Experimental", "Heróis de Arton"],
      ["Estilista", "Heróis de Arton"],
      ["Explicação Científica", "Heróis de Arton"],
      ["Explorar Fraqueza", "Heróis de Arton"],
      ["Farmácia Mágica", "Heróis de Arton"],
      ["Forçar a Calibragem", "Heróis de Arton"],
      ["Galvanização", "Heróis de Arton"],
      ["Gênio Inovador", "Heróis de Arton"],
      ["Golpe de Gênio", "Heróis de Arton"],
      ["Infusão Distante", "Heróis de Arton"],
      ["Oficina Esotérica", "Heróis de Arton"],
      ["Saraivada Alquímica", "Heróis de Arton"]
    ],
    ladino: [
      ["Assassinar", "Jogo do Ano"],
      ["Aumento de Atributo", "Jogo do Ano"],
      ["Contatos no Submundo", "Jogo do Ano"],
      ["Emboscar", "Jogo do Ano"],
      ["Escapista", "Jogo do Ano"],
      ["Fuga Formidável", "Jogo do Ano"],
      ["Gatuno", "Jogo do Ano"],
      ["Ladrão Arcano", "Jogo do Ano"],
      ["Mão na Boca", "Jogo do Ano"],
      ["Mãos Rápidas", "Jogo do Ano"],
      ["Mente Criminosa", "Jogo do Ano"],
      ["Oportunismo", "Jogo do Ano"],
      ["Rolamento Defensivo", "Jogo do Ano"],
      ["Roubo de Mana", "Jogo do Ano"],
      ["Saqueador de Tumbas", "Jogo do Ano"],
      ["Sombra", "Jogo do Ano"],
      ["Truque Mágico", "Jogo do Ano"],
      ["Velocidade Ladina", "Jogo do Ano"],
      ["Veneno Persistente", "Jogo do Ano"],
      ["Veneno Potente", "Jogo do Ano"],
      ["Ameaça Brutal", "Heróis de Arton"],
      ["Assassino em Série", "Heróis de Arton"],
      ["Ataque Furtivo Letal", "Heróis de Arton"],
      ["Bombardeiro Furtivo", "Heróis de Arton"],
      ["Chefe de Gangue", "Heróis de Arton"],
      ["Conhecimento Anatômico", "Heróis de Arton"],
      ["Enganar os Olhos", "Heróis de Arton"],
      ["Finta Acrobática", "Heróis de Arton"],
      ["Improvisação Arcana", "Heróis de Arton"],
      ["Investida Rasteira", "Heróis de Arton"],
      ["Mestre Assassino", "Heróis de Arton"],
      ["Mestre Envenenador", "Heróis de Arton"],
      ["Papo Furado", "Heróis de Arton"],
      ["Precisão Furtiva", "Heróis de Arton"],
      ["Rei do Crime", "Heróis de Arton"],
      ["Sabotagem Corrosiva", "Heróis de Arton"],
      ["Senhor do Submundo", "Heróis de Arton"],
      ["Truque de Palco", "Heróis de Arton"],
      ["Truque do Chapéu", "Heróis de Arton"],
      ["Vestido Para a Ocasião", "Heróis de Arton"]
    ],
    lutador: [
      ["Arma Improvisada", "Jogo do Ano"],
      ["Até Acertar", "Jogo do Ano"],
      ["Aumento de Atributo", "Jogo do Ano"],
      ["Braços Calejados", "Jogo do Ano"],
      ["Cabeçada", "Jogo do Ano"],
      ["Chave", "Jogo do Ano"],
      ["Confiança dos Ringues", "Jogo do Ano"],
      ["Convencido", "Jogo do Ano"],
      ["Golpe Baixo", "Jogo do Ano"],
      ["Trincado", "Jogo do Ano"],
      ["Trocação", "Jogo do Ano"],
      ["Trocação Tumultuosa", "Jogo do Ano"],
      ["Valentão", "Jogo do Ano"],
      ["Voadora", "Jogo do Ano"],
      ["Golpe Imprudente", "Jogo do Ano"],
      ["Imobilização", "Jogo do Ano"],
      ["Língua dos Becos", "Jogo do Ano"],
      ["Lutador de Chão", "Jogo do Ano"],
      ["Nome na Arena", "Jogo do Ano"],
      ["Punhos de Adamante", "Jogo do Ano"],
      ["Rasteira", "Jogo do Ano"],
      ["Sarado", "Jogo do Ano"],
      ["Sequência Destruidora", "Jogo do Ano"],
      ["Aquecimento", "Heróis de Arton"],
      ["Caminhar pelas Paredes", "Heróis de Arton"],
      ["Caminho Suave", "Heróis de Arton"],
      ["Combinação: Boca do Estômago", "Heróis de Arton"],
      ["Combinação: Chute Circular", "Heróis de Arton"],
      ["Combinação: Chute no Joelho", "Heróis de Arton"],
      ["Combinação: Esquiva Técnica", "Heróis de Arton"],
      ["Combinação: Quebra-guarda", "Heróis de Arton"],
      ["Combinação: Um-Dois", "Heróis de Arton"],
      ["Combinação: Técnica de Sacrifício", "Heróis de Arton"],
      ["Corpo Fechado", "Heróis de Arton"],
      ["Dança Marcial", "Heróis de Arton"],
      ["Gingado Elusivo", "Heróis de Arton"],
      ["Invencível", "Heróis de Arton"],
      ["Jogo de Pernas", "Heróis de Arton"],
      ["Mestre das Combinações", "Heróis de Arton"],
      ["Rilhar os Dentes", "Heróis de Arton"],
      ["Rolamento Escapatório", "Heróis de Arton"],
      ["Ruas Furiosas", "Heróis de Arton"],
      ["Sequência Defensiva", "Heróis de Arton"]
    ],
    nobre: [
      ["Armadura Brilhante", "Jogo do Ano"],
      ["Aumento de Atributo", "Jogo do Ano"],
      ["Autoridade Feudal", "Jogo do Ano"],
      ["Educação Privilegiada", "Jogo do Ano"],
      ["Estrategista", "Jogo do Ano"],
      ["Favor", "Jogo do Ano"],
      ["General", "Jogo do Ano"],
      ["Grito Tirânico", "Jogo do Ano"],
      ["Inspirar Confiança", "Jogo do Ano"],
      ["Inspirar Glória", "Jogo do Ano"],
      ["Jogo da Corte", "Jogo do Ano"],
      ["Liderar pelo Exemplo", "Jogo do Ano"],
      ["Língua de Ouro", "Jogo do Ano"],
      ["Língua de Prata", "Jogo do Ano"],
      ["Língua Rápida", "Jogo do Ano"],
      ["Presença Majestosa", "Jogo do Ano"],
      ["Título", "Jogo do Ano"],
      ["Voz Poderosa", "Jogo do Ano"],
      ["Agente de Elite", "Heróis de Arton"],
      ["Comandante de Campo", "Heróis de Arton"],
      ["Comitiva", "Heróis de Arton"],
      ["Discurso de Batalha", "Heróis de Arton"],
      ["Fofocas da Corte", "Heróis de Arton"],
      ["Guarda Pessoal", "Heróis de Arton"],
      ["Hedonismo Aristocrático", "Heróis de Arton"],
      ["Instigar Violência", "Heróis de Arton"],
      ["Insuflar Investida", "Heróis de Arton"],
      ["Legado Mágico", "Heróis de Arton"],
      ["Líder Enérgico", "Heróis de Arton"],
      ["Líder Impiedoso", "Heróis de Arton"],
      ["Linhagem Distinta", "Heróis de Arton"],
      ["Ordens Agressivas", "Heróis de Arton"],
      ["Ordens Encorajadoras", "Heróis de Arton"],
      ["Palavras de Efeito", "Heróis de Arton"],
      ["Palavras Ressonantes", "Heróis de Arton"],
      ["Protocolo Impecável", "Heróis de Arton"],
      ["Senescal", "Heróis de Arton"],
      ["Voz Límpida", "Heróis de Arton"]
    ],
    paladino: [
      ["Arma Sagrada", "Jogo do Ano"],
      ["Aumento de Atributo", "Jogo do Ano"],
      ["Aura Antimagia", "Jogo do Ano"],
      ["Julgamento Divino: Salvação", "Jogo do Ano"],
      ["Julgamento Divino: Vindicação", "Jogo do Ano"],
      ["Julgamento Divino: Zelo", "Jogo do Ano"],
      ["Orar", "Jogo do Ano"],
      ["Virtude Paladinesca: Caridade", "Jogo do Ano"],
      ["Virtude Paladinesca: Castidade", "Jogo do Ano"],
      ["Virtude Paladinesca: Compaixão", "Jogo do Ano"],
      ["Virtude Paladinesca: Humildade", "Jogo do Ano"],
      ["Aura Ardente", "Jogo do Ano"],
      ["Aura de Cura", "Jogo do Ano"],
      ["Aura de Invencibilidade", "Jogo do Ano"],
      ["Aura Poderosa", "Jogo do Ano"],
      ["Fulgor Divino", "Jogo do Ano"],
      ["Julgamento Divino: Arrependimento", "Jogo do Ano"],
      ["Julgamento Divino: Autoridade", "Jogo do Ano"],
      ["Julgamento Divino: Coragem", "Jogo do Ano"],
      ["Julgamento Divino: Iluminação", "Jogo do Ano"],
      ["Julgamento Divino: Justiça", "Jogo do Ano"],
      ["Julgamento Divino: Libertação", "Jogo do Ano"],
      ["Virtude Paladinesca: Temperança", "Jogo do Ano"],
      ["Arma Juramentada", "Heróis de Arton"],
      ["Arma Sacramentada", "Heróis de Arton"],
      ["Aura Vingadora", "Heróis de Arton"],
      ["Bloqueio Divino", "Heróis de Arton"],
      ["Convicção Heroica", "Heróis de Arton"],
      ["Expurgo Sagrado", "Heróis de Arton"],
      ["Escudo Fraterno", "Heróis de Arton"],
      ["Escudo Sagrado", "Heróis de Arton"],
      ["Fulgor Ardente", "Heróis de Arton"],
      ["Hoste Celestial", "Heróis de Arton"],
      ["Investida Sagrada", "Heróis de Arton"],
      ["Julgamento Divino: Desafio", "Heróis de Arton"],
      ["Julgamento Divino: Proteção", "Heróis de Arton"],
      ["Julgamento Divino: Redenção", "Heróis de Arton"],
      ["Julgamento Divino: Retribuição", "Heróis de Arton"],
      ["Luz Purificadora", "Heróis de Arton"],
      ["Manto de Batalha", "Heróis de Arton"],
      ["Paladino do Reino", "Heróis de Arton"],
      ["Rajada Divina", "Heróis de Arton"],
      ["Sacrifício", "Heróis de Arton"],
      ["Sentença Dobrada", "Heróis de Arton"],
      ["Virtude Paladinesca: Paciência", "Heróis de Arton"]
    ],
    treinador: [
      ["Amigo Divino", "Heróis de Arton"],
      ["Asas Aliadas", "Heróis de Arton"],
      ["Aumento de Atributo", "Heróis de Arton"],
      ["Bom Garoto", "Heróis de Arton"],
      ["Comando Defensivo", "Heróis de Arton"],
      ["Comandos Distantes", "Heróis de Arton"],
      ["Convocar Enxame", "Heróis de Arton"],
      ["Coração Grande", "Heróis de Arton"],
      ["Direcionamento Marcial", "Heróis de Arton"],
      ["Domador Cativante", "Heróis de Arton"],
      ["Domador Lendário", "Heróis de Arton"],
      ["Ensinar Truque", "Heróis de Arton"],
      ["Investida Conjunta", "Heróis de Arton"],
      ["Líder da Matilha", "Heróis de Arton"],
      ["Língua das Criaturas", "Heróis de Arton"],
      ["Mascote", "Heróis de Arton"],
      ["Petisco Merecido", "Heróis de Arton"],
      ["Proteção Fraterna", "Heróis de Arton"],
      ["Trabalho em Equipe", "Heróis de Arton"],
      ["Treinador Eclético", "Heróis de Arton"],
      ["Veterinário de Campo", "Heróis de Arton"]
    ],
    frade: [
      ["Acelerar Sacrário", "Deuses de Arton"],
      ["Ampliar Sacrário", "Deuses de Arton"],
      ["Aumento de Atributo", "Deuses de Arton"],
      ["Autoridade Eclesiástica", "Deuses de Arton"],
      ["Bênção Fortalecedora", "Deuses de Arton"],
      ["Canto Monástico", "Deuses de Arton"],
      ["Comunhão Vital", "Deuses de Arton"],
      ["Copista", "Deuses de Arton"],
      ["Conhecimento Mágico", "Deuses de Arton"],
      ["Cozinheiro da Abadia", "Deuses de Arton"],
      ["Estudante Diligente", "Deuses de Arton"],
      ["Fé e Razão", "Deuses de Arton"],
      ["Mago Branco", "Deuses de Arton"],
      ["Memorizar Liturgia", "Deuses de Arton"],
      ["Ofício do Mosteiro", "Deuses de Arton"],
      ["Psicografia", "Deuses de Arton"],
      ["Sacrário da Erudição", "Deuses de Arton"],
      ["Sacrário da Misericórdia", "Deuses de Arton"],
      ["Sacrário da Resiliência", "Deuses de Arton"],
      ["Sacrário da Solenidade", "Deuses de Arton"],
      ["Sacrário da Verdade", "Deuses de Arton"],
      ["Sacrário das Sombras", "Deuses de Arton"],
      ["Sacrário do Compartilhamento", "Deuses de Arton"],
      ["Sacrário do Ocaso", "Deuses de Arton"],
      ["Sermão da Celeridade", "Deuses de Arton"],
      ["Sermão da Égide", "Deuses de Arton"],
      ["Teologia Aplicada", "Deuses de Arton"],
      ["Transferir Sacrário", "Deuses de Arton"],
      ["Zelador dos Vinhedos", "Deuses de Arton"]
    ]
  };

  window.T20_CLASS_POWERS = Object.fromEntries(
    Object.entries(byClass).map(([classId, powers]) => [
      classId,
      powers.map(([name, source]) => ({ name, type: "Classe", source }))
    ])
  );
})();
