;(function(){
  const HEROIS="Heróis de Arton";
  const DEUSES="Deuses de Arton";
  const AMEACAS="Ameaças de Arton";

  const mundane=[];
  const magic=[];

  const item=(source,name,category,price,spaces,notes="")=>({source,name,category,price,spaces,notes});
  const magicItem=(source,name,category,price,spaces,notes="")=>magic.push(item(source,name,category,price,spaces,notes));
  const add=(source,name,category,price,spaces,notes="")=>mundane.push(item(source,name,category,price,spaces,notes));
  const spellCostByCircle={1:1,2:3,3:6,4:10,5:15};
  const spellConsumable=(source,name,circle,type)=>{
    const cost=spellCostByCircle[circle]||1;
    const price=`T$ ${(30*cost*cost).toLocaleString("pt-BR")}`;
    magicItem(source,`Consumível: ${name}`,"Consumíveis",price,0.5,`${type} ${circle}º círculo. Modelo para poção, óleo, granada ou pergaminho; ajuste forma e aprimoramentos conforme a fabricação.`);
  };
  const weapon=(source,name,category,price,spaces,damage,critical,range,type,extra="")=>{
    const details=[`Dano ${damage}`,`crítico ${critical}`];
    if(range) details.push(`alcance ${range}`);
    if(type) details.push(`tipo ${type}`);
    if(extra) details.push(extra);
    add(source,name,category,price,spaces,details.join("; ")+".");
  };
  const armor=(source,name,category,price,spaces,defense,penalty,extra="")=>{
    const details=[`Defesa ${defense}`,`penalidade de armadura ${penalty}`];
    if(extra) details.push(extra);
    add(source,name,category,price,spaces,details.join("; ")+".");
  };

  [
    ["Bastão lúdico","Armas simples","T$ 5",1,"1d6","x2","","impacto","Causa dano não letal; usuários marciais podem rebater armas de arremesso."],
    ["Besta de mão","Armas simples","T$ 30",1,"1d6","19","curto","perfuração","Arma surpreendente; recarregar é ação de movimento."],
    ["Adaga oposta","Armas marciais","T$ 12",1,"1d4","19","","perfuração","+2 em testes de ataque para evitar ou reduzir dano, como Aparar."],
    ["Agulha de Ahlen","Armas marciais","T$ 10",1,"1d4","19","","perfuração","Armazena uma dose de veneno de contato; CD do veneno aumenta em +2."],
    ["Cinquedea","Armas marciais","T$ 18",1,"1d4","19","","perfuração","Causa um dado de dano extra contra alvo desprevenido ou flanqueado."],
    ["Dirk","Armas marciais","T$ 15",1,"1d4","19","","perfuração","Pode atacar certos alvos vulneráveis sem violar Código de Honra."],
    ["Martelo leve","Armas marciais","T$ 2",1,"1d4","x4","curto","impacto","Pode ser arremessado."],
    ["Espada larga","Armas marciais","T$ 8",1,"2d4","x2","","corte"],
    ["Espadim","Armas marciais","T$ 300",1,"1d8","20","","corte","Arma cerimonial de status marcial."],
    ["Maça-estrela","Armas marciais","T$ 20",1,"2d4","x2","","impacto e perfuração"],
    ["Serrilheira","Armas marciais","T$ 25",1,"1d6","19","","corte","Se superar a Defesa por 5 ou mais, deixa o alvo vulnerável e sangrando por 1 rodada."],
    ["Bico de corvo","Armas marciais","T$ 15",2,"1d8","x3","","impacto/perfuração","+2 em testes para derrubar e quebrar."],
    ["Desmontador","Armas marciais","T$ 20",2,"—","—","","—","Arma alongada; +2 em testes para agarrar, derrubar e empurrar."],
    ["Espada de execução","Armas marciais","T$ 75",2,"2d6","18/x4","","corte","Impõe -5 em ataques se não for preparada com ação de movimento."],
    ["Lança de justa","Armas marciais","T$ 3",2,"1d8","x2","","perfuração","Causa dano não letal; em investida montada pode derrubar e pode se quebrar."],
    ["Malho","Armas marciais","T$ 8",2,"1d10","x2","","impacto","+2 em testes para derrubar ou empurrar."],
    ["Martelo longo","Armas marciais","T$ 12",2,"2d4","x4","","impacto/perfuração","Arma alongada."],
    ["Tan-korak","Armas marciais","T$ 40",2,"1d8","x2","","impacto","+2 para derrubar ou desarmar; pode causar dano letal ou não letal."],
    ["Tai-tai","Armas marciais","T$ 60",2,"2d4","x2","médio","impacto","Catapulta de antebraço; Arremessador aumenta seu dano em um passo."],
    ["Arco montado","Armas marciais","T$ 45",2,"1d6","x3","médio","perfuração","Não sofre penalidade por atacar à distância montado."],
    ["Besta dupla","Armas marciais","T$ 125",2,"1d8","19","médio","perfuração","Permite usar Disparo Rápido; se já possuir, remove a penalidade do poder."],
    ["Kimbata","Armas exóticas","T$ 12",1,"1d4","18","","corte","Ocultável e surpreendente; contra desprevenido, pode usar Furtividade no ataque."],
    ["Clava-grão","Armas exóticas","T$ 90",1,"1d6","x2","","impacto","Pode aplicar Sabedoria no dano; druidas podem usá-la como arma simples."],
    ["Espada canora","Armas exóticas","T$ 50",1,"1d6","19","","perfuração","Conta como instrumento musical para bardos e é ágil."],
    ["Espada-gadanho","Armas exóticas","T$ 40",1,"1d6","18","","corte","Ágil e surpreendente."],
    ["Khopesh","Armas exóticas","T$ 20",1,"1d8","19/x3","","corte","+2 em testes para derrubar."],
    ["Lança de falange","Armas exóticas","T$ 15",1,"1d8","x3","curto","perfuração","Alongada e arremessável; pode ser arma marcial de duas mãos."],
    ["Machado de haste","Armas exóticas","T$ 40",1,"1d8/1d10","x3","","corte","Adaptável e alongada; pode ser arma marcial de duas mãos."],
    ["Rapieira","Armas exóticas","T$ 50",1,"1d8","18","","perfuração","Arma ágil."],
    ["Marrão","Armas exóticas","T$ 50",2,"4d4","x2","","impacto","Arma desbalanceada."],
    ["Montante cinético","Armas exóticas","T$ 3.000",2,"2d6","19/x4","","corte","Pode ser usado como marcial, mas resultados 1 ou 2 no ataque atingem o usuário."],
    ["Boleadeira","Armas exóticas","T$ 12",1,"1d4","x2","curto","impacto","Pode executar a manobra derrubar à distância."],
    ["Chakram","Armas exóticas","T$ 15",1,"1d6","x3","curto","corte","Pode retornar à mão ou ricochetear em novos alvos com penalidade cumulativa."],
    ["Arco de guerra","Armas exóticas","T$ 200",2,"1d12","x3","médio","perfuração","Aplica Força no dano, não pode ser usado montado e é desbalanceado."],
    ["Balestra","Armas exóticas","T$ 180",2,"1d12","19","médio","perfuração","Aplica Força no dano; recarregar é ação padrão."],
    ["Besta de repetição","Armas exóticas","T$ 250",2,"1d8","19","médio","perfuração","Armazena 10 virotes; com proficiência recarrega livre e pode disparar saraivada."],
    ["Garrucha","Armas de fogo","T$ 250",1,"2d4","19/x3","curto","perfuração","Ocultável e surpreendente; recarregar é ação padrão."],
    ["Canhão portátil","Armas de fogo","T$ 3.000",2,"4d10","19/x3","curto","impacto","Desbalanceado; recarregar é ação completa e usa bola de ferro."],
    ["Sifão cáustico","Armas de fogo","T$ 600",2,"4d6","x2","especial","ácido","Dispersa ácido em cone de 6m e ocupa também espaço de item vestido."]
  ].forEach(w=>weapon(HEROIS,...w));

  [
    ["Bola de ferro (1)","Munição","T$ 5",0.5,"Munição para canhão portátil."],
    ["Flechas assobiadoras (20)","Munição","T$ 20",1,"Permitem comunicação rudimentar e podem ser usadas para finta à distância."],
    ["Flechas de caça (20)","Munição","T$ 10",1,"Causam dano de impacto não letal."],
    ["Flechas pesadas (20)","Munição","T$ 10",1,"-2 no ataque, mas ignoram 5 pontos de RD."],
    ["Virotes pesados (20)","Munição","T$ 20",1,"-2 no ataque, mas ignoram 5 pontos de RD."]
  ].forEach(i=>add(HEROIS,...i));

  [
    ["Armadura sensual","Armadura leve","T$ 55",2,"+1","0","Permite usar Atraente; se já tiver o poder, aumenta seu bônus."],
    ["Armadura de folhas","Armadura leve","T$ 75",2,"+2","0","Se treinado em Sobrevivência, fornece +2 PM após 1 dia de uso."],
    ["Armadura de engenhoqueiro goblin","Armadura leve","T$ 85",2,"+3","-2 a -10","Carrega itens na armadura; penalidade pode aumentar conforme espaços extras."],
    ["Cota de moedas","Armadura leve","T$ 350",2,"+4","-3","+2 em Diplomacia, a critério do mestre podendo virar penalidade."],
    ["Colete fora da lei","Armadura leve","T$ 750",2,"+5","-5","+2 na Defesa contra armas de disparo."],
    ["Brigantina","Armadura pesada","T$ 75",5,"+6","0","Contra perfuração, seu bônus na Defesa diminui em -2."],
    ["Armadura de chumbo","Armadura pesada","T$ 750",5,"+7","-5","RD 2/mundano e resistência a magia +2."],
    ["Armadura de justa","Armadura pesada","T$ 1.200",5,"+9","-5","+5 para resistir a derrubar montado; +2 na Defesa contra perfuração."],
    ["Armadura de hussardo alado","Armadura pesada","T$ 4.500",5,"+10","-6","Em investida montada, pode assustar o alvo com Intimidação."],
    ["Armadura de pedra","Armadura pesada","T$ 5.500",5,"+12","-5","RD 2; reduz deslocamento à metade e não recebe material especial."],
    ["Broquel","Escudo","T$ 25",0.5,"—","-1","Não soma Defesa; pode reduzir dano com teste de ataque uma vez por rodada."],
    ["Escudo de vime","Escudo","T$ 15",2,"+2","-2","Fornece camuflagem leve e pode proteger aliado adjacente."],
    ["Escudo torre","Escudo","T$ 45",2,"+2","-4","Pode ser fixado no chão como cobertura leve."],
    ["Sagna","Escudo","T$ 20",2,"+2","-3","Pode ser usado para surfar/nadar; funciona como escudo pesado para ataque."]
  ].forEach(a=>armor(HEROIS,...a));

  [
    ["Ábaco","Equipamento de aventura","T$ 45",1,"Ajuda em cálculos; com Conhecimento pode melhorar sustento e Poder Monetário."],
    ["Ampulheta","Equipamento de aventura","T$ 45",1,"Ao escolher 10 em Ofício (alquimista), considera o d20 como 12."],
    ["Aparelho de chá","Equipamento de aventura","T$ 30",1,"Uma vez por cena, +1d4 em Diplomacia ou Enganação com alguém tomando chá."],
    ["Armação para mochila","Equipamento de aventura","T$ 50",0,"Mochila de aventureiro aumenta carga em 6 espaços, mas sacar itens fica mais lento."],
    ["Asas do texugo","Equipamento de aventura","T$ 200",2,"Com teste de Atletismo, concede voo 12m por rodadas limitadas; ruim para magias."],
    ["Astrolábio","Equipamento de aventura","T$ 90",1,"Permite usar Conhecimento no lugar de Sobrevivência para orientar-se."],
    ["Bainha adornada","Equipamento de aventura","T$ 100",1,"Permite portar arma como parte de traje da corte."],
    ["Bússola","Equipamento de aventura","T$ 45",1,"Rola dois dados e usa o melhor em Sobrevivência para orientar-se."],
    ["Cinto de utilidades","Equipamento de aventura","T$ 50",1,"Permite sacar e guardar engenhocas como ação livre."],
    ["Condecoração militar","Equipamento de aventura","—",1,"No início de combate, concede PV temporários conforme o patamar da condecoração."],
    ["Dente falso","Equipamento de aventura","T$ 300",0,"Armazena uma poção ou preparado sem ocupar espaço; ingerir quebra o item."],
    ["Diagrama anatômico","Equipamento de aventura","T$ 75",1,"Ataque Furtivo recebe +1 na margem de ameaça."],
    ["Espelho refletor","Equipamento de aventura","T$ 45",1,"Uma vez por cena, pode deixar criatura desprevenida contra seu próximo ataque."],
    ["Estetoscópio","Equipamento de aventura","T$ 60",1,"Ajuda testes de Cura ou Ladinagem para fechaduras/sabotagem."],
    ["Estrepes (bolsa para 3m)","Equipamento de aventura","T$ 5",1,"Cobre área adjacente; causa 1d4 perfuração e deixa lenta por 1 rodada."],
    ["Favor da pessoa amada","Equipamento de aventura","—",1,"Fornece +2 PM enquanto o vínculo afetivo permanecer intacto."],
    ["Lampião de foco","Equipamento de aventura","T$ 15",1,"Lampião que concentra luz em cone de 24m."],
    ["Leque","Equipamento de aventura","T$ 3",1,"Uma vez por cena, pode usar Carisma em vez de Sabedoria em Vontade."],
    ["Livro de métodos anti-Nimb","Equipamento de aventura","T$ 100",1,"Por 1 minuto e 1 PM, substitui Jogatina por Conhecimento até o fim da cena."],
    ["Lupa","Equipamento de aventura","T$ 30",1,"Rola dois dados em Investigação para procurar e usa o melhor."],
    ["Mapa","Equipamento de aventura","T$ 30",1,"+5 em Sobrevivência para orientar-se na região do mapa."],
    ["Mecanismo de mola","Equipamento de aventura","T$ 25",1,"Saca arma leve ocultável como ação livre e a torna surpreendente nesse ataque."],
    ["Mochila discreta","Equipamento de aventura","T$ 20",1,"Compartimento oculto para 1 espaço; +5 em Ladinagem para ocultar esses itens."],
    ["Prancheta","Equipamento de aventura","T$ 5",1,"Ajuda a parecer autoridade em situações sociais apropriadas."],
    ["Sinete","Equipamento de aventura","T$ 50",1,"Reduz em -1 PM habilidades ligadas a símbolo pessoal, a critério do mestre."],
    ["Apito de caça","Ferramenta","T$ 6",1,"+1 em Adestramento e manejo animal livre uma vez por rodada com parceiros não inteligentes."],
    ["Baralho marcado","Ferramenta","T$ 15",1,"+2 em Jogatina com cartas; 1 natural revela a trapaça."],
    ["Espelho cirúrgico","Ferramenta","T$ 12",1,"Remove penalidade de -5 em Cura em si mesmo."],
    ["Estandarte","Ferramenta","T$ 15",1,"Capangas recebem +1 na Defesa e dano enquanto empunhado."],
    ["Estandarte portátil","Ferramenta","T$ 20",1,"Como estandarte, mas preso às costas ou sela; pode impor penalidade."],
    ["Molde pré-fabricado","Ferramenta","T$ 500",1,"Reduz fabricação de engenhoca de uma escola para três dias."],
    ["Clarim deheoni","Ferramenta","T$ 150",1,"Instrumento: Inspiração concede +1 adicional em resistências."],
    ["Cítara heptatônica","Ferramenta","T$ 250",1,"Instrumento: aliados inspirados recebem +2 na CD da primeira habilidade mágica."],
    ["Cornamusa de Doherimm","Ferramenta","T$ 750",2,"Instrumento vestido; Inspiração custa -1 PM, mas impõe -2 Defesa."],
    ["Flauta sar-allan","Ferramenta","T$ 150",1,"Instrumento: +5 em Atuação para Música contra criaturas reptilianas."],
    ["Gaita de foles","Ferramenta","T$ 500",1,"Instrumento: teste de Atuação pode aumentar Inspiração em +1."],
    ["Lira de casco de tartaruga","Ferramenta","T$ 300",1,"Instrumento: Músicas e magias de bardo de cura recuperam +1 PV por dado."],
    ["Marionetes","Ferramenta","T$ 90",1,"Instrumento: melhora Balada Fascinante, Fascinar em Massa e Manipular."],
    ["Pandeiro das estradas","Ferramenta","T$ 200",1,"Instrumento: pode manter concentração em certas Músicas como ação de movimento."],
    ["Tamborete marcial","Ferramenta","T$ 80",1,"Instrumento de cadência marcial para bardos."],
    ["Trombeta tapistana","Ferramenta","T$ 300",1,"Instrumento com função marcial/social tapistana."],
    ["Violino soprano","Ferramenta","T$ 300",1,"Instrumento refinado de alto alcance sonoro."],
    ["Avental de forja","Vestuário","T$ 75",1,"Pode perder 1d6 PV para receber +1 em Ofício."],
    ["Camisolão","Vestuário","T$ 12",1,"Dormir só com ele transforma descanso confortável em luxuoso."],
    ["Capa com dragonas","Vestuário","T$ 50",1,"Armadura conta como traje da corte."],
    ["Casaca de apetrechos","Vestuário","T$ 75",0,"Aumenta carga em 4 espaços; penalidade -2 e não pode ser usada com armadura."],
    ["Chapéu emplumado","Vestuário","T$ 50",1,"Na primeira rodada, saudação pode conceder 1 PM temporário."],
    ["Elmo leve","Vestuário","T$ 15",1,"Fortificação 25%; -2 em Iniciativa e Percepção se sem proficiência pesada."],
    ["Elmo pesado","Vestuário","T$ 200",1,"Fortificação 50%; -5 em Iniciativa e Percepção, reduzível com proficiência pesada."],
    ["Jaqueta de couro","Vestuário","T$ 15",1,"+1 em Investigação para interrogar e reduz custo desses testes."],
    ["Luva de falcoaria","Vestuário","T$ 15",1,"+2 em Adestramento com pássaros e similares."],
    ["Luva magnética","Vestuário","T$ 20",1,"Vítima de punga sofre -5 para perceber o furto de objetos ferrosos."],
    ["Máscara bucal","Vestuário","T$ 3",1,"Dificulta que testemunhas descrevam o usuário."],
    ["Máscara completa","Vestuário","T$ 15",1,"Escolha perícia de Carisma; concede +1 em testes apropriados."],
    ["Máscara de baile","Vestuário","T$ 25",1,"Uma vez por cena em situação apropriada, repete Diplomacia ou Enganação."],
    ["Máscara de soldador","Vestuário","T$ 50",1,"Pode usar Percepção para ajudar a si mesmo em Ofício."],
    ["Monóculo","Vestuário","T$ 50",1,"Orgulho em Vontade recebe +2 adicional."],
    ["Óculos de aeronauta","Vestuário","T$ 15",1,"+1 em Pilotagem."],
    ["Palmar","Vestuário","T$ 12",1,"Em natação, avança deslocamento inteiro ao passar em Atletismo."],
    ["Peruca","Vestuário","T$ 20",1,"Carisma menor que 0 conta como 0 para perícias do atributo durante uma cena."],
    ["Rondel","Vestuário","T$ 150",1,"Armadura recebe +1 Defesa, mas impõe -2 em ataques se sem proficiência pesada."],
    ["Roupão elegante","Vestuário","T$ 150",1,"+5 em Diplomacia dentro de estrutura própria, se vestido de modo relaxado."],
    ["Rufo","Vestuário","T$ 25",1,"Com traje da corte, concede +1 em Diplomacia."],
    ["Sapatos confortáveis","Vestuário","T$ 6",1,"Ignora o primeiro teste de Fortitude para marcha forçada."],
    ["Sapatos de salto alto","Vestuário","T$ 18",1,"Reduz deslocamento e prejudica marcha, mas pode ativar Atraente contra uma criatura."],
    ["Veste acolchoada","Vestuário","T$ 60",1,"Usada sob armadura; reduz multiplicadores críticos recebidos, mas aumenta penalidade."],
    ["Compasso místico","Esotérico","T$ 600",1,"Ao lançar magia em área, pode excluir um alvo da área."],
    ["Flauta convocadora","Esotérico","T$ 300",1,"Magias que conjuram capangas invocam um capanga adicional."],
    ["Mandala onírica","Esotérico","T$ 300",1,"Quando inimigo falha em Vontade contra sua magia, recebe 1 PM temporário."],
    ["Varinha armamentista","Esotérico","T$ 600",1,"Arcano de Batalha concede +2 dano adicional."],
    ["Ácido concentrado","Alquímico","T$ 60",0.5,"Causa 4d8 ácido e vulnerável; Reflexos CD Des reduz e evita condição."],
    ["Analgésico","Alquímico","T$ 60",0.5,"Até o fim da cena, permite gastar PM limitados para reduzir dano sofrido."],
    ["Estalinho Gury","Alquímico","T$ 30",0.5,"Explosão em 3m causa 4d6 impacto e surdez; Fortitude CD Des reduz/evita."],
    ["Extrato de gelo eterno","Alquímico","T$ 60",0.5,"Alvo em alcance curto sofre 2d12 frio e fica lento; Reflexos CD Des reduz/evita."],
    ["Extrato de oxxdon","Alquímico","T$ 180",0.5,"Destrói metal não mágico em área e fatiga criaturas metálicas."],
    ["Frasco abissal","Alquímico","T$ 300",0.5,"Área de 3m sofre 6d6 fogo e chamas fortes; Reflexos CD Des reduz/evita."],
    ["Pó de cinza","Alquímico","T$ 5",0.5,"+5 em Ladinagem para abrir fechaduras ou sabotar."],
    ["Pó do aparecimento","Alquímico","T$ 30",0.5,"Revela criaturas invisíveis em 3m, deixando apenas camuflagem leve."],
    ["Visco persistente","Alquímico","T$ 25",0.5,"Causa 4d4 ácido e enreda; Fortitude CD Des reduz/evita."],
    ["Cristal reflexivo","Alquímico","T$ 30",0.5,"Catalisador: magia de adivinhação concede +1 Defesa pela duração."],
    ["Essência fantasmal","Alquímico","T$ 30",0.5,"Catalisador: magia ignora 5 pontos de RD das criaturas afetadas."],
    ["Noz saltadora","Alquímico","T$ 90",0.5,"Catalisador: após lançar a magia, teletransporta até 4,5m."],
    ["Presa de Hyninn","Alquímico","T$ 45",0.5,"Catalisador: 25% de chance de ignorar ataques e efeitos por 1 rodada."],
    ["Bolor hemorrágico","Alquímico","T$ 60",0.5,"Veneno de contato: vítima fica sangrando e mais difícil de estabilizar."],
    ["Fumaça onírica","Alquímico","T$ 150",0.5,"Veneno de inalação resistido com Vontade; fascina por 3 rodadas."],
    ["Gás moroso","Alquímico","T$ 60",0.5,"Veneno de inalação: deixa vulnerável."],
    ["Seiva necrótica","Alquímico","T$ 120",0.5,"Veneno de contato: perde PV por rodada e só cura com luz mágica."],
    ["Captador de luz","Aparato","T$ 450",0,"Aparato: curas de luz da engenhoca aumentam em +1 por dado."],
    ["Comutador","Aparato","T$ 300",0,"Aparato: diminui em -1 PM o custo total dos aprimoramentos da engenhoca."],
    ["Conversor-alimentador","Aparato","T$ 300",0,"Aparato: usa essência de mana/preparados para pagar aprimoramentos e sustento."],
    ["Engenho de automação","Aparato","T$ 600",0,"Aparato: engenhoca sustentada não conta no limite simultâneo."],
    ["Espera para melhorias","Aparato","T$ 150",0,"Aparato: permite instalar melhorias compatíveis na engenhoca."],
    ["Estabilizador","Aparato","T$ 900",0,"Aparato: +2 na CD para resistir ao efeito da engenhoca."],
    ["Estimulador de sobrecarga","Aparato","T$ 750",0,"Aparato: engenhoca de dano causa +1 dado."],
    ["Gatilho de corda","Aparato","T$ 1.500",0,"Aparato acoplado a engenhocas; solto ocupa 1 espaço."],
    ["Giroscópio","Aparato","T$ 450",0,"Aparato acoplado a engenhocas; solto ocupa 1 espaço."],
    ["Ligação de convergência","Aparato","T$ 300",0,"Aparato acoplado a engenhocas; solto ocupa 1 espaço."],
    ["Remontagem de portabilidade","Aparato","T$ 300",0,"Aparato acoplado a engenhocas; solto ocupa 1 espaço."],
    ["Sequenciador de ativação","Aparato","T$ 600",0,"Aparato acoplado a engenhocas; solto ocupa 1 espaço."],
    ["Sistema de refrigeração","Aparato","T$ 900",0,"Aparato acoplado a engenhocas; solto ocupa 1 espaço."],
    ["Supressor de segurança","Aparato","T$ 300",0,"Aparato acoplado a engenhocas; solto ocupa 1 espaço."],
    ["Transformador místico","Aparato","T$ 600",0,"Aparato acoplado a engenhocas; solto ocupa 1 espaço."],
    ["Baga celeste cozida","Alimentação","T$ 15",0,"Prato especial de Heróis de Arton."],
    ["Cozido de pimenta","Alimentação","T$ 10",0,"Prato especial de Heróis de Arton."],
    ["Manjar de sombras","Alimentação","T$ 20",0,"Prato especial de Heróis de Arton."],
    ["Baba de troll","Alimentação","T$ 30",0.5,"Bebida especial de Heróis de Arton."],
    ["Barba queimada","Alimentação","T$ 45",0.5,"Bebida especial de Heróis de Arton."],
    ["Cerveja deheoni","Alimentação","T$ 15",0.5,"Bebida especial de Heróis de Arton."],
    ["Dilínio","Alimentação","T$ 600",0.5,"Bebida especial de Heróis de Arton."],
    ["Grogue negro","Alimentação","T$ 15",0.5,"Bebida especial de Heróis de Arton."],
    ["Grogue rubro","Alimentação","T$ 45",0.5,"Bebida especial de Heróis de Arton."],
    ["Hidromel uivante","Alimentação","T$ 21",0.5,"Bebida especial de Heróis de Arton."],
    ["Licor feérico","Alimentação","T$ 450",0.5,"Bebida especial de Heróis de Arton."],
    ["Sidra ahleniense","Alimentação","T$ 45",0.5,"Bebida especial de Heróis de Arton."],
    ["Vinho Pruss","Alimentação","T$ 60",0.5,"Bebida especial de Heróis de Arton."],
    ["Vinho élfico","Alimentação","T$ 90",0.5,"Bebida especial de Heróis de Arton."],
    ["Armadura de montaria leve","Animal","T$ 600",2,"Armadura para montaria."],
    ["Armadura de montaria pesada","Animal","T$ 3.000",5,"Armadura para montaria."],
    ["Arreios namalkahnianos","Animal","T$ 50",1,"Equipamento de montaria."],
    ["Caparazão","Animal","T$ 75",1,"Equipamento de montaria."],
    ["Estribos","Animal","T$ 60",1,"Equipamento de montaria."],
    ["Ornamento","Animal","T$ 50",1,"Equipamento de montaria."],
    ["Barcaça","Veículo","T$ 3.000",0,"Veículo aquático."],
    ["Biga de guerra","Veículo","T$ 250",0,"Veículo de combate."],
    ["Dirigível goblin","Veículo","T$ 1.200",0,"Veículo aéreo goblin."],
    ["Jangada","Veículo","T$ 60",0,"Veículo aquático simples."],
    ["Veleiro","Veículo","T$ 10.000",0,"Veículo aquático."],
    ["Banho quente","Serviço","T$ 10",0,"Serviço."],
    ["Bigode encerado","Serviço","T$ 20",0,"Serviço."],
    ["Instrução marcial","Serviço","T$ 300",0,"Serviço de treinamento."],
    ["Maquiagem profissional","Serviço","T$ 30",0,"Serviço."],
    ["Mercenário: parceiro iniciante","Serviço","T$ 30",0,"Por cena."],
    ["Mercenário: parceiro veterano","Serviço","T$ 150",0,"Por cena."],
    ["Mercenário: capangas iniciantes","Serviço","T$ 90",0,"Por cena."],
    ["Mercenário: capangas veteranos","Serviço","T$ 300",0,"Por cena."],
    ["Ópera","Serviço","T$ 200",0,"Serviço cultural."],
    ["Sarau informativo","Serviço","T$ 150",0,"Serviço social/informativo."]
  ].forEach(i=>add(HEROIS,...i));

  [
    ["Água benta concentrada","Alquímico","T$ 60",0.5,"Como água benta, mas causa 4d10 dano; item religioso."],
    ["Amuleto de Khalmyr","Equipamento de aventura","T$ 30",1,"Uma vez, pode escolher 10 em perícia se passar em Sabedoria CD 10."],
    ["Amuleto de Nimb","Equipamento de aventura","T$ 30",1,"Uma vez, se falhar em Inteligência CD 10, rerrola uma perícia e usa o melhor."],
    ["Apanhador de sonhos","Equipamento de aventura","T$ 40",1,"+2 em resistências enquanto dorme."],
    ["Aspersório","Equipamento de aventura","T$ 50",1,"Dispersa água benta em cone de 4,5m; aumenta CD em +2."],
    ["Cajado de pastor","Equipamento de aventura","T$ 12",2,"Missa fornece 5 PV e 1 PM temporários a cada participante."],
    ["Cálice consagrado","Equipamento de aventura","T$ 300",1,"Devoto pode aumentar poção consumida/aplicada em +1 dado."],
    ["Colar do suplicante","Equipamento de aventura","T$ 100",1,"Devoto pode gastar conta uma vez por dia para recuperar 1 PM."],
    ["Emblema religioso","Equipamento de aventura","T$ 30",1,"Por 1 PM, devoto recebe benefício de ser treinado em Religião até o fim da cena."],
    ["Férula","Equipamento de aventura","T$ 100",1,"Canalizar Energia aumenta em +1d6; pode ser usada como maça."],
    ["Panfleto de aforismos","Equipamento de aventura","T$ 60",1,"Remove uma condição física/cansaço com ação completa e 1 PM."],
    ["Patuá","Equipamento de aventura","T$ 50",1,"Com devoção, fornece RD 2/mundano e resistência a magia +1."],
    ["Texto sagrado","Equipamento de aventura","T$ 60",1,"Remove uma condição mental/medo com ação completa e 1 PM."],
    ["Trombeta do cruzado","Ferramenta","T$ 100",1,"Instrumento: convocações divinas custam -1 PM e capangas recebem +2 dano."],
    ["Anel eclesiástico","Vestuário","T$ 50",1,"Clérigos e frades recebem +1 em Diplomacia e Intimidação."],
    ["Carcaça do predador primal","Vestuário","T$ 150",1,"Forma selvagem/metamorfose aumenta Defesa da forma em +1."],
    ["Garras do predador primal","Vestuário","T$ 300",1,"Forma selvagem/metamorfose concede +1 dano com armas naturais."],
    ["Hábito monástico","Vestuário","T$ 30",1,"+2 em Vontade contra mental e +2 CD de Tranquilidade; penalidade social com ricos/nobres."],
    ["Hábito sacerdotal","Vestuário","T$ 30",1,"+2 em perícias de Carisma com devotos da mesma divindade."],
    ["Manto de alto sacerdote","Vestuário","T$ 100",1,"Com Autoridade Eclesiástica, +1 PM por patamar acima de iniciante."],
    ["Penas do predador primal","Vestuário","T$ 100",1,"Em forma selvagem/metamorfose, +2 Atletismo e +3m deslocamento."],
    ["Piercing de umbigo","Vestuário","T$ 50",1,"+1 CD para resistir a enfeitiçado, fascinado ou pasmo se sem armadura/armadura sensual."],
    ["Sandálias","Vestuário","T$ 9",1,"-2 contra clima/derrubar, mas +1 PM para conjuradores divinos."],
    ["Tonsura","Vestuário","T$ 3",0,"-5 Intimidação; permite usar Aparência Inofensiva."],
    ["Túnica do Virtuoso","Vestuário","T$ 25",1,"Conta como Virtude Paladinesca para PM adicionais após 1 dia."],
    ["Afiador solar","Esotérico","T$ 100",1,"Magias que dão dados de dano a armas podem mudar esse dano para luz."],
    ["Báculo da retribuição","Esotérico","T$ 200",1,"Magias de cura de luz podem recuperar 1 PM das criaturas curadas."],
    ["Contas de oração","Esotérico","T$ 500",1,"Aumenta limite de PM para magias divinas em +1."],
    ["Estola","Esotérico","T$ 150",1,"CD de uma magia divina específica aumenta em +2; pode ser vestida."],
    ["Frasco purificador","Esotérico","T$ 100",1,"Magias de alvo criatura curam 1d4 PV por dose gasta."],
    ["Medalhão afiado","Esotérico","T$ 900",1,"Magias que dão bônus em ataque também concedem +1 margem de ameaça."],
    ["Ostensório santificado","Esotérico","T$ 750",1,"Escolha uma magia: custo -1 PM quando lançada em devotos do seu deus."],
    ["Rede de almas","Esotérico","T$ 600",1,"Magias divinas de trevas concedem PV temporários em resultados máximos de dano."],
    ["Turíbulo ungido","Esotérico","T$ 100",1,"Aumenta área de magias em +1,5m."],
    ["Granada redentora","Alquímico","T$ 60",0.5,"Área de 3m cura 6d4 PV por luz."],
    ["Santa granada de mão","Alquímico","T$ 150",0.5,"Mortos-vivos e abissais em 3m sofrem 6d12 luz; Reflexos CD Sab reduz."],
    ["Incenso","Alquímico","T$ 12",0.5,"Usado em Missa, concede 2 PM temporários adicionais aos participantes."],
    ["Lucidílico","Alquímico","T$ 30",0.5,"Bebida instável: pode perder PM ou ganhar ações adicionais até o fim da cena."],
    ["Água benta","Alquímico","T$ 10",0.5,"Catalisador: abissais e mortos-vivos afetados por magia divina sofrem mais."],
    ["Favo de mel","Alquímico","T$ 30",0.5,"Catalisador: remove uma condição de cansaço de criatura afetada por magia divina."],
    ["Fitilho consagrado","Alquímico","T$ 30",0.5,"Catalisador: +1 PM para aprimorar magia divina."],
    ["Flor de orlyn","Alquímico","T$ 30",0.5,"Catalisador: uma segunda criatura recupera metade da cura."],
    ["Lantejoula","Alquímico","T$ 30",0.5,"Catalisador: magias de ilusão custam -1 PM."],
    ["Frasco de luz","Alquímico","T$ 30",0.5,"Catalisador: +2 CD em magias de luz."],
    ["Pena de anjo","Alquímico","T$ 30",0.5,"Catalisador: alvos de magia divina recuperam 1d8 PV."],
    ["Pedra de sombras","Alquímico","T$ 30",0.5,"Catalisador: magias de trevas custam -1 PM."],
    ["Vela eclesiástica","Alquímico","T$ 60",0.5,"Catalisador: magia divina sustentada não conta no limite enquanto a vela é mantida."],
    ["Abraço da noite","Alimentação","T$ 3",0,"Prato divino de Tenebra; concede uso de Carícia Sombria."],
    ["Assado de entranhas","Alimentação","T$ 2",0,"Prato divino de Megalokk; +1 dano corpo a corpo por uma cena."],
    ["Bênção dos mares","Alimentação","T$ 4",0,"Prato divino de Oceano; concede ou melhora deslocamento de natação por uma cena."],
    ["Bolinho de jade","Alimentação","T$ 4",0,"Prato divino de Lin-Wu; concede uso de Kiai Divino."],
    ["Bombas de saber","Alimentação","T$ 4",0,"Prato divino de Tanna-Toh; uma perícia conta como treinada em um teste."],
    ["Caldo de Lena","Alimentação","T$ 3",0,"Prato divino de Lena; cura mágica de luz recupera +2 PV."],
    ["Coragem de sangue","Alimentação","T$ 4",0,"Prato divino de Arsenal; uma vez, ação agredir permite ataque extra."],
    ["Deleite mágico","Alimentação","T$ 18",0,"Prato divino de Wynna; lança uma magia de 1º círculo uma vez."],
    ["Frescor de Nimb","Alimentação","T$ 1",0,"Prato divino de Nimb; sorteia benefício de outro prato divino."],
    ["Joia do deserto","Alimentação","T$ 5",0,"Prato divino de Azgher; arma corpo a corpo de corte causa dano de fogo temporário."],
    ["Justos de Khalmyr","Alimentação","T$ 2",0,"Prato divino de Khalmyr; permite escolher 10 em um teste."],
    ["Justos virtuosos","Alimentação","T$ 6",0,"Prato divino de Sszzaas; pode ser afetado por habilidade inimiga como aliado."],
    ["Manjar da paz","Alimentação","T$ 7",0,"Prato divino de Marah; uma criatura em alcance curto rola dois dados e usa o pior em ataque."],
    ["Ouro de dragão","Alimentação","T$ 6",0,"Prato divino de Kallyadranoch; +1 em ataques por uma cena."],
    ["Ovos de raposa","Alimentação","T$ 3",0,"Prato divino de Hyninn; rerrola Enganação ou Ladinagem."],
    ["Pão de Thwor","Alimentação","T$ 1",0,"Prato divino de Thwor; rerrola Fortitude ou perícia baseada em Força."],
    ["Presente da terra","Alimentação","T$ 3",0,"Prato divino de Allihanna; rerrola Adestramento ou Sobrevivência."],
    ["Renascer gentil","Alimentação","T$ 30",0,"Prato divino de Thyatis; uma vez, cairia a 0 PV ou menos e fica com 1 PV."],
    ["Suflê rubro","Alimentação","T$ 3",0,"Prato divino de Aharadak; início de cena gera efeito aleatório."],
    ["Tesouro de Valkaria","Alimentação","T$ 2",0,"Prato divino de Valkaria; +5 em resistência contra movimento."],
    ["Casamento","Serviço","T$ 150",0,"Por pessoa; cria reserva conjunta de 3 PM entre cônjuges em alcance curto."],
    ["Cerimônia religiosa","Serviço","T$ 20",0,"Devoto recebe +1 em Religião e Vontade e +2 PM até o fim da aventura."],
    ["Sacramento","Serviço","T$ 50",0,"Devoto recebe uma magia divina de 1º círculo para lançar uma vez até o fim da aventura."]
  ].forEach(i=>add(DEUSES,...i));

  [
    ["Açoite finntroll","Armas exóticas","T$ 30",1,"1d8","x2","","corte","Alvo que sofre dano recebe -2 em perícias e dano por 1 rodada."],
    ["Arcabuz","Armas de fogo","T$ 800",2,"2d10","19/x3","médio","perfuração","Arma desbalanceada; recarregar é ação padrão."],
    ["Arpão","Armas exóticas","T$ 30",1,"1d10","x3","curto","perfuração","Pode prender o alvo com corda; usado por devotos do Oceano."],
    ["Bacamarte","Armas de fogo","T$ 450",2,"4d6","19/x3","especial","perfuração","Ataca em cone de 6m; recarregar exige ação completa e 2 balas."],
    ["Espada vespa","Armas exóticas","T$ 75",1,"2d4","18","","corte ou perfuração","Alterna ferrões unidos/separados para corte ou perfuração."],
    ["Gládio","Armas marciais","T$ 12",1,"1d6","19/x3","","perfuração"],
    ["Lança de fogo","Armas exóticas","T$ 1.000",2,"especial","especial","especial","perfuração","Arma híbrida corpo a corpo/arma de fogo; pode disparar ao atacar."],
    ["Mordida do diabo","Armas exóticas","T$ 30",1,"1d4","x2","","perfuração","Ágil e versátil; +2 para agarrar e desarmar, alcança 3m."],
    ["Neko-te","Armas marciais","T$ 10",1,"1d4","19","","corte","+2 em Atletismo para escalar; duas aumentam escalada em +1,5m."],
    ["Pistola-punhal","Armas exóticas","T$ 300",1,"especial","especial","especial","perfuração","Arma híbrida lâmina/pistola; pode disparar ao atacar corpo a corpo."],
    ["Porrete","Armas simples","T$ 2",1,"1d6","x2","","impacto","Causa dano não letal."],
    ["Presa de serpente","Armas exóticas","T$ 1.000",1,"1d8","17","","corte","Ágil; em crítico, dano aumenta um passo antes de multiplicar."],
    ["Shuriken","Armas exóticas","T$ 1",0.5,"1d4","x2","curto","perfuração","Uma vez por rodada, 1 PM para ataque adicional contra o mesmo alvo."],
    ["Tetsubo","Armas marciais","T$ 20",2,"1d10","x2","","impacto","+2 para derrubar ou empurrar."],
    ["Traque","Armas de fogo","T$ 75",1,"2d6","19/x3","curto","perfuração","Se errar com resultado ímpar no d20, fica avariada."],
    ["Zarabatana","Armas simples","T$ 5",1,"1d3","x2","curto","perfuração","CD para resistir ao veneno dos dardos aumenta em +2."]
  ].forEach(w=>weapon(AMEACAS,...w));

  [
    ["Dardos de zarabatana (20)","Munição","T$ 2",0.5,"Munição para zarabatana."],
    ["Armadura de ossos","Armadura leve","T$ 120",2,"+3","-2","+1 em Intimidação e na CD de efeitos de medo."],
    ["Veste de teia de aranha","Armadura leve","T$ 3.000",2,"+4","0","+5 em Furtividade; não recebe material especial."],
    ["Armadura de quitina","Armadura pesada","T$ 350",5,"+7","-3","Não reduz deslocamento."],
    ["Escudo de couro","Escudo","T$ 3",1,"+1","-1","+2 Defesa contra ataques à distância; não serve como arma."]
  ].forEach(i=>{
    if(i.length===7) armor(AMEACAS,...i);
    else add(AMEACAS,...i);
  });

  [
    ["Caixa de voz","Equipamento de aventura","T$ 50",1,"Tem 1d4 cargas; aumenta alcance de habilidade de bardo ou nobre em um passo."],
    ["Corda de teia","Equipamento de aventura","T$ 100",1,"Corda de 10m resistente; arrebentar exige 5 dano de corte ou Força CD 28."],
    ["Dente de wisphago","Equipamento de aventura","T$ 100",1,"Gasto para rerrolar resistência contra magia arcana com +2."],
    ["Gema de força","Equipamento de aventura","—",1,"Tem 1d4 cargas; cria domo como Campo de Força ou reduz seu custo."],
    ["Garra feroz","Vestuário","T$ 60",1,"Como manopla; também se aplica a garra ou arma natural em Forma Selvagem."],
    ["Manto do mantor","Vestuário","T$ 450",1,"Na escuridão completa, fornece camuflagem total."],
    ["Manto pesado","Vestuário","T$ 10",1,"Imunidade a ofuscado e evita ser considerado sob luz solar durante o dia."],
    ["Sombreiro","Vestuário","T$ 10",1,"Resistência a efeitos de sentidos +2."],
    ["Traje selako","Vestuário","T$ 90",1,"+2 em Atletismo para nadar e +3m no deslocamento de natação."],
    ["Ankh solar","Esotérico","T$ 450",1,"Pode ser arma leve; magias podem impedir recuperação de PV por 1 rodada."],
    ["Tomo de guerra","Esotérico","T$ 300",1,"Ao lançar magia de evocação, recebe +1 PM para aprimoramentos."],
    ["Tomo do rancor","Esotérico","T$ 750",1,"Magias de dano podem causar +2d8+2 de corte, impacto ou perfuração."],
    ["Bálsamo de drogadora","Alquímico","T$ 60",0.5,"Ação completa para curar 4d6+4 PV."],
    ["Bomba de fumaça","Alquímico","T$ 15",0.5,"Cria nuvem de fumaça de 6m até o fim da cena."],
    ["Elixir quimérico","Alquímico","T$ 120",0.5,"Até o fim da cena, concede mordida ou aumenta mordida existente."],
    ["Éter elemental","Alquímico","T$ 60",0.5,"Arma ou 20 munições causam +1d4 dano elemental até o fim da cena."],
    ["Isca putrefata","Alquímico","T$ 60",0.5,"Atrai mortos-vivos não inteligentes para local ou criatura marcada."],
    ["Lágrima pétrea","Alquímico","T$ 30",0.5,"Remove efeitos de metamorfose de uma criatura."],
    ["Óleo de baleia","Alquímico","T$ 30",0.5,"Arma ou munições ignoram penalidades de combate submerso até o fim da cena."],
    ["Óleo de besouro","Alquímico","T$ 50",0.5,"Pode dobrar lampiões ou explodir causando 4d6 fogo e chamas."],
    ["Pó azul","Alquímico","T$ 150",0.5,"Ação completa para recuperar 2d4 PM."],
    ["Corrosivo mineral","Alquímico","T$ 150",0.5,"Catalisador: aumenta categoria dos dados de dano de magias de ácido."],
    ["Gelo extremo","Alquímico","T$ 150",0.5,"Catalisador: aumenta categoria dos dados de dano de magias de frio."],
    ["Pedaço de língua","Alquímico","T$ 30",0.5,"Catalisador: +1 na CD de Fortitude contra suas magias."],
    ["Raio cristalizado","Alquímico","T$ 150",0.5,"Catalisador: aumenta categoria dos dados de dano de magias de eletricidade."],
    ["Esporos de cogumelo","Alquímico","T$ 75",0.5,"Veneno de inalação; paralisa brevemente."],
    ["Peçonha anciã","Alquímico","T$ 1.800",0.5,"Veneno de contato que ignora imunidade a venenos."],
    ["Peçonha irritante","Alquímico","T$ 10",0.5,"Veneno de contato sem resistência; perda leve de PV."],
    ["Veneno batráquio","Alquímico","T$ 30",0.5,"Veneno de contato; causa perda de PV e enjoo."],
    ["Algravia","Alimentação","T$ 3",0,"Bebida: +1 em perícias de Carisma; doses extras são intoxicantes."],
    ["Banquete de canceronte","Alimentação","T$ 36",0,"Fornece 1d4+1 dados de auxílio para testes."],
    ["Coc-au-triz","Alimentação","T$ 54",0,"Reduz em -1 PM uma habilidade escolhida."],
    ["Cozido de serpe","Alimentação","T$ 12",0,"Se preparado com sucesso, +1 em todos os testes de perícia."],
    ["Gorlogg ensopado","Alimentação","T$ 6",0,"Na próxima noite, recuperação de PV e PM aumenta em +1 por nível."],
    ["Omelete monstruosa","Alimentação","T$ 3",0,"+2 dano e -2 em perícias de Sabedoria."],
    ["Sashimi de kraken","Alimentação","T$ 60",0,"+2 Diplomacia e 5 PM temporários."],
    ["Bulette","Animal","T$ 500",0,"Parceiro montaria iniciante."],
    ["Capivara","Animal","T$ 60",0,"Parceiro montaria para personagens Pequenos e Minúsculos."],
    ["Corcel do deserto","Animal","T$ 150",0,"Parceiro montaria iniciante."],
    ["Dromedário","Animal","T$ 75",0,"Parceiro montaria iniciante."],
    ["Elefante","Animal","T$ 1.500",0,"Parceiro montaria/trabalho iniciante."],
    ["Hiena","Animal","T$ 220",0,"Parceiro especial ou montaria para personagens Pequenos e Minúsculos."],
    ["Leão","Animal","T$ 800",0,"Parceiro montaria iniciante."],
    ["Rinoceronte","Animal","T$ 600",0,"Parceiro montaria iniciante, raro e difícil de domesticar."],
    ["Urso pardo","Animal","T$ 300",0,"Parceiro montaria iniciante."],
    ["Casco de monstro","Material especial","Variável",0,"Material para armas, armaduras, escudos e esotéricos; preço depende do item."],
    ["Couraça de kaiju","Material especial","Raro",0,"Material especial poderoso obtido apenas de kaiju abatido."],
    ["Couro de bulette","Material especial","Raro",0,"Material para armaduras/esotéricos ligado a escavação e ácido."],
    ["Cristal de sol","Material especial","Raro",0,"Material ligado a fogo/frio; perde propriedades se não usado."],
    ["Lanajuste","Material especial","Variável",0,"Coral-de-ferro de Khubar; útil para armas, armaduras, escudos e esotéricos."],
    ["Pena de kraken","Material especial","Raro",0,"Material extremamente afiado extraído de kraken."],
    ["Prata","Material especial","Variável",0,"Revestimento contra espíritos e mortos-vivos; combina com outro material especial."],
    ["Quitina razza","Material especial","Raro",0,"Material obtido de razza'kham; melhora críticos, percepção e dados máximos."],
    ["Carapaça","Recurso natural","Variável",0,"Recurso natural para couraças, armaduras completas e escudos pesados."],
    ["Couro","Recurso natural","Variável",0,"Recurso natural para armaduras leves e escudos leves."],
    ["Fonte","Recurso natural","Variável",0,"Recurso natural para itens esotéricos e acessórios mágicos."],
    ["Ingrediente","Recurso natural","Variável",0,"Recurso natural para alquímicos e poções."],
    ["Mantimento","Recurso natural","Variável",0,"Recurso natural alimentar; qualidade depende do patamar da ameaça."],
    ["Osso","Recurso natural","Variável",0,"Recurso natural para armas e itens macabros/tumulares."],
    ["Sucata","Recurso natural","Variável",0,"Recurso natural para engenhocas e itens de metal."]
  ].forEach(i=>add(AMEACAS,...i));

  [
    ["Esotérico mágico menor","Itens esotéricos","Base + T$ 18.000",1,"Modelo para um esotérico com 1 encanto de esotérico de Heróis de Arton."],
    ["Esotérico mágico médio","Itens esotéricos","Base + T$ 36.000",1,"Modelo para um esotérico com 2 encantos de esotérico de Heróis de Arton."],
    ["Esotérico mágico maior","Itens esotéricos","Base + T$ 72.000",1,"Modelo para um esotérico com 3 encantos de esotérico de Heróis de Arton."],
    ["Adaga da bruma","Armas mágicas","T$ 27.000",1,"Adaga formidável. Ao acertar, pode gastar 2 PM para ficar invisível por 1 rodada."],
    ["Arco das sombras","Armas mágicas","T$ 27.000",2,"Arco curto sombrio. Ao acertar com 2 PM, pode deixar o alvo cego por 1 rodada."],
    ["Arco do crepúsculo","Armas mágicas","T$ 22.500",2,"Arco longo formidável. Ao acertar com 1 PM, deixa o alvo ofuscado por 1d4 rodadas."],
    ["Azagaia fantasma","Armas mágicas","T$ 30.000",1,"Azagaia caçadora cristalina. Pode ignorar RD ao ser arremessada e retorna no fim do turno."],
    ["Besta estelar","Armas mágicas","T$ 30.000",1,"Besta leve cravejada de gemas formidável. Pode disparar luzes que fascinam inimigos na área."],
    ["Clava de lava","Armas mágicas","T$ 45.000",1,"Clava maciça flamejante formidável. Pode aumentar o dano de fogo do encanto para +3d6."],
    ["Espada da tempestade","Armas mágicas","T$ 45.000",1,"Espada longa precisa formidável trovejante. Críticos podem espalhar o atordoamento do trovão."],
    ["Espada do guardião","Armas mágicas","T$ 54.000",1,"Espada longa defensora formidável. Pode criar barreira de RD para você e aliados próximos."],
    ["Espada solar","Armas mágicas","T$ 45.000",1,"Espada bastarda magnífica. Pode emitir clarão que cega inimigos em alcance curto."],
    ["Florete do vendaval","Armas mágicas","T$ 27.000",1,"Florete leve formidável de mitral. Pode conceder voo breve e Defesa contra ataques à distância."],
    ["Lança da fênix","Armas mágicas","T$ 100.000",1,"Lança flamejante magnífica. Recupera PV ao derrubar inimigos e pode reerguer o portador em explosão de fogo."],
    ["Machado da natureza","Armas mágicas","T$ 22.500",1,"Machado de batalha preciso formidável. Em acertos críticos, recupera PV."],
    ["Machado do abismo","Armas mágicas","T$ 36.000",1,"Machado de batalha macabro formidável. Pode liberar onda de essência que abala criaturas."],
    ["Machado do vulcão","Armas mágicas","T$ 54.000",1,"Machado de guerra maciço flamejante formidável. Pode criar detonação vulcânica em alcance médio."],
    ["Martelo da terra","Armas mágicas","T$ 33.000",1,"Martelo de guerra cravejado de gemas formidável de adamante. Pode abrir rachadura no solo."],
    ["Martelo do titã","Armas mágicas","T$ 22.500",1,"Martelo de guerra formidável. Críticos podem empurrar o alvo."],
    ["Punhal das profundezas","Armas mágicas","T$ 36.000",1,"Adaga formidável marinha. Pode causar dano adicional de ácido."],
    ["Armadura das sombras profundas","Armaduras e escudos mágicos","T$ 40.500",5,"Cota de malha defensora sombria. Fornece redução de luz e acesso a Invisibilidade."],
    ["Armadura do dragão ancião","Armaduras e escudos mágicos","T$ 100.000",5,"Armadura completa guardiã invulnerável. Concede reduções elementais e rugido assustador quando ferido."],
    ["Armadura do inverno perene","Armaduras e escudos mágicos","T$ 40.500",2,"Couraça defensora gélida de gelo eterno. Melhora o encanto gélido e permite Área Escorregadia."],
    ["Cota da serpente marinha","Armaduras e escudos mágicos","T$ 27.000",5,"Cota de malha ajustada guardiã. Fornece natação e acesso a Sopro das Uivantes."],
    ["Couraça do guardião celeste","Armaduras e escudos mágicos","T$ 54.000",2,"Couraça banhada a ouro defensora protetora. Concede Carisma e melhora curas de luz."],
    ["Escudo da luz estelar","Armaduras e escudos mágicos","T$ 27.000",1,"Escudo leve defensor. Concede Percepção e acesso ampliado à magia Luz."],
    ["Escudo da ira vulcânica","Armaduras e escudos mágicos","T$ 54.000",2,"Escudo pesado guardião. Fornece redução de fogo e permite Explosão de Chamas."],
    ["Escudo da natureza viva","Armaduras e escudos mágicos","T$ 27.000",1,"Escudo leve defensor de madeira Tollon. Concede Fortitude e acesso a Curar Ferimentos."],
    ["Escudo do grifo","Armaduras e escudos mágicos","T$ 27.000",2,"Escudo pesado defensor. Fornece RD contra ataques à distância e acesso a Sopro das Uivantes."],
    ["Escudo do trovão","Armaduras e escudos mágicos","T$ 54.000",2,"Escudo pesado guardião de mitral. Pode empurrar inimigos adjacentes quando você sofre ataque corpo a corpo."],
    ["Cajado das marés","Itens esotéricos","T$ 27.000",2,"Cajado arcano glacial. Concede natação e pode conjurar redemoinho que empurra inimigos adjacentes."],
    ["Cálice sagrado","Itens esotéricos","T$ 150.000",1,"Esotérico divino. Reduz custo de magias divinas e aumenta efeitos variáveis por dado."],
    ["Relógio do arcanista","Itens esotéricos","T$ 60.000",1,"Esotérico arcano. Pode acelerar magias arcanas ou reduzir o custo de Magia Acelerada."],
    ["Varinha milenar","Itens esotéricos","T$ 200.000",1,"Varinha arcana ancestral. Aumenta CD e dados de dano de magias arcanas, mas cobra PV quando inimigos resistem."],
    ["A Armadura de Crânio Negro","Artefatos e outros","Artefato",5,"Armadura completa artefato que se move sozinha, conta como leve e sem penalidade, mas traz ecos mentais perigosos."],
    ["O Escudo Impérvio","Artefatos e outros","Artefato",2,"Escudo pesado artefato. Fornece grande Defesa, bônus em resistências e RD elevada."],
    ["O Kailash","Artefatos e outros","Artefato",1,"Boleadeira artefato precisa, de arremesso e múltiplas formas, capaz de capturar, arrastar e se transformar em outras armas."],
    ["Lorde Enxame","Artefatos e outros","Artefato",1,"Espada longa inteligente e venenosa, ligada a insetos, capaz de lançar Legião em criaturas insetoides."],
    ["O Monóculo da Verdade","Artefatos e outros","Artefato",1,"Monóculo artefato. Concede PM, Iniciativa, Intuição, Percepção e acesso a Orientação e Visão da Verdade."],
    ["Slash Calliber","Artefatos e outros","Artefato",1,"Espada longa inteligente e elétrica. Permite Relâmpago, mas tem personalidade caótica e inconveniente."]
  ].forEach(i=>magicItem(HEROIS,...i));

  [
    ["A Armadura Risonha","Artefatos e outros","Artefato",5,"Armadura completa artefato de Nimb. Liberta movimentos, envolve a cena em caos e pode acompanhar escudo refletor."],
    ["O Cálice dos Deuses","Artefatos e outros","Artefato",1,"Cálice artefato que transforma líquidos em bênção heroica, concedendo grandes bônus temporários e imprudência."],
    ["Holy Avenger","Artefatos e outros","Artefato",1,"Espada bastarda suprema. Concede ataque, dano de essência, resistências e um golpe capaz de destruir até deuses."],
    ["Rhumnam, a Espada-Pistola","Artefatos e outros","Artefato",1,"Espada-calibre inteligente de Khalmyr, com modos corpo a corpo e pistola e poderes plenos apenas para portadores dignos."],
    ["A Toga do Reitor","Artefatos e outros","Artefato",1,"Robe místico artefato de Wynna. Protege contra danos, resistências e magias, e fortalece aprimoramentos arcanos."],
    ["A Coroa da União Púrpura","Artefatos e outros","Artefato",1,"Coroa artefato dos Ermos Púrpuras. Concede Fúria, liderança, perícias sociais e invocação de guerreiros púrpuras."]
  ].forEach(i=>magicItem(DEUSES,...i));

  [
    [HEROIS,"Armadura Elemental",1,"Arcana"],
    [HEROIS,"Assobio Perigoso",1,"Arcana"],
    [HEROIS,"Descobrir Fraqueza",1,"Arcana"],
    [HEROIS,"Discrição",1,"Universal"],
    [HEROIS,"Distração Fugaz",1,"Arcana"],
    [HEROIS,"Espírito Balístico",1,"Arcana"],
    [HEROIS,"Farejar Fortuna",1,"Arcana"],
    [HEROIS,"Maaais Klunc",1,"Arcana"],
    [HEROIS,"Ossos de Adamante",1,"Arcana"],
    [HEROIS,"Punho de Mitral",1,"Arcana"],
    [HEROIS,"Toque do Horizonte",1,"Arcana"],
    [HEROIS,"Aura de Morte",2,"Arcana"],
    [HEROIS,"Conjurar Armadilha",2,"Arcana"],
    [HEROIS,"Desafio Corajoso",2,"Arcana"],
    [HEROIS,"Desfazer Engenhoca",2,"Universal"],
    [HEROIS,"Emular Magia",2,"Universal"],
    [HEROIS,"Máquina de Combate",2,"Arcana"],
    [HEROIS,"Piscar",2,"Arcana"],
    [HEROIS,"Poção Explosiva",2,"Arcana"],
    [HEROIS,"Transposição",2,"Arcana"],
    [HEROIS,"Viagem Onírica",2,"Arcana"],
    [HEROIS,"Coração Imortal",3,"Universal"],
    [DEUSES,"Arma de Jade",1,"Divina"],
    [DEUSES,"Arsenal de Allihanna",1,"Divina"],
    [DEUSES,"Bofetada de Nimb",1,"Divina"],
    [DEUSES,"Escapatória de Hyninn",1,"Divina"],
    [DEUSES,"Euforia de Valkaria",1,"Divina"],
    [DEUSES,"Execução de Thwor",1,"Divina"],
    [DEUSES,"Flecha de Luz",1,"Universal"],
    [DEUSES,"Frescor de Lena",1,"Divina"],
    [DEUSES,"Fúria dos Antepassados",1,"Divina"],
    [DEUSES,"Futuro Melhor",1,"Divina"],
    [DEUSES,"Infortúnio de Sszzaas",1,"Divina"],
    [DEUSES,"Instante Estoico",1,"Divina"],
    [DEUSES,"Magia Dadivosa",1,"Divina"],
    [DEUSES,"Orbe do Oceano",1,"Divina"],
    [DEUSES,"Paixão de Marah",1,"Divina"],
    [DEUSES,"Percepção Rubra",1,"Universal"],
    [DEUSES,"Perturbação Sombria",1,"Divina"],
    [DEUSES,"Poder de Kallyadranoch",1,"Divina"],
    [DEUSES,"Posse de Arsenal",1,"Divina"],
    [DEUSES,"Proteção de Tauron",1,"Divina"],
    [DEUSES,"Sigilo de Sszzaas",1,"Divina"],
    [DEUSES,"Siroco de Azgher",1,"Divina"],
    [DEUSES,"Sorriso da Fortuna",1,"Divina"],
    [DEUSES,"Toque de Megalokk",1,"Divina"],
    [DEUSES,"Voz da Razão",1,"Divina"],
    [DEUSES,"Couraça de Allihanna",2,"Divina"],
    [DEUSES,"Punição do Profano",2,"Divina"],
    [DEUSES,"Traição da Lâmina",2,"Divina"],
    [DEUSES,"Traição Mágica",2,"Universal"],
    [AMEACAS,"Açoite Flamejante",1,"Arcana"],
    [AMEACAS,"Dardo Gélido",1,"Arcana"],
    [AMEACAS,"Jato Corrosivo",1,"Arcana"],
    [AMEACAS,"Invocar Fagulha Elemental",2,"Arcana"],
    [AMEACAS,"Momento de Tormenta",2,"Universal"],
    [AMEACAS,"Transformação em Dragão",4,"Arcana"],
    [AMEACAS,"Katana Celestial",5,"Divina"]
  ].forEach(i=>spellConsumable(...i));

  [
    ["Cilício vivo","Acessórios","T$ 37.000",1,"Aharadak. Reduz PV máximos, mas concede bônus em todos os testes; devotos ampliam o benefício."],
    ["Coração corrompido","Acessórios","T$ 45.000",1,"Aharadak. Absorve dano e condições do devoto após sacrifício."],
    ["Coroa de flores","Acessórios","T$ 9.000",1,"Allihanna. Para devotos, +1 Sabedoria e +1 por dado em magias de efeitos variáveis."],
    ["Cajado das matas","Armas mágicas","T$ 27.000",2,"Allihanna. Bordão formidável; ao ar livre sobre terra, +2 Defesa para devotos."],
    ["Tapeçaria da guerra","Acessórios","T$ 35.000",1,"Arsenal. Ferramenta aprimorada de Guerra; devotos podem estender bônus a aliados em combate."],
    ["Machado da bravura","Armas mágicas","T$ 25.000",1,"Arsenal. Machado de batalha litúrgico; em investidas, devoto recebe PM temporários."],
    ["Alfange dourado","Armas mágicas","T$ 36.000",2,"Azgher. Pode sacrificar ouro para ganhar bônus em ataque e dano até o fim do dia."],
    ["Cimitarra solar","Armas mágicas","T$ 54.000",1,"Azgher. Cimitarra flamejante que se fortalece sob luz do sol para devotos."],
    ["Adaga sorrateira","Armas mágicas","T$ 22.500",1,"Hyninn. Devotos recebem bônus após sucesso em Enganação ou Furtividade."],
    ["Cubo armadilha","Acessórios","T$ 25.000",1,"Hyninn. Armadilha invisível que causa 10d8 corte com dados explosivos."],
    ["Lança da dominação","Armas mágicas","T$ 45.000",1,"Kallyadranoch. Devotos causam dano elemental e aumentam bônus conforme sobem de nível."],
    ["Ossos dracônicos","Acessórios","T$ 90.000",1,"Kallyadranoch. +4 Intimidação e -2 Diplomacia; devotos recebem atributos e CD."],
    ["Espada monástica","Armas mágicas","T$ 54.000",1,"Khalmyr. Teste de Religião pode elevar a arma e gerar Oração até o fim da cena."],
    ["Armadura do julgamento","Armaduras e escudos mágicos","T$ 54.000",5,"Khalmyr. Armadura completa que pune atacantes com pasmo/frustração."],
    ["Caldeirão da vida","Acessórios","T$ 25.000",2,"Lena. Permite preparar refeição que concede +2 resistências e PV temporários a devotos."],
    ["Alabarda da coragem","Armas mágicas","T$ 36.000",2,"Lin-Wu. Devotos recebem +5 Iniciativa e PM temporários se agirem primeiro."],
    ["Katana da determinação","Armas mágicas","T$ 54.000",1,"Lin-Wu. Ignora imunidade a crítico de lefeu e recompensa derrotá-los."],
    ["Instrumento da alegria","Acessórios","T$ 10.500",1,"Marah. Tocar concede +2 em perícias a você e aliados; devotos ativam com Música."],
    ["Véu diáfano","Acessórios","T$ 13.500",1,"Marah. Veste aprimorada; para devotos, +1 Carisma e +2 Defesa."],
    ["Colar de presas","Acessórios","T$ 21.000",1,"Megalokk. +2 Intimidação e -2 Diplomacia; devotos melhoram armas naturais."],
    ["Maça monstruosa","Armas mágicas","T$ 27.000",1,"Megalokk. Devotos aumentam bastante o dano da arma."],
    ["Alguma coisa de Nimb","Armas mágicas","T$ 54.000",1,"Nimb. Objeto aleatório que funciona como arma simples formidável veloz para devotos."],
    ["Jarro das profundezas","Acessórios","T$ 9.000",1,"Oceano. Devotos criam água salgada, derrubam em cone ou invocam elemental da água."],
    ["Tridente aquoso","Armas mágicas","T$ 54.000",1,"Oceano. Tridente congelante que pode se tornar magnífico quando mergulhado em água."],
    ["Adaga ofídica","Armas mágicas","T$ 36.000",1,"Sszzaas. Veneno mágico reposto a cada golpe e ignora resistência/imunidade em devotos."],
    ["Bordão sabichão","Armas mágicas","T$ 72.000",2,"Tanna-Toh. Devotos podem gastar 2 PM para somar Sabedoria em testes de perícia."],
    ["Escrivaninha consagrada","Acessórios","T$ 9.000",2,"Tanna-Toh. Estudo de 1 hora dobra bônus de treino em perícia de Int ou Sab por 1 dia."],
    ["Vestido noturno","Acessórios","T$ 21.000",1,"Tenebra. Veste aprimorada; devotos podem ficar invisíveis até o fim da cena."],
    ["Machado lamnoriano","Armas mágicas","T$ 22.500",1,"Thwor. Durante fúria, devotos aumentam o dano da arma."],
    ["Espada imaculada","Armas mágicas","T$ 45.000",1,"Thyatis. Devotos podem transformar lâmina em plasma vermelho não letal."],
    ["Pira póstera","Acessórios","T$ 15.000",1,"Thyatis. +1 Sabedoria e uma rerrolagem diária de iniciativa, percepção ou resistência."],
    ["Botas inquietas","Acessórios","T$ 15.000",1,"Valkaria. +1 Constituição, bônus em marcha forçada e PM temporários em investidas."],
    ["Mangual aventureiro","Armas mágicas","T$ 40.000",1,"Valkaria. Mangual dançarino; em lugares novos, aumenta dano em dois passos."],
    ["Argolas místicas","Acessórios","T$ 25.500",1,"Wynna. Devotos recebem +2 PM para gastar em aprimoramentos de cada magia."],
    ["Varinha da generosidade","Itens esotéricos","T$ 30.000",1,"Wynna. Varinha arcana poderosa; fornece RD 5 e concede PM temporários a aliado quando lança magia."]
  ].forEach(i=>magicItem(DEUSES,...i));

  [
    ["Chifre de unicórnio","Acessórios","T$ 120.000",1,"Permite lançar Curar Ferimentos, Purificação e Segunda Chance; também funciona como espada curta formidável."],
    ["Fragmento de filactério","Acessórios","T$ 90.000",1,"Conta como costela de lich poderosa e fornece +20 PM após um dia de uso."],
    ["Grilhão de descrença","Armaduras e escudos mágicos","T$ 24.000",5,"Armadura completa amaldiçoada; quem chega a 0 PV com ela não pode ser ressuscitado."],
    ["Pilão conspurcado","Itens esotéricos","T$ 21.000",1,"Conta como costela de lich; encantamento e necromancia custam -1 PM e têm CD +2."],
    ["Pistola demoníaca","Armas mágicas","T$ 72.250",1,"Pistola formidável e profana que nunca precisa de munição, mas impõe impulso assassino."],
    ["Uyzrrak Da'ukthra","Armas mágicas","T$ 78.050",1,"Machado de guerra magnífico de adamante que recebe encanto conforme o Akzath próximo."],
    ["Amuleto do abutre","Artefatos e outros","Artefato",1,"Artefato de Ferren Asloth: enorme poder arcano, mas com risco de possessão."],
    ["Rompedor da realidade","Artefatos e outros","Artefato",2,"Artefato lefeu: machado gigante de matéria vermelha que distorce vítimas."]
  ].forEach(i=>magicItem(AMEACAS,...i));

  const bySourceCategoryName=(a,b)=>
    a.source.localeCompare(b.source,"pt-BR")||
    a.category.localeCompare(b.category,"pt-BR")||
    a.name.localeCompare(b.name,"pt-BR");

  window.T20_EXPANSION_ITEM_CATALOG=mundane.sort(bySourceCategoryName);
  window.T20_EXPANSION_MAGIC_ITEM_CATALOG=magic.sort(bySourceCategoryName);
})();
