;(function(){
  const source="Jogo do Ano";
  const normalizeCategory=(category)=>{
    const text=String(category||"").toLowerCase();
    if(text.startsWith("alquímico")||text.startsWith("alquimico")||text==="veneno") return "Alquímico";
    return category;
  };
  const weaponCategory=(category)=>{
    const text=String(category||"").toLowerCase();
    if(text.includes("simples")) return "Armas simples";
    if(text.includes("marcial")) return "Armas marciais";
    if(text.includes("exótica")||text.includes("exotica")) return "Armas exóticas";
    if(text.includes("fogo")) return "Armas de fogo";
    return "Armas";
  };
  const weaponDescriptions={
    "Adaga":"Esta faca afiada é usada por muitos habitantes adultos do Reinado, embora seja favorita de ladrões e assassinos, por ser facilmente escondida (fornece +5 em testes de Ladinagem para ocultá-la). Quando ataca com uma adaga, você pode usar sua Destreza em vez de Força nos testes de ataque. Uma adaga pode ser arremessada.",
    "Alabarda":"Uma haste de madeira com 2m de comprimento e uma lâmina de machado na ponta. A alabarda é uma arma alongada.",
    "Alfange":"Uma versão maior da cimitarra, esta espada de lâmina larga e curva é bastante usada por guerreiros do Deserto da Perdição.",
    "Arco curto":"Uma arma antiga e comum, este arco é usado primariamente como ferramenta de caça, embora seja usado como arma de guerra por milícias, bandidos e exércitos menos equipados. Pode ser usado montado.",
    "Arco longo":"Este arco reforçado tem a altura de uma pessoa. Ao contrário da versão curta, é primariamente uma arma de guerra. Por ter uma puxada pesada, permite que você aplique sua Força às rolagens de dano (ao contrário de outras armas de disparo). Porém, um arco longo não pode ser usado se você estiver montado.",
    "Azagaia":"Uma lança leve e flexível, própria para arremesso. Pode ser usada como arma corpo a corpo, mas você sofre uma penalidade de -5 no teste de ataque.",
    "Besta leve":"Um arco montado sobre uma coronha de madeira com um gatilho, a besta leve é uma arma que dispara virotes com grande potência. Recarregar uma besta leve é uma ação de movimento.",
    "Besta pesada":"Versão maior e mais potente da besta leve. Recarregar uma besta pesada é uma ação padrão.",
    "Bordão":"Um cajado apreciado por viajantes e camponeses por sua praticidade e fácil acesso (seu preço é zero). O bordão é uma arma dupla.",
    "Chicote":"Esta arma pode ser usada para atacar inimigos a até 4,5m e pode se enroscar nas mãos, pernas ou armas de seus adversários. O chicote é uma arma ágil e versátil, fornecendo +2 em testes para derrubar ou desarmar.",
    "Cimitarra":"Espada com a lâmina curva e muito afiada. A cimitarra é uma arma ágil.",
    "Clava":"Um pedaço de madeira empunhado como arma, geralmente usado por bárbaros ou criaturas brutais, ou como arma improvisada, como um galho de árvore ou pedaço de mobília. Sendo fácil de conseguir, seu preço é zero.",
    "Corrente de espinhos":"Esta arma pode ser usada para atacar inimigos a até 4,5m e pode se enroscar nas mãos, pernas ou armas de seus adversários. A corrente de espinhos é uma arma ágil, dupla e versátil, fornecendo +2 em testes para derrubar ou desarmar.",
    "Espada bastarda":"Maior e mais pesada que a espada longa, esta arma é tradicionalmente usada pelos cavaleiros de Bielefeld. A espada bastarda é uma arma adaptável. É muito grande para ser usada com uma só mão sem treinamento especial; por isso é uma arma exótica. Ela pode ser usada como uma arma marcial de duas mãos.",
    "Espada curta":"O tipo mais comum de espada, usada por guardas ou como arma secundária de guerreiros mais capazes. Mede entre 40 e 50cm.",
    "Espada longa":"Arma típica de soldados e guerreiros, esta espada de dois gumes tem lâmina reta medindo entre 80cm e 1m.",
    "Florete":"A lâmina leve e fina desta espada torna a arma muito precisa. O florete é uma arma ágil.",
    "Foice":"Originalmente um instrumento agrícola, consiste de uma lâmina curva presa a um cabo de madeira. Uma arma tradicional de druidas.",
    "Funda":"Uma simples tira de couro usada para arremessar pedras polidas. Na falta de munição adequada, pode disparar pedras comuns, mas o dano é reduzido em um passo. Recarregar uma funda é uma ação de movimento. Ao contrário de outras armas de disparo, você aplica sua Força a rolagens de dano com uma funda.",
    "Gadanho":"Outra ferramenta agrícola, o gadanho é uma versão maior da foice, para uso com as duas mãos. Foi criada para ceifar cereais, mas também pode ceifar vidas.",
    "Katana":"A espada tradicional do samurai tem lâmina levemente curva e apenas um gume. A katana é uma arma adaptável e ágil. É muito grande para ser empunhada com uma só mão sem treinamento especial; por isso, é uma arma exótica. Ela pode ser usada como uma arma marcial de duas mãos.",
    "Lança":"Qualquer arma feita com uma haste de madeira e uma ponta afiada, natural ou metálica. Por sua facilidade de fabricação, é muito comum entre orcs, kobolds, trogloditas e outras raças menos civilizadas. Uma lança pode ser arremessada.",
    "Lança montada":"A lança montada é uma arma alongada. Se você estiver montado, pode usá-la com apenas uma mão. Além disso, quando usada numa investida montada, causa +2d8 pontos de dano (note que dados extras não são multiplicados em caso de acerto crítico).",
    "Maça":"Bastão com um peso cheio de protuberâncias na ponta, a maça é usada por clérigos que fazem votos de não derramar sangue. De fato, um golpe de maça nem sempre derrama sangue, mas esmaga ossos.",
    "Machadinha":"Ferramenta útil para cortar madeira e também inimigos. Uma machadinha pode ser arremessada.",
    "Machado anão":"A arma preferida de onze entre dez guerreiros anões. Um machado anão é muito grande para ser usado com uma só mão sem treinamento especial; por isso é uma arma exótica. Ele pode ser usado como uma arma marcial de duas mãos.",
    "Machado de batalha":"Adaptado do machado de lenhador, este não é um instrumento para corte de árvores, mas sim uma arma capaz de causar ferimentos terríveis.",
    "Machado de guerra":"Este imenso machado de lâmina dupla é uma arma extremamente perigosa.",
    "Machado táurico":"Uma haste comprida com uma lâmina extremamente grossa na ponta, esta é uma arma ancestral dos minotauros. Um machado táurico é uma arma desbalanceada. Além disso, é muito grande para ser usado sem treinamento especial; por isso, é uma arma exótica.",
    "Mangual":"Uma haste metálica ligada a uma corrente com uma esfera de aço na ponta, que pode se enroscar na arma do adversário. O mangual é uma arma versátil, fornecendo +2 em testes para desarmar.",
    "Marreta":"Uma haste de madeira resistente com uma pesada cabeça de metal ou pedra.",
    "Martelo de guerra":"Outra ferramenta adaptada para combate, esta é a arma favorita de quase todos os anões que não usam machados.",
    "Montante":"Enorme e pesada, esta espada de 1,5m de comprimento é uma arma poderosa.",
    "Mosquete":"Uma arma de fogo de uso difícil, mas com poder devastador. Recarregar um mosquete é uma ação padrão.",
    "Picareta":"Usada por mineradores, esta ferramenta quebra pedras com facilidade. Imagine o que pode fazer com carne e osso!",
    "Pique":"Essencialmente uma lança muito longa. O pique é uma arma alongada.",
    "Pistola":"A arma de fogo mais comum. Recarregar uma pistola é uma ação padrão.",
    "Rede":"A rede tem pequenos dentes em sua trama e uma corda para controlar os inimigos presos. Se você acertar um ataque com a rede, não causa dano. Em vez disso, a vítima fica enredada (deslocamento reduzido à metade, não pode correr nem fazer investidas e sofre -2 na Defesa e em testes de ataque). Enquanto você estiver segurando a corda, sempre que a vítima se mover você pode fazer um teste de Força oposto contra ela como uma reação. Se você vencer, a vítima só pode se mover até o limite da corda (alcance curto). A vítima pode se soltar com uma ação completa e um teste de Força ou Acrobacia (CD 20). A rede tem 5 pontos de vida e, se rasgar, qualquer criatura enredada se solta automaticamente. A rede só pode ser usada contra criaturas no máximo uma categoria de tamanho maior que você.",
    "Tacape":"Versão maior e/ou com pregos de uma clava. Usado por bárbaros e humanoides bestiais, não é uma arma elegante, mas faz o serviço.",
    "Tridente":"Uma lança com três pontas, favorita de povos marinhos e gladiadores e própria para prender as pernas do oponente. O tridente é uma arma versátil, fornecendo +2 em testes para derrubar. Um tridente pode ser arremessado."
  };
  const armorDescriptions={
    "Armadura acolchoada":"Uma túnica almofadada feita em linho ou lã. É a armadura mais leve, mas protege todo o corpo, fornecendo +2 em Fortitude.",
    "Armadura completa":"A mais forte e pesada das armaduras, formada por placas de metal forjadas e encaixadas de modo a cobrir o corpo inteiro. Inclui uma túnica acolchoada para ser usada sob as placas. Correias e fivelas distribuem o peso da armadura pelo corpo inteiro. Esta armadura precisa ser feita sob medida para cada usuário; um ferreiro cobra T$ 200 para adaptar uma armadura completa a um novo usuário.",
    "Armadura de couro":"O peitoral desta armadura é feito de couro curtido em óleo fervente, para ficar mais rígido, enquanto as demais partes são feitas de couro flexível.",
    "Brunea":"Colete de couro coberto com plaquetas de metal sobrepostas, como escamas de um peixe. Por ser barata de produzir, é a armadura mais utilizada no Reinado por soldados de infantaria e guardas de castelo.",
    "Cota de malha":"Longa veste de anéis metálicos interligados, formando uma malha flexível e resistente, que vai até os joelhos.",
    "Couraça":"A mais robusta das armaduras leves, formada por uma placa metálica que protege o peito e as costas, presa sobre um casaco de couro.",
    "Couro batido":"Versão mais pesada da armadura de couro, reforçada com rebites de metal.",
    "Escudo leve":"Tipicamente feito de madeira, este escudo é amarrado no antebraço, deixando a mão livre. Você pode carregar um objeto na mão que empunha o escudo, mas não manusear uma arma.",
    "Escudo pesado":"Normalmente feito de aço, este escudo é preso ao antebraço e também deve ser empunhado com firmeza, impedindo o usuário de usar aquela mão.",
    "Gibão de peles":"Usada principalmente por bárbaros e selvagens, esta armadura é formada por várias camadas de peles e couro de animais.",
    "Loriga segmentada":"Composta por tiras horizontais de metal, esta armadura pesada é muito utilizada por legionários do Império de Tauron.",
    "Meia armadura":"Uma cota de malha reforçada com placas de metal."
  };
  const describedNotes=(rules,description)=>description?`${rules}\n\n${description}`:rules;
  const entry=(name,category,price,spaces,notes="")=>({name,category:normalizeCategory(category),price,spaces,source,notes});
  const weapon=(name,category,price,spaces,damage,critical,range,type,extra="")=>{
    const details=[`Dano ${damage}`,`crítico ${critical}`];
    if(range) details.push(`alcance ${range}`);
    if(type) details.push(`tipo ${type}`);
    if(extra) details.push(extra);
    return entry(name,weaponCategory(category),price,spaces,describedNotes(details.join("; ")+".",weaponDescriptions[name]));
  };
  const armor=(name,category,price,defense,penalty,spaces)=>{
    return entry(name,category,price,spaces,describedNotes(`Defesa ${defense}; penalidade de armadura ${penalty}.`,armorDescriptions[name]));
  };

  const catalog=[
    weapon("Adaga","simples leve","T$ 2",1,"1d4","19","curto","perfuração"),
    weapon("Espada curta","simples leve","T$ 10",1,"1d6","19","","perfuração"),
    weapon("Foice","simples leve","T$ 4",1,"1d6","x3","","corte"),
    weapon("Clava","simples uma mão","T$ 0",1,"1d6","x2","","impacto"),
    weapon("Lança","simples uma mão","T$ 2",1,"1d6","x2","curto","perfuração"),
    weapon("Maça","simples uma mão","T$ 12",1,"1d8","x2","","impacto"),
    weapon("Bordão","simples duas mãos","T$ 0",2,"1d6/1d6","x2","","impacto"),
    weapon("Pique","simples duas mãos","T$ 2",2,"1d8","x2","","perfuração"),
    weapon("Tacape","simples duas mãos","T$ 0",2,"1d10","x2","","impacto"),
    weapon("Azagaia","simples à distância","T$ 1",1,"1d6","x2","médio","perfuração"),
    weapon("Besta leve","simples à distância","T$ 35",1,"1d8","19","médio","perfuração"),
    weapon("Funda","simples à distância","T$ 0",1,"1d4","x2","médio","impacto"),
    weapon("Arco curto","simples à distância","T$ 30",2,"1d6","x3","médio","perfuração"),
    weapon("Machadinha","marcial leve","T$ 6",1,"1d6","x3","curto","corte"),
    weapon("Cimitarra","marcial leve","T$ 15",1,"1d6","18","","corte"),
    weapon("Espada longa","marcial uma mão","T$ 15",1,"1d8","19","","corte"),
    weapon("Florete","marcial uma mão","T$ 20",1,"1d6","18","","perfuração"),
    weapon("Machado de batalha","marcial uma mão","T$ 10",1,"1d8","x3","","corte"),
    weapon("Mangual","marcial uma mão","T$ 8",1,"1d8","x2","","impacto"),
    weapon("Martelo de guerra","marcial uma mão","T$ 12",1,"1d8","x3","","impacto"),
    weapon("Picareta","marcial uma mão","T$ 8",1,"1d6","x4","","perfuração"),
    weapon("Tridente","marcial uma mão","T$ 15",1,"1d8","x2","curto","perfuração"),
    weapon("Alabarda","marcial duas mãos","T$ 10",2,"1d10","x3","","corte/perfuração"),
    weapon("Alfange","marcial duas mãos","T$ 75",2,"2d4","18","","corte"),
    weapon("Gadanho","marcial duas mãos","T$ 18",2,"2d4","x4","","corte"),
    weapon("Lança montada","marcial duas mãos","T$ 10",2,"1d8","x3","","perfuração"),
    weapon("Machado de guerra","marcial duas mãos","T$ 20",2,"1d12","x3","","corte"),
    weapon("Marreta","marcial duas mãos","T$ 20",2,"3d4","x2","","impacto"),
    weapon("Montante","marcial duas mãos","T$ 50",2,"2d6","19","","corte"),
    weapon("Arco longo","marcial à distância","T$ 100",2,"1d8","x3","médio","perfuração"),
    weapon("Besta pesada","marcial à distância","T$ 50",2,"1d12","19","médio","perfuração"),
    weapon("Chicote","exótica leve","T$ 2",1,"1d3","x2","","corte"),
    weapon("Espada bastarda","exótica uma mão","T$ 35",1,"1d10/1d12","19","","corte"),
    weapon("Katana","exótica uma mão","T$ 100",1,"1d8/1d10","19","","corte"),
    weapon("Machado anão","exótica uma mão","T$ 30",1,"1d10","x3","","corte"),
    weapon("Corrente de espinhos","exótica duas mãos","T$ 25",2,"2d4/2d4","19","","corte"),
    weapon("Machado táurico","exótica duas mãos","T$ 50",2,"2d8","x3","","corte"),
    weapon("Rede","exótica à distância","T$ 20",1,"—","—","curto","—"),
    weapon("Pistola","arma de fogo","T$ 250",1,"2d6","19/x3","curto","perfuração"),
    weapon("Mosquete","arma de fogo","T$ 500",2,"2d8","19/x3","médio","perfuração"),

    entry("Balas (20)","Munição","T$ 20",1,"Munição para pistolas e mosquetes."),
    entry("Flechas (20)","Munição","T$ 1",1,"Munição para arcos."),
    entry("Pedras (20)","Munição","T$ 0,5",1,"Munição para funda."),
    entry("Virotes (20)","Munição","T$ 2",1,"Munição para bestas."),

    armor("Armadura acolchoada","Armadura leve","T$ 5","+1",0,2),
    armor("Armadura de couro","Armadura leve","T$ 20","+2",0,2),
    armor("Couro batido","Armadura leve","T$ 35","+3",1,2),
    armor("Gibão de peles","Armadura leve","T$ 25","+4",3,2),
    armor("Couraça","Armadura leve","T$ 500","+5",4,2),
    armor("Brunea","Armadura pesada","T$ 50","+5",2,5),
    armor("Cota de malha","Armadura pesada","T$ 150","+6",2,5),
    armor("Loriga segmentada","Armadura pesada","T$ 250","+7",3,5),
    armor("Meia armadura","Armadura pesada","T$ 600","+8",4,5),
    armor("Armadura completa","Armadura pesada","T$ 3.000","+10",5,5),
    armor("Escudo leve","Escudo","T$ 5","+1",1,1),
    armor("Escudo pesado","Escudo","T$ 15","+2",2,2),

    entry("Água benta","Equipamento de aventura","T$ 10",0.5,"Ação padrão contra morto-vivo ou abissal em alcance curto: 2d10 luz; Reflexos CD Sab reduz à metade."),
    entry("Algemas","Equipamento de aventura","T$ 15",1,"Prende criaturas Médias. Pode impor -5 em testes com as mãos e impedir conjuração; escapar exige ação completa e Acrobacia CD 30 ou Força CD 25."),
    entry("Arpéu","Equipamento de aventura","T$ 5",1,"Gancho com corda. Fixar exige Pontaria CD 15; subir com a corda fornece +5 em Atletismo."),
    entry("Bandoleira de poções","Equipamento de aventura","T$ 20",1,"Enquanto vestida, permite sacar itens alquímicos e poções como ação livre."),
    entry("Barraca","Equipamento de aventura","T$ 10",1,"Conta como saco de dormir para duas pessoas e fornece +2 em Sobrevivência para acampar."),
    entry("Corda","Equipamento de aventura","T$ 1",1,"Rolo de 10m. Ajuda em descidas e escaladas (+5 em Atletismo); nó especial exige Destreza CD 15."),
    entry("Espelho","Equipamento de aventura","T$ 10",1,"Pequeno espelho útil para observar cantos, fazer sinais de luz e outras soluções criativas."),
    entry("Lampião","Equipamento de aventura","T$ 7",1,"Ação padrão para acender; ilumina 15m. Carregar com óleo é ação padrão e dura uma cena."),
    entry("Mochila","Equipamento de aventura","T$ 2",0,"Bolsa de lona com tiras para carregar nas costas. Não conta como item vestido."),
    entry("Mochila de aventureiro","Equipamento de aventura","T$ 50",0,"Mochila reforçada cheia de bolsos. Aumenta sua capacidade de carga em 2 espaços e não ocupa espaço."),
    entry("Óleo","Equipamento de aventura","T$ 0,1",0.5,"Combustível para lampião. Arremessado em alcance curto, faz o alvo sofrer +1d6 dano se tomar fogo até seu próximo turno e ficar em chamas."),
    entry("Organizador de pergaminhos","Equipamento de aventura","T$ 25",1,"Estojo rígido. Enquanto vestido, permite sacar pergaminhos como ação livre."),
    entry("Pé de cabra","Equipamento de aventura","T$ 2",1,"Fornece +5 em testes de Força para abrir portas, janelas e baús. Pode ser usado como clava."),
    entry("Saco de dormir","Equipamento de aventura","T$ 1",1,"Colchão e coberta enroláveis; ajuda a evitar a perda de recuperação por dormir ao relento sem preparo."),
    entry("Símbolo sagrado","Equipamento de aventura","T$ 5",1,"Se vestido ou empunhado por devoto da divindade correspondente, concede +1 em testes de resistência."),
    entry("Tocha","Equipamento de aventura","T$ 0,1",1,"Ação padrão para acender; ilumina 9m e dura uma cena. Pode ser arma simples leve: 1d4 impacto +1 fogo, crítico x2."),
    entry("Vara de madeira (3m)","Equipamento de aventura","T$ 0,2",1,"Haste de 3m útil para alcançar ou testar pontos distantes, mas frágil demais para servir como arma."),

    entry("Alaúde élfico","Ferramenta","T$ 300",1,"Instrumento musical. Enquanto empunhado, permite usar Inspiração como ação de movimento."),
    entry("Coleção de livros","Ferramenta","T$ 75",1,"Coleção sobre um assunto. Fornece +1 em Conhecimento, Guerra, Misticismo, Nobreza ou Religião, escolhido na compra/fabricação."),
    entry("Equipamento de viagem","Ferramenta","T$ 10",1,"Conjunto para sobreviver nos ermos. Sem ele, sofre -5 em Sobrevivência para fazer acampamento."),
    entry("Estojo de disfarces","Ferramenta","T$ 50",1,"Cosméticos, tintas e próteses simples. Sem ele, sofre -5 em Enganação para disfarce."),
    entry("Flauta mística","Ferramenta","T$ 150",1,"Instrumento musical. Bardo que empunhe este item aumenta em +1 a CD para resistir às magias que lança."),
    entry("Gazua","Ferramenta","T$ 5",1,"Ferramenta para fechaduras. Sem ela, sofre -5 em Ladinagem para abrir fechaduras."),
    entry("Instrumentos de ofício","Ferramenta","T$ 30",1,"Kit de uma perícia de Ofício específica. Sem os instrumentos adequados, sofre -5 nessa perícia."),
    entry("Instrumento musical","Ferramenta","T$ 35",1,"Usado com duas mãos para benefícios e Músicas de Bardo. Bardos podem usá-lo como esotérico."),
    entry("Luneta","Ferramenta","T$ 100",1,"Fornece +5 em Percepção para observar coisas em alcance longo ou além."),
    entry("Maleta de medicamentos","Ferramenta","T$ 50",1,"Ervas, bandagens e materiais médicos. Sem ela, sofre -5 em Cura."),
    entry("Sela","Ferramenta","T$ 20",1,"Montaria sem sela impõe -5 em Cavalgar. Usada no animal, não ocupa espaço de carga do personagem."),
    entry("Tambor das profundezas","Ferramenta","T$ 80",1,"Instrumento musical. Enquanto empunhado, dobra o alcance de Inspiração e de qualquer Música de Bardo."),

    entry("Andrajos de aldeão","Vestuário","T$ 1",1,"+2 em Investigação para interrogar e +2 na CD de Aparência Inofensiva; -2 em perícias de Carisma contra quem se importa com status."),
    entry("Bandana","Vestuário","T$ 5",1,"Lenço de bandidos e piratas. Fornece +1 em Intimidação."),
    entry("Botas reforçadas","Vestuário","T$ 20",1,"Se seu deslocamento for reduzido por terreno difícil, aumenta o resultado final em +1,5m."),
    entry("Camisa bufante","Vestuário","T$ 25",1,"Blusa colorida de mangas e golas chamativas. Fornece +1 em Atuação."),
    entry("Capa esvoaçante","Vestuário","T$ 25",1,"Capa dramática e chamativa. Fornece +1 em Enganação."),
    entry("Capa pesada","Vestuário","T$ 15",1,"Capa grossa e resistente. Fornece +1 em Fortitude."),
    entry("Casaco longo","Vestuário","T$ 20",1,"Fornece +5 em Fortitude contra frio, mas impõe penalidade de armadura -2."),
    entry("Chapéu arcano","Vestuário","T$ 50",1,"Fornece +1 PM, mas apenas para personagens com Caminho do Arcanista."),
    entry("Enfeite de elmo","Vestuário","T$ 15",1,"Adorno chamativo para elmo. Fornece resistência a medo +2."),
    entry("Farrapos de ermitão","Vestuário","T$ 1",1,"Fornece +2 em Adestramento; impõe -2 em Diplomacia e em Investigação para interrogar."),
    entry("Gorro de ervas","Vestuário","T$ 75",1,"Chapéu com ervas preparadas para concentração. Fornece +1 em Vontade."),
    entry("Luva de pelica","Vestuário","T$ 5",1,"Luvas delicadas que preservam o tato. Fornecem +1 em Ladinagem."),
    entry("Manopla","Vestuário","T$ 10",1,"Torna ataques desarmados letais e conta como arma para receber melhorias e encantos desses ataques."),
    entry("Manto camuflado","Vestuário","T$ 12",1,"Feito para um terreno específico; no terreno correto, fornece +2 em Furtividade."),
    entry("Manto eclesiástico","Vestuário","T$ 20",1,"Manto típico de igrejas e templos. Fornece +1 em Religião."),
    entry("Robe místico","Vestuário","T$ 50",1,"Manto com temas arcanos. Fornece +1 em Misticismo."),
    entry("Sapatos de camurça","Vestuário","T$ 8",1,"Calçados leves que melhoram equilíbrio e firmeza. Fornecem +1 em Acrobacia."),
    entry("Tabardo","Vestuário","T$ 10",1,"Peça com heráldica de reino, igreja ou ordem. Fornece +1 em Diplomacia."),
    entry("Traje da corte","Vestuário","T$ 100",1,"Roupa luxuosa adequada à nobreza. Em certos ambientes, não vesti-la impõe -5 em perícias de Carisma."),
    entry("Traje de viajante","Vestuário","T$ 10",0,"Roupa padrão de aventureiros, com botas, cinto, camisa e capa com capuz."),
    entry("Veste de seda","Vestuário","T$ 25",1,"Roupa leve e elegante que deixa os movimentos livres. Fornece +1 em Reflexos."),

    entry("Bolsa de pó","Esotérico","T$ 300",1,"Ao lançar magia de encantamento ou ilusão, recebe +2 PM para gastar em aprimoramentos."),
    entry("Cajado arcano","Esotérico","T$ 1.000",2,"Aumenta em +1 o limite de PM e a CD de magias arcanas. Exige duas mãos e pode ser usado como bordão."),
    entry("Cetro elemental","Esotérico","T$ 750",1,"Escolha ácido, eletricidade, fogo ou frio. Magias desse tipo causam +1 dado do mesmo tipo."),
    entry("Costela de lich","Esotérico","T$ 300",1,"Magias causam +1d6 trevas. Enquanto empunhado, você não recupera PV por cura mágica."),
    entry("Dedo de ente","Esotérico","T$ 200",1,"Ao gastar pelo menos 1 PM para lançar uma magia, role 1d4; com 4, recupera 1 PM."),
    entry("Luva de ferro","Esotérico","T$ 150",1,"Magias arcanas pessoais que dão bônus em Defesa ou resistências têm esse bônus aumentado em +1."),
    entry("Medalhão de prata","Esotérico","T$ 750",1,"Reduz em -1 PM o custo de magias de alcance pessoal."),
    entry("Orbe cristalino","Esotérico","T$ 750",1,"Aumenta em +1 o limite de PM que você pode gastar em magias arcanas."),
    entry("Tomo hermético","Esotérico","T$ 1.500",1,"Escolha uma escola de magia. A CD para resistir a suas magias arcanas dessa escola aumenta em +2."),
    entry("Varinha arcana","Esotérico","T$ 100",1,"Aumenta em +1 a CD para resistir às suas magias arcanas."),

    entry("Ácido","Alquímico - preparado","T$ 10",0.5,"Ação padrão contra criatura em alcance curto: 2d4 ácido; Reflexos CD Des reduz à metade."),
    entry("Bálsamo restaurador","Alquímico - preparado","T$ 10",0.5,"Ação completa para aplicar; recupera 2d4 PV."),
    entry("Bomba","Alquímico - preparado","T$ 50",0.5,"Acender é ação de movimento e arremessar é ação padrão. Área de 3m em alcance curto sofre 6d6 impacto; Reflexos CD Des reduz."),
    entry("Cosmético","Alquímico - preparado","T$ 30",0.5,"Ação completa para usar; concede +2 em perícias baseadas em Carisma até o fim da cena."),
    entry("Elixir do amor","Alquímico - preparado","T$ 100",0.5,"Humanoide que beber fica enfeitiçado pela primeira criatura que enxergar; Vontade CD Car anula; dura 1d3 dias."),
    entry("Essência de mana","Alquímico - preparado","T$ 50",0.5,"Ação padrão para beber; recupera 1d4 PM."),
    entry("Fogo alquímico","Alquímico - preparado","T$ 10",0.5,"Ação padrão contra criatura em alcance curto: 1d6 fogo e fica em chamas; Reflexos CD Des reduz e evita as chamas."),
    entry("Pó do desaparecimento","Alquímico - preparado","T$ 100",0.5,"Criatura ou objeto coberto pelo pó fica invisível por 2d6 rodadas."),

    entry("Baga-de-fogo","Alquímico - catalisador","T$ 30",0.5,"Catalisador: adiciona +1d6 dano de fogo a magias."),
    entry("Dente-de-dragão","Alquímico - catalisador","T$ 45",0.5,"Catalisador: aumenta o dano de magias em um dado do mesmo tipo."),
    entry("Essência abissal","Alquímico - catalisador","T$ 150",0.5,"Catalisador: aumenta os dados de dano de fogo da magia em uma categoria, até d12."),
    entry("Líquen lilás","Alquímico - catalisador","T$ 30",0.5,"Catalisador: adiciona +1d6 dano de frio a magias."),
    entry("Musgo púrpura","Alquímico - catalisador","T$ 45",0.5,"Catalisador: fornece +2 na CD de magias de ilusão."),
    entry("Ossos de monstro","Alquímico - catalisador","T$ 45",0.5,"Catalisador: fornece +2 na CD de magias de necromancia."),
    entry("Pó de cristal","Alquímico - catalisador","T$ 30",0.5,"Catalisador: reduz em -1 PM o custo de magias de encantamento."),
    entry("Pó de giz","Alquímico - catalisador","T$ 30",0.5,"Catalisador: reduz em -1 PM o custo de magias de convocação."),
    entry("Ramo verdejante","Alquímico - catalisador","T$ 45",0.5,"Catalisador: magias de cura recuperam +1 PV por dado."),
    entry("Saco de sal","Alquímico - catalisador","T$ 45",0.5,"Catalisador: fornece +2 na CD de magias de abjuração."),
    entry("Seixo de âmbar","Alquímico - catalisador","T$ 30",0.5,"Catalisador: reduz em -1 PM o custo de magias de transmutação."),
    entry("Terra de cemitério","Alquímico - catalisador","T$ 30",0.5,"Catalisador: adiciona +1d6 dano de trevas a magias."),

    entry("Beladona","Veneno","T$ 1.500",0.5,"Ingestão: vítima fica paralisada por 3 rodadas; se passar, fica lenta. CD de fabricação e resistência +5."),
    entry("Bruma sonolenta","Veneno","T$ 150",0.5,"Inalação: vítima fica inconsciente; se passar, fica enjoada por 1 rodada."),
    entry("Cicuta","Veneno","T$ 60",0.5,"Ingestão: perde 1d12 PV por rodada durante 3 rodadas; se passar, perde 1d12 PV."),
    entry("Essência de sombra","Veneno","T$ 100",0.5,"Contato: vítima fica debilitada; se passar, fica fraca."),
    entry("Névoa tóxica","Veneno","T$ 30",0.5,"Inalação: perde 1d12 PV por rodada durante 3 rodadas; se passar, perde 1d12 PV."),
    entry("Peçonha comum","Veneno","T$ 15",0.5,"Contato: vítima perde 1d12 PV."),
    entry("Peçonha concentrada","Veneno","T$ 90",0.5,"Contato: perde 1d12 PV por rodada durante 3 rodadas; se passar, perde 1d12 PV."),
    entry("Peçonha potente","Veneno","T$ 600",0.5,"Contato: perde 2d12 PV por rodada durante 3 rodadas; se passar, perde 2d12 PV."),
    entry("Pó de lich","Veneno","T$ 3.000",0.5,"Ingestão: perde 4d12 PV por rodada durante 5 rodadas; se passar, perde 4d12 PV. CD de fabricação e resistência +5."),
    entry("Riso de Nimb","Veneno","T$ 150",0.5,"Inalação: vítima fica confusa; se passar, fica lenta por 1 rodada."),

    entry("Batata valkariana","Alimentação","T$ 2",0.5,"Prato especial: recebe +1d6 em um teste à sua escolha realizado até o fim do dia."),
    entry("Gorad quente","Alimentação","T$ 18",0.5,"Prato especial: recebe +2 PM temporários."),
    entry("Macarrão de Yuvalin","Alimentação","T$ 6",0.5,"Prato especial: recebe +5 PV temporários."),
    entry("Prato do aventureiro","Alimentação","T$ 1",0.5,"Prato especial: na próxima noite de sono, sua recuperação de PV aumenta em +1 por nível."),
    entry("Ração de viagem (por dia)","Alimentação","T$ 0,5",0.5,"Alimenta uma pessoa por um dia. Dura bastante se mantida seca; molhada, estraga em 24 horas."),
    entry("Refeição comum","Alimentação","T$ 0,3",0.5,"Refeição típica com pão, queijo, cozido e bebida simples."),
    entry("Sopa de peixe","Alimentação","T$ 1",0.5,"Prato especial: na próxima noite de sono, sua recuperação de PM aumenta em +1 por nível."),

    entry("Alforje","Animal","T$ 30",0,"Sacos presos à sela; permitem que uma montaria carregue até 10 espaços de itens para você."),
    entry("Cão de caça","Animal","T$ 150",0,"Pode ser parceiro perseguidor para personagens treinados em Adestramento ou montaria para criaturas Pequenas/Minúsculas."),
    entry("Cavalo","Animal","T$ 75",0,"Montaria comum. Sem treinamento, exige Cavalgar CD 20 por rodada para permanecer montado em combate."),
    entry("Cavalo de guerra","Animal","T$ 400",0,"Montaria treinada para combate; dispensa o teste de Cavalgar exigido por cavalos comuns em combate."),
    entry("Estábulo (por dia)","Animal","T$ 0,1",0,"Inclui abrigo e alimentação para o animal por um dia."),
    entry("Pônei","Animal","T$ 5",0,"Montaria comum para raças Pequenas. Sem treinamento, exige Cavalgar CD 20 por rodada em combate."),
    entry("Pônei de guerra","Animal","T$ 30",0,"Pônei treinado para combate; dispensa o teste de Cavalgar exigido por pôneis comuns em combate."),
    entry("Trobo","Animal","T$ 60",0,"Ave grande e dócil usada como animal de carga, tração ou montaria."),

    entry("Balão goblin","Veículo","T$ 200",0,"Veículo Enorme com voo 12m, Defesa 5 + Des do baloeiro e 100 PV; carrega 8 criaturas Médias ou 160 espaços."),
    entry("Carroca","Veículo","T$ 150",0,"Veículo Grande com deslocamento 9m, Defesa 8 + Des do condutor e 50 PV; carrega 4 criaturas Médias ou 80 espaços."),
    entry("Carruagem","Veículo","T$ 500",0,"Como carroça, mas transporta passageiros em cabine fechada e fornece cobertura leve."),
    entry("Canoa","Veículo","T$ 70",0,"Embarcação simples com estatísticas de carroça, mas deslocamento de natação."),
    entry("Veleiro","Veículo","T$ 10.000",0,"Navio de três mastros típico para viagens e comércio marítimo."),

    entry("Estadia comum","Serviço","T$ 0,5",0,"Noite em salão comunal com refeição simples. Recupera 1 PV e 1 PM por nível."),
    entry("Estadia confortável","Serviço","T$ 4",0,"Quarto pequeno e privado com refeição melhor. Recupera 2 PV e 2 PM por nível."),
    entry("Estadia luxuosa","Serviço","T$ 20",0,"Quarto grande e luxuoso com refeição refinada. Recupera 3 PV e 3 PM por nível."),
    entry("Condução terrestre","Serviço","T$ 0,5 por km",0,"Viagem terrestre, normalmente em carroças."),
    entry("Condução marítima","Serviço","T$ 0,1 por km",0,"Viagem marítima, normalmente em navios."),
    entry("Condução aérea","Serviço","T$ 10 por km",0,"Viagem em balão goblin; a cada 100 km há 1 chance em 20 de queda não fatal."),
    entry("Curandeiro","Serviço","T$ 5",0,"Serviço para cuidados prolongados ou tratamento contra doença ou veneno."),
    entry("Magia de 1º círculo","Serviço","T$ 10",0,"Preço para conjurador lançar uma magia de 1º círculo em situação comum e sem risco."),
    entry("Magia de 2º círculo","Serviço","T$ 90",0,"Preço para conjurador lançar uma magia de 2º círculo em situação comum e sem risco."),
    entry("Magia de 3º círculo","Serviço","T$ 360",0,"Preço para conjurador lançar uma magia de 3º círculo em situação comum e sem risco."),
    entry("Mensageiro","Serviço","T$ 0,5 por km",0,"Serviço de entrega de mensagens a pé, por cavaleiros ou por navios.")
  ];

  window.T20_ITEM_CATALOG=catalog.sort((a,b)=>a.category.localeCompare(b.category,"pt-BR")||a.name.localeCompare(b.name,"pt-BR"));
})();
