;(function(){
  const originChoice="Escolha dois benefícios entre as perícias e poderes disponíveis.";
  const jdaOrigins={
    acolito:{nome:"Acólito",fonte:"Jogo do Ano",tipo:"comum",pericias:["Cura","Religião","Vontade"],poderes:["Medicina","Membro da Igreja","Vontade de Ferro"],itens:"Símbolo sagrado, traje de sacerdote.",beneficio:originChoice},
    amigo_animais:{nome:"Amigo dos Animais",fonte:"Jogo do Ano",tipo:"comum",pericias:["Adestramento","Cavalgar"],poderes:["Amigo Especial"],itens:"Cão de caça, cavalo, pônei ou trobo à sua escolha.",beneficio:originChoice},
    amnesico:{nome:"Amnésico",fonte:"Jogo do Ano",tipo:"comum",pericias:["Uma perícia escolhida pelo mestre"],poderes:["Um poder escolhido pelo mestre","Lembranças Graduais"],itens:"Um ou mais itens, somando até T$ 500 e aprovados pelo mestre.",beneficio:"Você recebe uma perícia e um poder escolhidos pelo mestre, além de Lembranças Graduais."},
    aristocrata:{nome:"Aristocrata",fonte:"Jogo do Ano",tipo:"comum",pericias:["Diplomacia","Enganação","Nobreza"],poderes:["Comandar","Sangue Azul"],itens:"Joia de família no valor de T$ 300, traje da corte.",beneficio:originChoice},
    artesao:{nome:"Artesão",fonte:"Jogo do Ano",tipo:"comum",pericias:["Ofício","Vontade"],poderes:["Frutos do Trabalho","Sortudo"],itens:"Instrumentos de ofício e um item que você possa fabricar de até T$ 50.",beneficio:originChoice},
    artista:{nome:"Artista",fonte:"Jogo do Ano",tipo:"comum",pericias:["Atuação","Enganação"],poderes:["Atraente","Dom Artístico","Sortudo","Torcida"],itens:"Estojo de disfarces ou um instrumento musical à sua escolha.",beneficio:originChoice},
    assistente_de_laboratorio:{nome:"Assistente de Laboratório",fonte:"Jogo do Ano",tipo:"comum",pericias:["Ofício (alquimista)","Misticismo"],poderes:["Esse Cheiro...","Venefício","Um poder da Tormenta à sua escolha"],itens:"Instrumentos de Ofício (alquimista).",beneficio:originChoice},
    batedor:{nome:"Batedor",fonte:"Jogo do Ano",tipo:"comum",pericias:["Furtividade","Percepção","Sobrevivência"],poderes:["À Prova de Tudo","Estilo de Disparo","Sentidos Aguçados"],itens:"Barraca, equipamento de viagem, uma arma simples ou marcial de ataque à distância.",beneficio:originChoice},
    capanga:{nome:"Capanga",fonte:"Jogo do Ano",tipo:"comum",pericias:["Luta","Intimidação"],poderes:["Confissão","Um poder de combate à sua escolha"],itens:"Tatuagem ou adereço de sua gangue (+1 em Intimidação), uma arma simples corpo a corpo.",beneficio:originChoice},
    charlatao:{nome:"Charlatão",fonte:"Jogo do Ano",tipo:"comum",pericias:["Enganação","Jogatina"],poderes:["Alpinista Social","Aparência Inofensiva","Sortudo"],itens:"Estojo de disfarces, joia falsificada com valor aparente de T$ 100.",beneficio:originChoice},
    circense:{nome:"Circense",fonte:"Jogo do Ano",tipo:"comum",pericias:["Acrobacia","Atuação","Reflexos"],poderes:["Acrobático","Torcida","Truque de Mágica"],itens:"Três bolas coloridas para malabarismo (+1 em Atuação).",beneficio:originChoice},
    criminoso:{nome:"Criminoso",fonte:"Jogo do Ano",tipo:"comum",pericias:["Enganação","Furtividade","Ladinagem"],poderes:["Punguista","Venefício"],itens:"Estojo de disfarces ou gazua.",beneficio:originChoice},
    curandeiro:{nome:"Curandeiro",fonte:"Jogo do Ano",tipo:"comum",pericias:["Cura","Vontade"],poderes:["Medicina","Médico de Campo","Venefício"],itens:"Bálsamo restaurador x2, maleta de medicamentos.",beneficio:originChoice},
    eremita:{nome:"Eremita",fonte:"Jogo do Ano",tipo:"comum",pericias:["Misticismo","Religião","Sobrevivência"],poderes:["Busca Interior","Lobo Solitário"],itens:"Barraca, equipamento de viagem.",beneficio:originChoice},
    escravo:{nome:"Escravo",fonte:"Jogo do Ano",tipo:"comum",pericias:["Atletismo","Fortitude","Furtividade"],poderes:["Desejo de Liberdade","Vitalidade"],itens:"Algemas, uma ferramenta pesada com estatísticas de maça.",beneficio:originChoice},
    estudioso:{nome:"Estudioso",fonte:"Jogo do Ano",tipo:"comum",pericias:["Conhecimento","Guerra","Misticismo"],poderes:["Aparência Inofensiva","Palpite Fundamentado"],itens:"Coleção de livros (+1 em Conhecimento, Guerra, Misticismo ou Nobreza).",beneficio:originChoice},
    fazendeiro:{nome:"Fazendeiro",fonte:"Jogo do Ano",tipo:"comum",pericias:["Adestramento","Cavalgar","Ofício (fazendeiro)","Sobrevivência"],poderes:["Água no Feijão","Ginete"],itens:"Carroça, ferramenta agrícola, 10 rações de viagem e um animal não combativo.",beneficio:originChoice},
    forasteiro:{nome:"Forasteiro",fonte:"Jogo do Ano",tipo:"comum",pericias:["Cavalgar","Pilotagem","Sobrevivência"],poderes:["Cultura Exótica","Lobo Solitário"],itens:"Equipamento de viagem, instrumento musical exótico, traje estrangeiro.",beneficio:originChoice},
    gladiador:{nome:"Gladiador",fonte:"Jogo do Ano",tipo:"comum",pericias:["Atuação","Luta"],poderes:["Atraente","Pão e Circo","Torcida","Um poder de combate à sua escolha"],itens:"Uma arma marcial ou exótica, um item sem valor recebido de um admirador.",beneficio:originChoice},
    guarda:{nome:"Guarda",fonte:"Jogo do Ano",tipo:"comum",pericias:["Investigação","Luta","Percepção"],poderes:["Detetive","Investigador","Um poder de combate à sua escolha"],itens:"Apito, insígnia da milícia, uma arma marcial.",beneficio:originChoice},
    herdeiro:{nome:"Herdeiro",fonte:"Jogo do Ano",tipo:"comum",pericias:["Misticismo","Nobreza","Ofício"],poderes:["Comandar","Herança"],itens:"Símbolo de sua herança, como anel de sinete ou manto cerimonial.",beneficio:originChoice},
    heroi_campones:{nome:"Herói Camponês",fonte:"Jogo do Ano",tipo:"comum",pericias:["Adestramento","Ofício"],poderes:["Coração Heroico","Sortudo","Surto Heroico","Torcida"],itens:"Instrumentos de ofício ou uma arma simples, traje de plebeu.",beneficio:originChoice},
    marujo:{nome:"Marujo",fonte:"Jogo do Ano",tipo:"comum",pericias:["Atletismo","Jogatina","Pilotagem"],poderes:["Acrobático","Passagem de Navio"],itens:"T$ 2d6, corda.",beneficio:originChoice},
    mateiro:{nome:"Mateiro",fonte:"Jogo do Ano",tipo:"comum",pericias:["Atletismo","Furtividade","Sobrevivência"],poderes:["Lobo Solitário","Sentidos Aguçados","Vendedor de Carcaças"],itens:"Arco curto, barraca, equipamento de viagem, 20 flechas.",beneficio:originChoice},
    membro_de_guilda:{nome:"Membro de Guilda",fonte:"Jogo do Ano",tipo:"comum",pericias:["Diplomacia","Enganação","Misticismo","Ofício"],poderes:["Foco em Perícia","Rede de Contatos"],itens:"Gazua ou instrumentos de ofício.",beneficio:originChoice},
    mercador:{nome:"Mercador",fonte:"Jogo do Ano",tipo:"comum",pericias:["Diplomacia","Intuição","Ofício"],poderes:["Negociação","Proficiência","Sortudo"],itens:"Carroça, trobo, mercadorias para vender no valor de T$ 100.",beneficio:originChoice},
    minerador:{nome:"Minerador",fonte:"Jogo do Ano",tipo:"comum",pericias:["Atletismo","Fortitude","Ofício (minerador)"],poderes:["Ataque Poderoso","Escavador","Sentidos Aguçados"],itens:"Gemas preciosas no valor de T$ 100, picareta.",beneficio:originChoice},
    nomade:{nome:"Nômade",fonte:"Jogo do Ano",tipo:"comum",pericias:["Cavalgar","Pilotagem","Sobrevivência"],poderes:["Lobo Solitário","Mochileiro","Sentidos Aguçados"],itens:"Bordão, equipamento de viagem.",beneficio:originChoice},
    pivete:{nome:"Pivete",fonte:"Jogo do Ano",tipo:"comum",pericias:["Furtividade","Iniciativa","Ladinagem"],poderes:["Acrobático","Aparência Inofensiva","Quebra-Galho"],itens:"Gazua, traje de plebeu, um animal urbano.",beneficio:originChoice},
    refugiado:{nome:"Refugiado",fonte:"Jogo do Ano",tipo:"comum",pericias:["Fortitude","Reflexos","Vontade"],poderes:["Estoico","Vontade de Ferro"],itens:"Um item estrangeiro de até T$ 100.",beneficio:originChoice},
    seguidor:{nome:"Seguidor",fonte:"Jogo do Ano",tipo:"comum",pericias:["Adestramento","Ofício"],poderes:["Antigo Mestre","Proficiência","Surto Heroico"],itens:"Um item recebido de seu mestre de até T$ 100.",beneficio:originChoice},
    selvagem:{nome:"Selvagem",fonte:"Jogo do Ano",tipo:"comum",pericias:["Percepção","Reflexos","Sobrevivência"],poderes:["Lobo Solitário","Vida Rústica","Vitalidade"],itens:"Uma arma simples, um pequeno animal de estimação.",beneficio:originChoice},
    soldado:{nome:"Soldado",fonte:"Jogo do Ano",tipo:"comum",pericias:["Fortitude","Guerra","Luta","Pontaria"],poderes:["Influência Militar","Um poder de combate à sua escolha"],itens:"Uma arma marcial, um uniforme militar, uma insígnia de seu exército.",beneficio:originChoice},
    taverneiro:{nome:"Taverneiro",fonte:"Jogo do Ano",tipo:"comum",pericias:["Diplomacia","Jogatina","Ofício (cozinheiro)"],poderes:["Gororoba","Proficiência","Vitalidade"],itens:"Rolo de macarrão ou martelo de carne, panela, avental, caneca e pano sujo.",beneficio:originChoice},
    trabalhador:{nome:"Trabalhador",fonte:"Jogo do Ano",tipo:"comum",pericias:["Atletismo","Fortitude"],poderes:["Atlético","Esforçado"],itens:"Uma ferramenta pesada com estatísticas de maça ou lança.",beneficio:originChoice}
  };
  Object.assign(window.T20_ORIGINS, jdaOrigins);

  const originPower=(name,originIds,origins,desc,cost="",action="")=>({name,type:"Origem",subtype:"Origem",source:"Jogo do Ano",desc,cost,action,originIds,origins});
  const cleanOriginPowers=[
    originPower("À Prova de Tudo",["batedor"],["Batedor"],"Você não sofre penalidade em deslocamento e Sobrevivência por clima ruim e por terreno difícil natural."),
    originPower("Alpinista Social",["charlatao"],["Charlatão"],"Você pode substituir testes de Diplomacia por testes de Enganação."),
    originPower("Amigo Especial",["amigo_animais"],["Amigo dos Animais"],"Você recebe +5 em testes de Adestramento com animais e possui um animal de estimação parceiro que fornece +2 em uma perícia à sua escolha, exceto Luta ou Pontaria, e não conta em seu limite de parceiros."),
    originPower("Antigo Mestre",["seguidor"],["Seguidor"],"Uma vez por aventura, seu antigo mestre surge para ajudá-lo por uma cena. Ele é um parceiro mestre de um tipo à sua escolha e não conta em seu limite de aliados."),
    originPower("Água no Feijão",["fazendeiro"],["Fazendeiro"],"Você não sofre a penalidade de -5 e não gasta matéria-prima adicional para fabricar pratos para cinco pessoas."),
    originPower("Busca Interior",["eremita"],["Eremita"],"Quando você e seus companheiros estão diante de um mistério, incapazes de prosseguir, você pode gastar 1 PM para meditar sozinho e receber uma dica do mestre.","1 PM"),
    originPower("Confissão",["capanga"],["Capanga"],"Você pode usar Intimidação para interrogar sem custo e em um minuto."),
    originPower("Coração Heroico",["heroi_campones"],["Herói Camponês"],"Você recebe +3 PM. Quando atinge um novo patamar, no 5º, 11º e 17º níveis, recebe +3 PM adicionais."),
    originPower("Cultura Exótica",["forasteiro"],["Forasteiro"],"Quando faz um teste de perícia que requer treinamento, você pode gastar 1 PM para ignorar esse requerimento para esse teste.","1 PM"),
    originPower("Desejo de Liberdade",["escravo"],["Escravo"],"Você recebe +5 em testes contra a manobra agarrar e efeitos de movimento."),
    originPower("Detetive",["guarda"],["Guarda"],"Você pode gastar 1 PM para substituir testes de Percepção e Intuição por testes de Investigação até o fim da cena.","1 PM"),
    originPower("Dom Artístico",["artista"],["Artista"],"Você recebe +2 em testes de Atuação e recebe o dobro de tibares em apresentações."),
    originPower("Escavador",["minerador"],["Minerador"],"Você se torna proficiente em picaretas, causa +1 de dano com elas e não é afetado por terreno difícil em masmorras e subterrâneos."),
    originPower("Esse Cheiro...",["assistente_de_laboratorio"],["Assistente de Laboratório"],"Você recebe +2 em Fortitude e detecta automaticamente a presença, mas não a localização ou natureza, de itens alquímicos em alcance curto."),
    originPower("Esforçado",["trabalhador"],["Trabalhador"],"Você recebe +2 em todos os testes de perícias estendidos, incluindo perigos complexos."),
    originPower("Estoico",["refugiado"],["Refugiado"],"Sua condição de descanso é uma categoria acima do padrão pela situação."),
    originPower("Frutos do Trabalho",["artesao"],["Artesão"],"No início de cada aventura, você recebe até 5 itens gerais que possa fabricar num valor total de até T$ 50. Esse valor aumenta para T$ 100 no patamar veterano, T$ 300 no campeão e T$ 500 no lenda."),
    originPower("Gororoba",["taverneiro"],["Taverneiro"],"Você não sofre a penalidade de -5 para fabricar um prato especial adicional."),
    originPower("Herança",["herdeiro"],["Herdeiro"],"Você herdou um item de preço de até T$ 1.000. Você pode escolher este poder duas vezes, para um item de até T$ 2.000."),
    originPower("Influência Militar",["soldado"],["Soldado"],"Onde houver acampamentos ou bases militares, você pode conseguir hospedagem e informações para você e seus aliados."),
    originPower("Lembranças Graduais",["amnesico"],["Amnésico"],"Durante suas aventuras, em momentos a critério do mestre, você pode fazer um teste de Sabedoria (CD 10) para reconhecer pessoas, criaturas ou lugares que tenha encontrado antes de perder a memória."),
    originPower("Médico de Campo",["curandeiro"],["Curandeiro"],"Você soma sua Sabedoria aos PV restaurados por suas habilidades e itens mundanos de cura."),
    originPower("Membro da Igreja",["acolito"],["Acólito"],"Você consegue hospedagem confortável e informação em qualquer templo de sua divindade, para você e seus aliados."),
    originPower("Mochileiro",["nomade"],["Nômade"],"Seu limite de carga aumenta em 5 espaços."),
    originPower("Negociação",["mercador"],["Mercador"],"Você pode vender itens 10% mais caro, não cumulativo com barganha."),
    originPower("Palpite Fundamentado",["estudioso"],["Estudioso"],"Quando faz um teste de perícia originalmente baseada em Inteligência ou Sabedoria, você pode gastar 2 PM para substituí-la por Conhecimento.","2 PM"),
    originPower("Pão e Circo",["gladiador"],["Gladiador"],"Você pode escolher causar dano não letal sem sofrer a penalidade de -5."),
    originPower("Passagem de Navio",["marujo"],["Marujo"],"Você consegue transporte marítimo para você e seus aliados, sem custos, desde que todos paguem com trabalho durante a viagem."),
    originPower("Punguista",["criminoso"],["Criminoso"],"Você pode fazer testes de Ladinagem para sustento como Ofício, mas em apenas um dia. Se passar, recebe o dobro do dinheiro; se falhar, pode ter problemas com a lei."),
    originPower("Quebra-Galho",["pivete"],["Pivete"],"Em cidades ou metrópoles, você pode comprar qualquer item mundano não superior por metade do preço normal. Esses itens não podem ser matérias-primas e não podem ser revendidos."),
    originPower("Rede de Contatos",["membro_de_guilda"],["Membro de Guilda"],"Graças à influência de sua guilda, você pode usar Diplomacia para interrogar sem custo e em um minuto."),
    originPower("Sangue Azul",["aristocrata"],["Aristocrata"],"Você tem influência política suficiente para ser tratado com mais leniência pela guarda, conseguir uma audiência com o nobre local e favores semelhantes."),
    originPower("Truque de Mágica",["circense"],["Circense"],"Você pode lançar Explosão de Chamas, Hipnotismo e Queda Suave, mas apenas com o aprimoramento Truque. Esta não é uma habilidade mágica; os efeitos vêm de prestidigitação."),
    originPower("Vendedor de Carcaças",["mateiro"],["Mateiro"],"Você pode extrair recursos de criaturas em um minuto, em vez de uma hora, e recebe +5 no teste."),
    originPower("Vida Rústica",["selvagem"],["Selvagem"],"Você é imune a efeitos prejudiciais de itens ingeríveis e, mesmo dormindo ao relento, sua recuperação de PV e PM nunca é inferior a seu próprio nível.")
  ];

  window.T20_POWER_CATALOG=(window.T20_POWER_CATALOG||[]).filter(power=>!(power.type==="Origem" && power.source==="Jogo do Ano"));
  window.T20_POWER_CATALOG.push(...cleanOriginPowers);

  const vontadeDeFerroDesc="Você recebe +1 PM para cada dois níveis de personagem e +2 em Vontade. Pré-requisito: Sab 1.";
  window.T20_POWER_CATALOG=(window.T20_POWER_CATALOG||[]).map(power=>{
    if(power.name==="Vontade de Ferro" && power.source==="Jogo do Ano"){
      return {...power,desc:vontadeDeFerroDesc,cost:"",action:""};
    }
    return power;
  });

  const racePower=(name,races,desc,cost="",action="")=>({name,type:"Raça",source:"Jogo do Ano",desc,cost,action,races});
  const raceAbilities=[
    racePower("+1 em Três Atributos Diferentes",["Humano"],"Você recebe +1 em três atributos diferentes."),
    racePower("Versátil",["Humano"],"Você se torna treinado em duas perícias à sua escolha. Você pode trocar uma dessas perícias por um poder geral à sua escolha."),
    racePower("Constituição +2, Sabedoria +1, Destreza -1",["Anão"],"Modificadores de atributos de anão."),
    racePower("Conhecimento das Rochas",["Anão"],"Você recebe visão no escuro e +2 em Percepção e Sobrevivência realizados no subterrâneo."),
    racePower("Devagar e Sempre",["Anão"],"Seu deslocamento é 6m, mas não é reduzido por uso de armadura ou excesso de carga."),
    racePower("Duro como Pedra",["Anão"],"Você recebe +3 PV no 1º nível e +1 PV por nível seguinte."),
    racePower("Tradição de Heredrimm",["Anão"],"Para você, todos os machados, martelos, marretas e picaretas são armas simples. Você recebe +2 em ataques com essas armas."),
    racePower("Sabedoria +2, Destreza +1, Inteligência -1",["Dahllan"],"Modificadores de atributos de dahllan."),
    racePower("Amiga das Plantas",["Dahllan"],"Você pode lançar Controlar Plantas usando Sabedoria. Caso aprenda novamente essa magia, seu custo diminui em -1 PM."),
    racePower("Armadura de Allihanna",["Dahllan"],"Você pode gastar uma ação de movimento e 1 PM para transformar sua pele em casca de árvore, recebendo +2 na Defesa até o fim da cena.","1 PM","Movimento"),
    racePower("Empatia Selvagem",["Dahllan"],"Você pode se comunicar com animais por linguagem corporal e vocalizações, e usar Adestramento para mudar atitude e persuasão com animais."),
    racePower("Inteligência +2, Destreza +1, Constituição -1",["Elfo"],"Modificadores de atributos de elfo."),
    racePower("Graça de Glórienn",["Elfo"],"Seu deslocamento é 12m."),
    racePower("Sangue Mágico",["Elfo"],"Você recebe +1 PM por nível."),
    racePower("Sentidos Élficos",["Elfo"],"Você recebe visão na penumbra e +2 em Misticismo e Percepção."),
    racePower("Destreza +2, Inteligência +1, Carisma -1",["Goblin"],"Modificadores de atributos de goblin."),
    racePower("Engenhoso",["Goblin"],"Você não sofre penalidades em testes de perícia por não usar ferramentas. Se usar a ferramenta necessária, recebe +2 no teste."),
    racePower("Espelunqueiro",["Goblin"],"Você recebe visão no escuro e deslocamento de escalada igual ao seu deslocamento terrestre."),
    racePower("Peste Esguia",["Goblin"],"Seu tamanho é Pequeno, mas seu deslocamento se mantém 9m."),
    racePower("Rato das Ruas",["Goblin"],"Você recebe +2 em Fortitude e sua recuperação de PV e PM nunca é inferior ao seu nível."),
    racePower("+1 em Três Atributos Diferentes (exceto Carisma), Carisma -1",["Lefou"],"Modificadores de atributos de lefou."),
    racePower("Cria da Tormenta",["Lefou"],"Você é uma criatura do tipo monstro e recebe +5 em testes de resistência contra efeitos causados por lefeu e pela Tormenta."),
    racePower("Deformidade",["Lefou"],"Você recebe +2 em duas perícias à sua escolha. Cada bônus conta como um poder da Tormenta, exceto para perda de Carisma. Você pode trocar um desses bônus por um poder da Tormenta à sua escolha."),
    racePower("Força +2, Constituição +1, Sabedoria -1",["Minotauro"],"Modificadores de atributos de minotauro."),
    racePower("Chifres",["Minotauro"],"Você possui uma arma natural de chifres (dano 1d6, crítico x2, perfuração). Uma vez por rodada, ao usar a ação agredir com outra arma, pode gastar 1 PM para fazer um ataque extra com os chifres.","1 PM"),
    racePower("Couro Rígido",["Minotauro"],"Você recebe +1 na Defesa."),
    racePower("Faro",["Minotauro"],"Contra inimigos em alcance curto que não possa perceber, você não fica desprevenido e camuflagem total causa apenas 20% de chance de falha."),
    racePower("Medo de Altura",["Minotauro"],"Se estiver adjacente a uma queda de 3m ou mais de altura, você fica abalado."),
    racePower("Carisma +2, Inteligência +1, Sabedoria -1",["Qareen"],"Modificadores de atributos de qareen."),
    racePower("Desejos",["Qareen"],"Se lançar uma magia que alguém tenha pedido desde seu último turno, o custo da magia diminui em -1 PM. Fazer um desejo ao qareen é uma ação livre."),
    racePower("Resistência Elemental",["Qareen"],"Conforme sua ascendência, você recebe redução 10 a frio, eletricidade, fogo, ácido, luz ou trevas."),
    racePower("Tatuagem Mística",["Qareen"],"Você pode lançar uma magia de 1º círculo à sua escolha usando Carisma. Caso aprenda novamente essa magia, seu custo diminui em -1 PM."),
    racePower("Força +2, Constituição +1, Carisma -1",["Golem"],"Modificadores de atributos de golem."),
    racePower("Chassi",["Golem"],"Seu deslocamento é 6m, não é reduzido por armadura ou carga, e você recebe +2 na Defesa, mas possui penalidade de armadura -2."),
    racePower("Criatura Artificial",["Golem"],"Você é um construto, recebe visão no escuro e imunidade a cansaço, efeitos metabólicos e veneno. Não precisa respirar, alimentar-se ou dormir, mas não se beneficia de cura mundana e alimentação."),
    racePower("Fonte Elemental",["Golem"],"Escolha água, ar, fogo ou terra. Você é imune ao dano correspondente e cura PV igual à metade do dano mágico desse tipo que sofreria."),
    racePower("Propósito de Criação",["Golem"],"Você não escolhe origem, mas recebe um poder geral à sua escolha."),
    racePower("Destreza +2, Carisma +1, Força -1",["Hynne"],"Modificadores de atributos de hynne."),
    racePower("Arremessador",["Hynne"],"Quando faz um ataque à distância com uma funda ou arma de arremesso, seu dano aumenta em um passo."),
    racePower("Pequeno e Rechonchudo",["Hynne"],"Seu tamanho é Pequeno e seu deslocamento é 6m. Você recebe +2 em Enganação e pode usar Destreza em Atletismo."),
    racePower("Sorte Salvadora",["Hynne"],"Quando faz um teste de resistência, você pode gastar 1 PM para rolar o teste novamente.","1 PM"),
    racePower("Inteligência +2, Carisma +1, Força -1",["Kliren"],"Modificadores de atributos de kliren."),
    racePower("Híbrido",["Kliren"],"Você se torna treinado em uma perícia à sua escolha."),
    racePower("Engenhosidade",["Kliren"],"Quando faz um teste de perícia, você pode gastar 2 PM para somar sua Inteligência no teste. Não funciona em testes de ataque.","2 PM"),
    racePower("Ossos Frágeis",["Kliren"],"Você sofre 1 ponto de dano adicional por dado de dano de impacto."),
    racePower("Vanguardista",["Kliren"],"Você recebe proficiência em armas de fogo e +2 em um Ofício à sua escolha."),
    racePower("Destreza +2, Carisma +1",["Medusa"],"Modificadores de atributos de medusa."),
    racePower("Cria de Megalokk",["Medusa"],"Você é uma criatura do tipo monstro e recebe visão no escuro."),
    racePower("Natureza Venenosa",["Medusa"],"Você recebe resistência a veneno +5 e pode gastar uma ação de movimento e 1 PM para envenenar uma arma que esteja usando.","1 PM","Movimento"),
    racePower("Olhar Atordoante",["Medusa"],"Você pode gastar uma ação de movimento e 1 PM para forçar uma criatura em alcance curto a fazer Fortitude (CD Car). Se falhar, ela fica atordoada por uma rodada, uma vez por cena.","1 PM","Movimento"),
    racePower("+1 em Três Atributos Diferentes (exceto Constituição), Constituição -1",["Osteon"],"Modificadores de atributos de osteon."),
    racePower("Armadura Óssea",["Osteon"],"Você recebe redução de corte, frio e perfuração 5."),
    racePower("Memória Póstuma",["Osteon"],"Você se torna treinado em uma perícia ou recebe um poder geral à sua escolha. Como alternativa, pode ser osteon de outra raça humanoide não humana e ganhar uma habilidade dessa raça."),
    racePower("Natureza Esquelética",["Osteon"],"Você é morto-vivo, recebe visão no escuro e imunidade a cansaço, efeitos metabólicos, trevas e veneno. Não respira, come ou dorme; cura de luz causa dano e dano de trevas recupera PV."),
    racePower("Preço da Não Vida",["Osteon"],"Você precisa passar oito horas sob luz de estrelas ou no subterrâneo para recuperar PV e PM em descanso normal. Caso contrário, sofre efeitos de fome."),
    racePower("+1 em Três Atributos Diferentes",["Sereia/Tritão"],"Modificadores de atributos de sereia/tritão."),
    racePower("Canção dos Mares",["Sereia/Tritão"],"Você pode lançar duas magias entre Amedrontar, Comando, Despedaçar, Enfeitiçar, Hipnotismo ou Sono usando Carisma. Caso aprenda novamente uma delas, seu custo diminui em -1 PM."),
    racePower("Mestre do Tridente",["Sereia/Tritão"],"Para você, o tridente é uma arma simples. Além disso, você recebe +2 em rolagens de dano com azagaias, lanças e tridentes."),
    racePower("Transformação Anfíbia",["Sereia/Tritão"],"Você respira debaixo d'água e possui deslocamento de natação 12m com cauda. Fora d'água, a cauda desaparece e dá lugar a pernas com deslocamento 9m."),
    racePower("Carisma +2, Destreza +1, Força -2",["Sílfide"],"Modificadores de atributos de sílfide."),
    racePower("Asas de Borboleta",["Sílfide"],"Seu tamanho é Minúsculo. Você pode pairar a 1,5m do chão com deslocamento 9m, ignora terreno difícil e é imune a dano por queda. Pode gastar 1 PM por rodada para voar 12m.","1 PM/rodada"),
    racePower("Espírito da Natureza",["Sílfide"],"Você é uma criatura do tipo espírito, recebe visão na penumbra e pode falar com animais livremente."),
    racePower("Magia das Fadas",["Sílfide"],"Você pode lançar duas magias entre Criar Ilusão, Enfeitiçar, Luz e Sono usando Carisma. Caso aprenda novamente uma delas, seu custo diminui em -1 PM."),
    racePower("Sabedoria +2, Carisma +1 (aggelus) ou Destreza +2, Inteligência +1 (sulfure)",["Suraggel"],"Modificadores de atributos de suraggel."),
    racePower("Herança Divina",["Suraggel"],"Você é uma criatura do tipo espírito e recebe visão no escuro."),
    racePower("Luz Sagrada",["Aggelus"],"Como aggelus, você recebe +2 em Diplomacia e Intuição e pode lançar Luz como magia divina usando Carisma. Caso aprenda novamente essa magia, seu custo diminui em -1 PM."),
    racePower("Sombras Profanas",["Sulfure"],"Como sulfure, você recebe +2 em Enganação e Furtividade e pode lançar Escuridão como magia divina usando Inteligência. Caso aprenda novamente essa magia, seu custo diminui em -1 PM."),
    racePower("Constituição +2, Força +1, Inteligência -1",["Trog"],"Modificadores de atributos de trog."),
    racePower("Mau Cheiro",["Trog"],"Você pode gastar uma ação padrão e 2 PM para expelir gás fétido. Criaturas em alcance curto devem passar em Fortitude contra veneno (CD Con) ou ficam enjoadas por 1d6 rodadas.","2 PM","Padrão"),
    racePower("Mordida",["Trog"],"Você possui uma arma natural de mordida (dano 1d6, crítico x2, perfuração). Uma vez por rodada, ao usar a ação agredir com outra arma, pode gastar 1 PM para fazer um ataque extra com a mordida.","1 PM"),
    racePower("Reptiliano",["Trog"],"Você é uma criatura do tipo monstro, recebe visão no escuro, +1 na Defesa e, se estiver sem armadura ou roupas pesadas, +5 em Furtividade."),
    racePower("Sangue Frio",["Trog"],"Você sofre 1 ponto de dano adicional por dado de dano de frio.")
  ];
  const coreRaceKeys=new Set(raceAbilities.map(power=>`${power.name}|${power.races.join("/")}`));
  window.T20_POWER_CATALOG=window.T20_POWER_CATALOG.filter(power=>!(power.type==="Raça" && power.source==="Jogo do Ano" && coreRaceKeys.has(`${power.name}|${(power.races||[]).join("/")}`)));
  window.T20_POWER_CATALOG.push(...raceAbilities);
})();
