;(function(){
  const source="Jogo do Ano";
  const item=(name,category,price,spaces,notes="")=>({name,category,price,spaces,source,notes});
  const withRank=(rank,notes)=>`${rank}. ${notes}`;

  const catalog=[
    item("Arma mágica menor","Armas mágicas","Base + T$ 18.000",1,withRank("Menor","Modelo para uma arma com 1 encanto. Role ou escolha um encanto da Tabela 8-8.")),
    item("Arma mágica média","Armas mágicas","Base + T$ 36.000",1,withRank("Médio","Modelo para uma arma com 2 encantos. Role ou escolha encantos da Tabela 8-8.")),
    item("Arma mágica maior","Armas mágicas","Base + T$ 72.000",1,withRank("Maior","Modelo para uma arma com 3 encantos. Role ou escolha encantos da Tabela 8-8.")),
    item("Armadura ou escudo mágico menor","Armaduras e escudos mágicos","Base + T$ 18.000",2,withRank("Menor","Modelo para armadura ou escudo com 1 encanto. Role ou escolha um encanto da Tabela 8-10.")),
    item("Armadura ou escudo mágico médio","Armaduras e escudos mágicos","Base + T$ 36.000",2,withRank("Médio","Modelo para armadura ou escudo com 2 encantos. Role ou escolha encantos da Tabela 8-10.")),
    item("Armadura ou escudo mágico maior","Armaduras e escudos mágicos","Base + T$ 72.000",2,withRank("Maior","Modelo para armadura ou escudo com 3 encantos. Role ou escolha encantos da Tabela 8-10.")),

    item("Arco do poder","Armas mágicas","T$ 90.000",2,"Arco longo formidável que cria flechas de energia: normal, piedosa, explosiva ou flecha-rede."),
    item("Avalanche","Armas mágicas","T$ 140.000",2,"Machado de guerra de gelo eterno congelante formidável. Fornece redução de fogo 10 e pode invocar tempestade de gelo."),
    item("Azagaia dos relâmpagos","Armas mágicas","T$ 30.000",1,"Quando arremessada, transforma-se em Relâmpago e retorna ao usuário no fim do turno."),
    item("Besta explosiva","Armas mágicas","T$ 100.000",2,"Besta pesada formidável. Pode gastar 3 PM para transformar o disparo em Bola de Fogo."),
    item("Cajado da destruição","Itens esotéricos","T$ 60.000",2,"Bordão formidável que conta como cajado arcano. Magias de dano causam +1 ponto de dano por dado."),
    item("Cajado da vida","Itens esotéricos","T$ 60.000",2,"Bordão formidável que conta como cajado arcano para magias divinas. Magias de cura curam +2 PV por dado."),
    item("Cajado do poder","Itens esotéricos","T$ 180.000",2,"Bordão defensor magnífico que conta como cajado arcano. Reduz custo de magias arcanas em -1 PM e aumenta CD em +2."),
    item("Espada baronial","Armas mágicas","T$ 30.000",1,"Espada longa que fornece +1 em ataque e dano; o bônus aumenta com código de conduta, devoção a Khalmyr e treino em Nobreza."),
    item("Espada sortuda","Armas mágicas","T$ 110.000",1,"Espada curta formidável. Fornece +2 em testes de resistência e permite gastar 3 PM para rolar novamente um teste."),
    item("Florete fugaz","Armas mágicas","T$ 50.000",1,"Florete formidável. Ao agredir, pode gastar 1 PM; se acertar crítico no turno, faz ataque adicional contra a mesma criatura."),
    item("Lâmina da luz","Armas mágicas","T$ 45.000",1,"Espada bastarda formidável. Pode irradiar luz brilhante em alcance médio e deixar inimigos ofuscados."),
    item("Lança animalesca","Armas mágicas","T$ 45.000",1,"Lança formidável que aplica seu bônus de +2 em ataque e dano às armas naturais durante Forma Selvagem."),
    item("Língua do deserto","Armas mágicas","T$ 90.000",1,"Cimitarra formidável. Pode transformar a lâmina em chamas, aumentando dano em um passo e causando dano de fogo."),
    item("Maça do terror","Armas mágicas","T$ 45.000",1,"Maça formidável que permite lançar Amedrontar. Se já conhecer a magia, reduz o custo em -1 PM."),
    item("Machado silvestre","Armas mágicas","T$ 70.000",1,"Machado de batalha formidável. Em ermos ao ar livre, causa +1d8 de dano e fornece Trespassar."),
    item("Martelo de Doherimm","Armas mágicas","T$ 70.000",1,"Martelo de guerra formidável. Quando empunhado por anão, adquire arremesso e aumenta o dano."),
    item("Punhal sszzaazita","Armas mágicas","T$ 100.000",1,"Adaga assassina formidável venenosa. Pode se transformar em objeto inofensivo de tamanho similar."),
    item("Vingadora sagrada","Armas mágicas","T$ 200.000",1,"Espada longa formidável especialmente poderosa para paladinos: +5 em ataque/dano, Golpe Divino -1 PM e resistência a magia +5 para aliados próximos."),

    item("Armadura da luz","Armaduras e escudos mágicos","T$ 150.000",5,"Armadura completa banhada a ouro reforçada guardiã zelosa. Pode fornecer RD igual ao Carisma para personagens com código ou devoção positiva."),
    item("Baluarte anão","Armaduras e escudos mágicos","T$ 50.000",5,"Armadura completa reforçada defensora de adamante. Se não se deslocar no turno, a RD aumenta para 10 até o próximo turno."),
    item("Carapaça demoníaca","Armaduras e escudos mágicos","T$ 63.000",5,"Armadura completa macabra reforçada guardiã. Devotos de energia negativa causam +1d8 de trevas em ataques corpo a corpo."),
    item("Cota élfica","Armaduras e escudos mágicos","T$ 30.000",5,"Cota de malha defensora de mitral que permite aplicar Destreza na Defesa como armadura leve."),
    item("Couraça do comando","Armaduras e escudos mágicos","T$ 45.000",2,"Couraça banhada a ouro sob medida defensora. Fornece +1 em Carisma e melhora o bônus de Comandar."),
    item("Couro de monstro","Armaduras e escudos mágicos","T$ 36.000",2,"Gibão de peles defensor. Ataque Poderoso ou investida fornece +2d6 em rolagens de dano."),
    item("Escudo de Azgher","Armaduras e escudos mágicos","T$ 140.000",2,"Escudo pesado guardião em forma de sol. Pode emitir cone de luz que revela e causa dano de fogo."),
    item("Escudo do conjurador","Armaduras e escudos mágicos","T$ 45.000",1,"Escudo leve defensor que pode armazenar uma magia em uma tira interna, depois lida como pergaminho."),
    item("Escudo do eclipse","Armaduras e escudos mágicos","T$ 70.000",2,"Escudo pesado defensor. Fornece redução de trevas 10, causa +1d8 de trevas e pode lançar Escuridão."),
    item("Escudo do leão","Armaduras e escudos mágicos","T$ 50.000",2,"Escudo pesado defensor. Uma vez por rodada, pode gastar 2 PM para morder criatura adjacente automaticamente."),
    item("Escudo espinhoso","Armaduras e escudos mágicos","T$ 50.000",2,"Escudo pesado defensor que pode disparar espinho em alcance curto, acertando automaticamente."),
    item("Loriga do centurião","Armaduras e escudos mágicos","T$ 45.000",5,"Loriga segmentada defensora. Se estiver liderando criaturas, ataques corpo a corpo causam +2d6 de fogo."),
    item("Manto da noite","Armaduras e escudos mágicos","T$ 45.000",2,"Couro batido ajustado defensor sombrio. Reduz penalidades de Furtividade por movimento e ataque."),

    item("Abençoar Alimentos (óleo)","Consumíveis","T$ 30",0.5,"Poção/óleo de Abençoar Alimentos."),
    item("Área Escorregadia (granada)","Consumíveis","T$ 30",0.5,"Granada de Área Escorregadia."),
    item("Arma Mágica (óleo)","Consumíveis","T$ 30",0.5,"Óleo de Arma Mágica."),
    item("Compreensão","Consumíveis","T$ 30",0.5,"Poção de Compreensão."),
    item("Curar Ferimentos (2d8+2 PV)","Consumíveis","T$ 30",0.5,"Poção de Curar Ferimentos."),
    item("Disfarce Ilusório","Consumíveis","T$ 30",0.5,"Poção de Disfarce Ilusório."),
    item("Escuridão (óleo)","Consumíveis","T$ 30",0.5,"Óleo de Escuridão."),
    item("Luz (óleo)","Consumíveis","T$ 30",0.5,"Óleo de Luz."),
    item("Névoa (granada)","Consumíveis","T$ 30",0.5,"Granada de Névoa."),
    item("Primor Atlético","Consumíveis","T$ 30",0.5,"Poção de Primor Atlético."),
    item("Proteção Divina","Consumíveis","T$ 30",0.5,"Poção de Proteção Divina."),
    item("Resistência a Energia","Consumíveis","T$ 30",0.5,"Poção de Resistência a Energia."),
    item("Sono","Consumíveis","T$ 30",0.5,"Poção de Sono."),
    item("Suporte Ambiental","Consumíveis","T$ 30",0.5,"Poção de Suporte Ambiental."),
    item("Tranca Arcana (óleo)","Consumíveis","T$ 30",0.5,"Óleo de Tranca Arcana."),
    item("Visão Mística","Consumíveis","T$ 30",0.5,"Poção de Visão Mística."),
    item("Vitalidade Fantasma","Consumíveis","T$ 30",0.5,"Poção de Vitalidade Fantasma."),
    item("Escudo da Fé (duração cena)","Consumíveis","T$ 120",0.5,"Poção com aprimoramento para duração cena."),
    item("Alterar Tamanho","Consumíveis","T$ 270",0.5,"Poção de Alterar Tamanho."),
    item("Aparência Perfeita","Consumíveis","T$ 270",0.5,"Poção de Aparência Perfeita."),
    item("Armamento da Natureza (óleo)","Consumíveis","T$ 270",0.5,"Óleo de Armamento da Natureza."),
    item("Bola de Fogo (granada)","Consumíveis","T$ 270",0.5,"Granada de Bola de Fogo."),
    item("Camuflagem Ilusória","Consumíveis","T$ 270",0.5,"Poção de Camuflagem Ilusória."),
    item("Concentração de Combate (duração cena)","Consumíveis","T$ 270",0.5,"Poção com aprimoramento para duração cena."),
    item("Curar Ferimentos (4d8+4 PV)","Consumíveis","T$ 270",0.5,"Poção de Curar Ferimentos."),
    item("Físico Divino","Consumíveis","T$ 270",0.5,"Poção de Físico Divino."),
    item("Mente Divina","Consumíveis","T$ 270",0.5,"Poção de Mente Divina."),
    item("Metamorfose","Consumíveis","T$ 270",0.5,"Poção de Metamorfose."),
    item("Purificação","Consumíveis","T$ 270",0.5,"Poção de Purificação."),
    item("Velocidade","Consumíveis","T$ 270",0.5,"Poção de Velocidade."),
    item("Vestimenta da Fé (óleo)","Consumíveis","T$ 270",0.5,"Óleo de Vestimenta da Fé."),
    item("Voz Divina","Consumíveis","T$ 270",0.5,"Poção de Voz Divina."),
    item("Arma Mágica +3 (óleo)","Consumíveis","T$ 750",0.5,"Óleo de Arma Mágica com aprimoramento para bônus +3."),
    item("Curar Ferimentos (7d8+7 PV)","Consumíveis","T$ 1.080",0.5,"Poção de Curar Ferimentos."),
    item("Físico Divino (três atributos)","Consumíveis","T$ 1.080",0.5,"Poção com aprimoramento para três atributos."),
    item("Invisibilidade (duração cena)","Consumíveis","T$ 1.080",0.5,"Poção com aprimoramento para duração cena."),
    item("Bola de Fogo 10d6 (granada)","Consumíveis","T$ 1.470",0.5,"Granada de Bola de Fogo com aprimoramento para 10d6 de dano."),
    item("Curar Ferimentos (11d8+11 PV)","Consumíveis","T$ 3.000",0.5,"Poção de Curar Ferimentos."),
    item("Pergaminho mágico","Consumíveis","Variável",0.5,"Pergaminho com uma magia. Para ativar, leia em voz alta; exige conhecer a magia ou teste de Misticismo."),

    item("Amuleto da robustez","Acessórios","T$ 25.500",1,"Após um dia de uso, fornece +2 em Constituição."),
    item("Anel da energia","Acessórios","T$ 21.000",1,"Após um dia de uso, fornece +5 PM."),
    item("Anel da liberdade","Acessórios","T$ 60.000",1,"Mantém o usuário permanentemente sob efeito de Libertação."),
    item("Anel da proteção","Acessórios","T$ 9.000",1,"Fornece +2 na Defesa."),
    item("Anel da regeneração","Acessórios","T$ 150.000",1,"Após um dia de uso, fornece cura acelerada 5."),
    item("Anel da vitalidade","Acessórios","T$ 21.000",1,"Após um dia de uso, fornece +10 PV."),
    item("Anel de invisibilidade","Acessórios","T$ 21.000",1,"Ao colocar o anel, fica sob efeito de Invisibilidade até atacar ou lançar magia ofensiva."),
    item("Anel de telecinesia","Acessórios","T$ 10.500",1,"Permite lançar Telecinesia (CD Int). Se já conhecer a magia, reduz o custo em -1 PM."),
    item("Anel do escudo mental","Acessórios","T$ 9.000",1,"Fornece imunidade a magias de adivinhação."),
    item("Anel do sustento","Acessórios","T$ 3.000",1,"Após uma semana de uso, elimina necessidade de comer/beber e reduz o sono necessário a duas horas."),
    item("Anel refletor","Acessórios","T$ 51.000",1,"Uma vez por rodada, pode gastar PM igual ao custo de uma magia alvo para refleti-la ao conjurador."),
    item("Bainha mágica","Acessórios","T$ 3.000",1,"Acomoda qualquer arma corpo a corpo e permite lançar Arma Mágica na arma sem pagar PM."),
    item("Bola de cristal","Acessórios","T$ 10.500",1,"Olhar através dela é ação completa e gera Vidência (CD Sab)."),
    item("Botas aladas","Acessórios","T$ 15.000",1,"Pode gastar 2 PM para voar 12m por uma rodada; 1 PM por turno para manter."),
    item("Botas velozes","Acessórios","T$ 25.500",1,"Fornece +3m de deslocamento e permite lançar Velocidade em si mesmo."),
    item("Braçadeiras do arqueiro","Acessórios","T$ 21.000",1,"Fornece +2 em rolagens de dano com armas de ataque à distância."),
    item("Braceletes de bronze","Acessórios","T$ 16.500",1,"Fornece +4 na Defesa, cumulativo com outros itens mágicos, mas não com armaduras."),
    item("Braceletes de ouro","Acessórios","T$ 64.500",1,"Fornece +8 na Defesa, não cumulativo com braceletes de bronze."),
    item("Brincos da sagacidade","Acessórios","T$ 4.500",1,"Após um dia de uso, fornece +1 em Inteligência."),
    item("Brincos de Marah","Acessórios","T$ 21.000",1,"A primeira criatura que atacar você na cena deve passar em Vontade (CD Car) ou perde a ação."),
    item("Caveira maldita","Acessórios","T$ 10.500",1,"Gera efeito de Profanar, com o crânio como ponto de origem."),
    item("Chapéu do disfarce","Acessórios","T$ 6.000",1,"Permite lançar Disfarce Ilusório aprimorado para odores/sensações e +20 em Enganação para disfarces."),
    item("Cinto da força do gigante","Acessórios","T$ 25.500",1,"Após um dia de uso, fornece +2 em Força."),
    item("Cinto do campeão","Acessórios","T$ 51.000",1,"Fornece +1 em Força, Briga e melhora dano desarmado/Torcida conforme habilidades do usuário."),
    item("Colar guardião","Acessórios","T$ 51.000",1,"Fornece +5 na Defesa."),
    item("Corda da escalada","Acessórios","T$ 3.000",1,"Corda de 15m que se move e se prende por comando, suportando até seis criaturas Médias."),
    item("Coroa majestosa","Acessórios","T$ 25.500",1,"Após um dia de uso, fornece +2 em Carisma."),
    item("Elmo do teletransporte","Acessórios","T$ 30.000",1,"Permite lançar Salto Dimensional e Teletransporte apenas em si mesmo; reduz custo se já conhecer as magias."),
    item("Espelho da oposição","Acessórios","T$ 75.000",1,"Cria uma cópia hostil de uma criatura que observe seu reflexo."),
    item("Espelho do aprisionamento","Acessórios","T$ 150.000",1,"Aprisiona criaturas que se aproximam e veem o próprio reflexo, se falharem em Reflexos (CD Int)."),
    item("Estatueta animista","Acessórios","T$ 51.000",1,"Transforma-se em animal parceiro veterano até o fim da cena."),
    item("Estola da serenidade","Acessórios","T$ 25.500",1,"Após um dia de uso, fornece +2 em Sabedoria."),
    item("Faixas do pugilista","Acessórios","T$ 21.000",1,"Fornece +2 em ataques e dano com ataques desarmados."),
    item("Ferraduras da velocidade","Acessórios","T$ 3.000",1,"Fixadas em montaria, aumentam o deslocamento dela em +3m."),
    item("Flauta fantasma","Acessórios","T$ 6.000",1,"Se for treinado em Atuação, permite lançar Esculpir Sons (CD Car) sem pagar PM."),
    item("Garrafa da fumaça eterna","Acessórios","T$ 3.000",1,"Permite lançar Névoa sem pagar PM; a fumaça persiste até a garrafa ser tampada."),
    item("Gema da luminosidade","Acessórios","T$ 3.000",1,"Emite luz como tocha ou raio que pode cegar criatura em alcance curto."),
    item("Gema da telepatia","Acessórios","T$ 30.000",1,"Permite lançar Compreensão e Enfeitiçar (CD Car) sem pagar PM."),
    item("Gema elemental","Acessórios","T$ 30.000",1,"Permite lançar Conjurar Elemental sem pagar PM."),
    item("Lanterna da revelação","Acessórios","T$ 6.000",1,"Funciona como lampião e revela criaturas e objetos invisíveis no alcance."),
    item("Luvas da delicadeza","Acessórios","T$ 4.500",1,"Após um dia de uso, fornece +1 em Destreza."),
    item("Manoplas da força do ogro","Acessórios","T$ 4.500",1,"Após um dia de uso, fornece +1 em Força."),
    item("Manto da aranha","Acessórios","T$ 21.000",1,"Fornece deslocamento de escalada, +5 contra venenos, imunidade a teias e permite lançar Teia."),
    item("Manto da resistência","Acessórios","T$ 4.500",1,"Fornece +2 em testes de resistência."),
    item("Manto do fascínio","Acessórios","T$ 4.500",1,"Após um dia de uso, fornece +1 em Carisma."),
    item("Manto do morcego","Acessórios","T$ 25.500",1,"Fornece +5 em Furtividade, permite pendurar-se no teto e transformar-se em morcego em condições escuras."),
    item("Manto élfico","Acessórios","T$ 3.000",1,"Com o capuz cobrindo o rosto, fornece +5 em Furtividade."),
    item("Manual da saúde corporal","Acessórios","T$ 30.000",1,"Após leitura de uma semana, aumenta Constituição em +1 permanentemente e se torna mundano."),
    item("Manual do bom exercício","Acessórios","T$ 30.000",1,"Após leitura de uma semana, aumenta Força em +1 permanentemente e se torna mundano."),
    item("Manual dos movimentos precisos","Acessórios","T$ 30.000",1,"Após leitura de uma semana, aumenta Destreza em +1 permanentemente e se torna mundano."),
    item("Medalhão de Lena","Acessórios","T$ 30.000",1,"Uma vez por dia, quando você é reduzido a 0 PV ou menos, cura 100 PV antes que caia."),
    item("Mochila de carga","Acessórios","T$ 3.000",0,"Aumenta capacidade de carga em 10 espaços e não ocupa espaço."),
    item("Orbe das tempestades","Itens esotéricos","T$ 97.500",1,"Permite lançar Controlar o Clima e Fúria do Panteão (CD Sab); aliados adjacentes ficam sob Suporte Ambiental."),
    item("Pingente da saúde","Acessórios","T$ 9.000",1,"Após uma semana de uso, fornece imunidade a doenças e venenos."),
    item("Pingente da sensatez","Acessórios","T$ 4.500",1,"Após um dia de uso, fornece +1 em Sabedoria."),
    item("Pulseiras da celeridade","Acessórios","T$ 25.500",1,"Após um dia de uso, fornece +2 em Destreza."),
    item("Robe do arquimago","Acessórios","T$ 90.000",1,"Para conjurador arcano, fornece bônus na Defesa igual a 5 + maior círculo que pode lançar e metade disso em resistências."),
    item("Símbolo abençoado","Itens esotéricos","T$ 21.000",1,"Conta como símbolo sagrado. Para devotos do deus, reduz custo de magias divinas em -1 PM."),
    item("Tapete voador","Acessórios","T$ 60.000",1,"Fornece voo 12m, mede 3m x 3m e carrega seis criaturas Médias ou 120 espaços."),
    item("Tiara da sapiência","Acessórios","T$ 25.500",1,"Após um dia de uso, fornece +2 em Inteligência."),
    item("Tomo da compreensão","Acessórios","T$ 30.000",1,"Após leitura de uma semana, aumenta Sabedoria em +1 permanentemente e se torna mundano."),
    item("Tomo da liderança e influência","Acessórios","T$ 30.000",1,"Após leitura de uma semana, aumenta Carisma em +1 permanentemente e se torna mundano."),
    item("Tomo dos grandes pensamentos","Acessórios","T$ 30.000",1,"Após leitura de uma semana, aumenta Inteligência em +1 permanentemente e se torna mundano."),
    item("Torque do vigor","Acessórios","T$ 4.500",1,"Após um dia de uso, fornece +1 em Constituição."),
    item("Vassoura voadora","Acessórios","T$ 21.000",1,"Como tapete voador, mas carrega duas pessoas ou 40 espaços."),

    item("A Espada-Deus","Artefatos e outros","Artefato",1,"Espada longa divina, indestrutível, com dano básico 2d12 e vários encantos. Use apenas por decisão do mestre."),
    item("A Joia da Alma","Artefatos e outros","Artefato",1,"Gema indestrutível ligada à memória e poder arcano. Fornece +3 em Inteligência após um dia de uso, com riscos severos."),
    item("Baralho do Caos","Artefatos e outros","Artefato",1,"Baralho artefato que fornece +10 em Jogatina, mas revela seu poder real ao sacar cartas de efeitos extremos."),
    item("Rubis da Virtude","Artefatos e outros","Artefato",0.5,"Cada rubi pode conceder um nível em classe já possuída, além de RD 2, +1 em resistências e proteção contra adivinhação.")
  ];

  window.T20_MAGIC_ITEM_CATALOG=catalog.sort((a,b)=>a.category.localeCompare(b.category,"pt-BR")||a.name.localeCompare(b.name,"pt-BR"));
})();
