;(function(){
  const ORIGIN_SOURCES=new Set(["Heróis de Arton","Atlas de Arton"]);
  const data={};

  function add(id,{nome,fonte,tipo,regiao="",pericias=[],itens="",beneficio=""}){
    data[id]={nome,fonte,tipo,regiao,pericias,poderes:[nome],itens,beneficio};
  }
  function costFromBenefit(text){
    const costs=[...String(text||"").matchAll(/\b\d+\s*PM(?: por rodada)?/g)].map(match=>match[0]);
    return [...new Set(costs)].join(", ");
  }

  const H="Heróis de Arton";
  const A="Atlas de Arton";

  add("bacharel",{nome:"Bacharel",fonte:H,tipo:"especial",pericias:["Conhecimento","Diplomacia","Nobreza"],itens:"Tabardo com o símbolo de Khalmyr, uma coleção de livros à sua escolha.",beneficio:"Você é treinado em Conhecimento, Diplomacia e Nobreza. Uma vez por cena, pode usar Diplomacia para mudar atitude como ação livre."});
  add("herois_boticario",{nome:"Boticário",fonte:H,tipo:"especial",pericias:["Cura","Ofício (alquimista)"],itens:"Bálsamo restaurador, instrumentos de Ofício (alquimista), maleta de medicamentos.",beneficio:"Você é treinado em Cura e Ofício (alquimista). Pode fabricar poções de duas fórmulas de 1º círculo à sua escolha, como se tivesse Alquimista Iniciado."});
  add("herois_cacador_de_ratos",{nome:"Caçador de Ratos",fonte:H,tipo:"especial",pericias:["Furtividade","Investigação","Sobrevivência"],itens:"Clava, um gato parceiro perseguidor iniciante, T$ 50.",beneficio:"Você é treinado em Furtividade, Investigação e Sobrevivência, e recebe +2 em testes de perícias contra criaturas duas categorias de tamanho menores que você, mínimo Minúsculas."});
  add("herois_cao_de_briga",{nome:"Cão de Briga",fonte:H,tipo:"especial",itens:"Manoplas ou uma arma marcial.",beneficio:"Na primeira vez a cada cena em que faz a ação agredir, você pode fazer um ataque extra."});
  add("herois_carcereiro",{nome:"Carcereiro",fonte:H,tipo:"especial",itens:"Algemas, lampião, uma arma de até T$ 500 à sua escolha.",beneficio:"Você recebe +2 em testes contra efeitos mentais, Enganação, Furtividade e Intimidação."});
  add("herois_carpinteiro_de_guilda",{nome:"Carpinteiro de Guilda",fonte:H,tipo:"especial",pericias:["Ofício (artesão)"],itens:"Instrumentos de Ofício (carpinteiro), uma arma de corte à sua escolha.",beneficio:"Você é treinado em Ofício (artesão), recebe redução de corte 2 e, em suas mãos, armas de corte ignoram 5 pontos de RD."});
  add("herois_catador_da_catastrofe",{nome:"Catador da Catástrofe",fonte:H,tipo:"especial",pericias:["Fortitude","Percepção"],itens:"Dois equipamentos de aventura de até T$ 150 cada à sua escolha.",beneficio:"Você é treinado em Fortitude e Percepção. No início de cada aventura, pode fazer Percepção CD 15 + metade do nível; se passar, encontra um tesouro adequado ao seu ND."});
  add("herois_chef_hynne",{nome:"Chef Hynne",fonte:H,tipo:"especial",pericias:["Ofício (cozinheiro)"],itens:"Cutelo, instrumentos de cozinheiro aprimorados.",beneficio:"Você é treinado em Ofício (cozinheiro). Quando prepara um prato especial, seu benefício dura mais 1 dia; se tiver uso diário, pode ser usado novamente nesse dia."});
  add("herois_cirurgiao_barbeiro",{nome:"Cirurgião-Barbeiro",fonte:H,tipo:"especial",pericias:["Cura","Ofício (barbeiro)"],itens:"Dente falso, instrumentos de barbeiro, maleta de medicamentos.",beneficio:"Você é treinado em Cura e Ofício (barbeiro). Com ação completa e 2 PM, remove uma condição de uma criatura adjacente, mas ela perde 1d6 PV."});
  add("herois_citadino_abastado",{nome:"Citadino Abastado",fonte:H,tipo:"especial",pericias:["Nobreza","Ofício"],itens:"Uma arma, armadura, ferramenta ou vestuário de até T$ 500.",beneficio:"Você é treinado em Nobreza e em um Ofício à sua escolha. Em cidade grande, pode pagar T$ 10 x nível para usar por uma cena um poder de combate, destino ou de classe que cumpra os requisitos."});
  add("cocheiro",{nome:"Cocheiro",fonte:H,tipo:"especial",pericias:["Adestramento","Pilotagem"],itens:"Cavalo ou trobo, carroça.",beneficio:"Você é treinado em Adestramento e Pilotagem. Quando conduz um veículo, você e o veículo recebem +2 na Defesa e em testes de resistência."});
  add("construtor",{nome:"Construtor",fonte:H,tipo:"especial",pericias:["Fortitude","Ofício (pedreiro)"],itens:"Instrumentos de pedreiro ou uma ferramenta pesada com estatísticas de maça ou lança.",beneficio:"Você é treinado em Fortitude e Ofício (pedreiro). Pode pagar 2 PM para que você ou aliado em alcance curto ignore 5 pontos de RD de uma criatura ou objeto por uma cena."});
  add("herois_contrabandista",{nome:"Contrabandista",fonte:H,tipo:"especial",pericias:["Enganação","Ladinagem"],itens:"Uma arma de fogo ou 10 doses de venenos, com preço total de até T$ 500.",beneficio:"Você é treinado em Enganação e Ladinagem, recebe +5 em Ladinagem para ocultar itens em si mesmo ou em veículos, e sua carga aumenta em 2 espaços."});
  add("herois_coureiro",{nome:"Coureiro",fonte:H,tipo:"especial",pericias:["Fortitude","Ofício (coureiro)"],itens:"Faca de corte, instrumentos de coureiro, T$ 100 em itens alquímicos.",beneficio:"Você é treinado em Fortitude e Ofício (coureiro). Com 10 minutos e T$ 10, melhora uma armadura de couro por um dia: +1 Defesa e penalidade de armadura reduzida em 2."});
  add("herois_escriba",{nome:"Escriba",fonte:H,tipo:"especial",pericias:["Conhecimento","Ofício (escriba)"],itens:"Instrumentos de escriba, organizador de pergaminhos, uma coleção de livros.",beneficio:"Você é treinado em Conhecimento e Ofício (escriba) e recebe Lendas e Histórias. Se receber esse poder novamente, recebe +5 ao rolar novamente testes pelo efeito."});
  add("herois_espiao",{nome:"Espião",fonte:H,tipo:"especial",pericias:["Enganação","Ladinagem"],itens:"Estojo de disfarces, gazua, luneta, três doses de cosmético.",beneficio:"Você é treinado em Enganação e Ladinagem. Escolha uma perícia, exceto Luta ou Pontaria; você pode usar Carisma como atributo-chave dela."});
  add("herois_ferreiro_militar",{nome:"Ferreiro Militar",fonte:H,tipo:"especial",pericias:["Ofício (armeiro)"],itens:"Instrumentos de armeiro, martelo leve.",beneficio:"Você é treinado em Ofício (armeiro) e recebe +2 em rolagens de dano com martelos e marretas de qualquer tipo."});
  add("herois_freira",{nome:"Freira",fonte:H,tipo:"especial",pericias:["Cura"],itens:"Maleta de medicamentos, manto eclesiástico, símbolo sagrado.",beneficio:"Você é treinada em Cura. Ao ajudar, pode gastar 1 PM para aumentar o bônus em +1d4; ao usar cura, pode gastar 1 PM para aumentar em +1 dado."});
  add("herois_goradista",{nome:"Goradista",fonte:H,tipo:"especial",pericias:["Ofício (cozinheiro)"],itens:"Instrumentos de cozinheiro, T$ 36 em ingredientes para gorad quente.",beneficio:"Você é treinado em Ofício (cozinheiro). Ao preparar prato especial, pode gastar T$ 10 extras em cobertura de gorad; o prato também concede 2 PM temporários por patamar."});
  add("herois_insciente",{nome:"Insciente",fonte:H,tipo:"especial",pericias:["Sobrevivência"],itens:"Uma arma simples ou ferramenta de até T$ 100.",beneficio:"Você é treinado em Sobrevivência e recebe resistência a magia +5."});
  add("herois_interrogador",{nome:"Interrogador",fonte:H,tipo:"especial",pericias:["Intimidação","Investigação"],itens:"Um ou mais itens somando T$ 100 de antigas vítimas.",beneficio:"Você é treinado em Intimidação e Investigação e recebe +1 na margem de ameaça contra criaturas feridas."});
  add("herois_ladrao_de_tumulos",{nome:"Ladrão de Túmulos",fonte:H,tipo:"especial",pericias:["Ladinagem","Sobrevivência"],itens:"Pá com estatísticas de lança, pé de cabra.",beneficio:"Você é treinado em Ladinagem e Sobrevivência, recebe +2 na Defesa e em testes de perícia contra mortos-vivos, e redução de trevas 5; se morto-vivo, recupera +1 PV por dado de trevas."});
  add("herois_menestrel",{nome:"Menestrel",fonte:H,tipo:"especial",pericias:["Atuação"],itens:"Um instrumento musical de até T$ 35.",beneficio:"Você é treinado em Atuação e recebe um poder de Música de bardo: Balada Fascinante, Canção Assustadora ou Melodia Curativa."});
  add("herois_mensageiro",{nome:"Mensageiro",fonte:H,tipo:"especial",itens:"Cavalo com sela, mochila de aventureiro, traje de viajante.",beneficio:"Você recebe +3m em seu deslocamento e +2 em testes de resistência."});
  add("herois_naufrago",{nome:"Náufrago",fonte:H,tipo:"especial",itens:"Arco curto, 20 flechas e uma bola ou objeto simples com rosto e nome.",beneficio:"Você recebe +5 PV e +2 PM. Uma vez por cena, pode gastar 2 PM para ganhar treinamento em uma perícia, proficiência com arma/armadura/escudo ou usar uma ferramenta como outra até o fim da cena."});
  add("herois_padeiro",{nome:"Padeiro",fonte:H,tipo:"especial",pericias:["Ofício (cozinheiro)"],itens:"Instrumentos de Ofício (cozinheiro), rolo de massa com estatísticas de clava.",beneficio:"Você é treinado em Ofício (cozinheiro), recebe +1 em dano com armas de impacto e pode substituir Atletismo por Ofício (cozinheiro)."});
  add("herois_pedinte",{nome:"Pedinte",fonte:H,tipo:"especial",itens:"Andrajos, 1 bálsamo restaurador e 1 essência de mana.",beneficio:"Você recebe +2 em Enganação e Furtividade. Ao usar alimento, preparado ou poção, pode rolar efeito aleatório duas vezes e usar o melhor, ou dividir o item com aliado adjacente."});
  add("herois_pescador",{nome:"Pescador",fonte:H,tipo:"especial",pericias:["Ofício (pescador)","Sobrevivência"],itens:"Bolsa cheia de minhocas, instrumentos de pescador.",beneficio:"Você é treinado em Ofício (pescador) e Sobrevivência, recebe +2 em Iniciativa e +2 em testes para executar ações preparadas."});
  add("herois_servo",{nome:"Servo",fonte:H,tipo:"especial",pericias:["Diplomacia","Ofício (serviçal)"],itens:"Balde e vassoura com estatísticas de bordão, tabardo de seu patrono.",beneficio:"Você é treinado em Diplomacia e Ofício (serviçal), recebe +2 em Diplomacia e Enganação contra alvos de status superior e pode substituir Nobreza por Ofício (serviçal)."});
  add("herois_suporte_de_tropas",{nome:"Suporte de Tropas",fonte:H,tipo:"especial",itens:"Equipamento de viagem, instrumentos de ofício, maleta de medicamentos.",beneficio:"Sempre que ajuda, o bônus fornecido aumenta em +2. Quando flanqueia, o bônus de ataque seu e de aliados aumenta para +4."});

  add("agricultor_sambur",{nome:"Agricultor Sambur",fonte:A,tipo:"regional",regiao:"Repúblicas Livres de Sambúrdia",pericias:["Adestramento","Sobrevivência"],itens:"Ferramenta agrícola com estatísticas de lança, T$ 100.",beneficio:"Você é treinado em Adestramento e Sobrevivência. Uma vez por cena, pode gastar 1 PM para receber +1d6 em um teste de perícia."});
  add("amazona_hippion",{nome:"Amazona de Hippion",fonte:A,tipo:"regional",regiao:"Deheon, Namalkah",pericias:["Cavalgar"],itens:"Arma simples ou marcial, cavalo de guerra.",beneficio:"Você é treinada em Cavalgar e, se não estiver usando armadura pesada, soma seu Carisma aos PM, limitado pelo nível, após um dia."});
  add("amoque_purpura",{nome:"Amoque Púrpura",fonte:A,tipo:"regional",regiao:"Ermos Púrpuras",pericias:["Intimidação"],itens:"Arma simples, estandarte da sua tribo.",beneficio:"Você é treinado em Intimidação. Quando está sob Fúria, Fúria Divina ou Poder Oculto, recebe +2 em rolagens de dano."});
  add("anao_armas",{nome:"Anão de Armas",fonte:A,tipo:"regional",regiao:"Doherimm",pericias:["Ofício (armeiro)"],itens:"Arma marcial tradicional anã, instrumentos de Ofício (armeiro).",beneficio:"Você é treinado em Ofício (armeiro) e recebe +2 em dano com armas tradicionais anãs: machados, martelos, marretas e picaretas."});
  add("andarilho_ubaneri",{nome:"Andarilho Ubaneri",fonte:A,tipo:"regional",regiao:"Ubani",itens:"Escudo pesado, lança.",beneficio:"Você recebe um alikunhá, parceiro iniciante que não conta em seu limite, e proficiência com escudos. Se já for proficiente, seu escudo fornece +1 Defesa adicional."});
  add("atlas_aprendiz_de_dragoeiro",{nome:"Aprendiz de Dragoeiro",fonte:A,tipo:"regional",regiao:"Sckharshantallas",itens:"Arma simples ou marcial, troféu de caça, treckod.",beneficio:"Você recebe +2 na Defesa contra criaturas maiores e +2 em Reflexos. Se passar em Reflexos, seus ataques contra a fonte do efeito causam +1d8 dano até o fim da cena."});
  add("atlas_aprendiz_de_drogadora",{nome:"Aprendiz de Drogadora",fonte:A,tipo:"regional",regiao:"Galrasia",pericias:["Cura","Ofício (alquimista)"],itens:"Bálsamo restaurador x2, poção de curar ferimentos x2, maleta de medicamentos.",beneficio:"Você é treinada em Cura e Ofício (alquimista). Ao fabricar preparados alquímicos e poções, gasta apenas 1/4 do preço em matérias-primas."});
  add("atlas_aristocrata_dai_zenshi",{nome:"Aristocrata Dai’zenshi",fonte:A,tipo:"regional",regiao:"Tamu-ra",pericias:["Nobreza"],itens:"Traje da corte, katana superior com uma melhoria, exceto material especial.",beneficio:"Você é treinado em Nobreza. Ao descansar sem ter feito Enganação, Furtividade ou Ladinagem desde o último descanso, recebe +1 PM temporário para cada dois níveis."});
  add("atlas_armeiro_armado",{nome:"Armeiro Armado",fonte:A,tipo:"regional",regiao:"Zakharov",pericias:["Ofício (armeiro)"],itens:"Arma marcial, instrumentos de Ofício (armeiro).",beneficio:"Você é treinado em Ofício (armeiro) e pode fabricar armas com uma melhoria. Se aprender a fabricar armas superiores, gasta só 1/4 do preço das melhorias em armas."});
  add("atlas_aspirante_a_heroi",{nome:"Aspirante a Herói",fonte:A,tipo:"regional",regiao:"Deheon",itens:"Essência de mana, mochila de aventureiro.",beneficio:"Você recebe +1 em um atributo à sua escolha."});
  add("atlas_assistente_forense",{nome:"Assistente Forense",fonte:A,tipo:"regional",regiao:"Salistick",pericias:["Investigação"],itens:"Lupa, que conta como ferramenta de +1 em Investigação.",beneficio:"Você é treinado em Investigação e pode usá-la para necropsia, identificar alquímicos e rastrear. Em cena de crime, pode identificar criaturas ausentes, com penalidade por dias decorridos."});
  add("atlas_bandoleiro_da_fortaleza",{nome:"Bandoleiro da Fortaleza",fonte:A,tipo:"regional",regiao:"Khalifor",pericias:["Furtividade","Intimidação"],itens:"Adaga, gazua, manto camuflado urbano.",beneficio:"Você é treinado em Furtividade e Intimidação e recebe resistência a medo +5."});
  add("atlas_barao_arruinado",{nome:"Barão Arruinado",fonte:A,tipo:"regional",regiao:"Feudos de Trebuck",pericias:["Nobreza"],itens:"Anel de família, títulos expirados, traje da corte.",beneficio:"Você é treinado em Nobreza. Quando falha em um teste com consequência negativa, recebe +2 em testes da mesma perícia até o fim da cena."});
  add("atlas_catador_da_cidade_velha",{nome:"Catador da Cidade Velha",fonte:A,tipo:"regional",regiao:"Nova Malpetrim",pericias:["Fortitude","Percepção"],itens:"Luneta, luvas de pelica, tranqueiras resgatadas do mar.",beneficio:"Você é treinado em Fortitude e Percepção. Pode gastar 1 PM para receber deslocamento de natação igual ao básico por uma cena; se já tiver, aumenta em +3m e dobra fôlego."});
  add("atlas_cativo_das_fadas",{nome:"Cativo das Fadas",fonte:A,tipo:"regional",regiao:"Pondsmânia",itens:"Corda, ração de viagem x10, essência de mana.",beneficio:"Você recebe resistência a espíritos e magia +2 e +1 PV por nível."});
  add("atlas_competidor_do_circuito",{nome:"Competidor do Circuito",fonte:A,tipo:"regional",regiao:"Feudos de Trebuck",itens:"Arma marcial, T$ 100.",beneficio:"Você recebe o poder Torcida. Enquanto está sob efeito dele, sempre que reduz um inimigo a 0 PV com ataque corpo a corpo, recupera 1 PM."});
  add("atlas_cosmopolita",{nome:"Cosmopolita",fonte:A,tipo:"regional",regiao:"Valkaria",itens:"Equipamento de viagem, traje de viajante, item artístico cultural indefinido.",beneficio:"Escolha um poder geral ou de uma classe na qual tenha pelo menos dois níveis, cumprindo requisitos. Uma vez por aventura, após descanso, pode trocar esse poder."});
  add("atlas_cria_da_favela",{nome:"Cria da Favela",fonte:A,tipo:"regional",regiao:"Valkaria",itens:"Andrajos de aldeão, corda, vara de madeira.",beneficio:"Você recebe +1 em Constituição e, por piores que sejam as condições de descanso, sua recuperação é sempre pelo menos normal."});
  add("atlas_criado_pelas_voracis",{nome:"Criado pelas Voracis",fonte:A,tipo:"regional",regiao:"Galrasia",itens:"Arma simples, armadura leve, lança.",beneficio:"Você recebe +2 na Defesa e Sobrevivência e +3m em seu deslocamento."});
  add("atlas_de_outro_mundo",{nome:"De Outro Mundo",fonte:A,tipo:"regional",regiao:"Éter Divino",itens:"Trajes exóticos, um item de até T$ 100 do mundo natal.",beneficio:"Escolha uma magia de 1º círculo e atributo-chave para representar habilidade ou tecnologia do seu mundo. Se tecnologia, recebe item Minúsculo que lança a magia e aumenta o limite de PM dela em +2."});
  add("descendente_colleniano",{nome:"Descendente Colleniano",fonte:A,tipo:"regional",regiao:"Ahlen",itens:"Arma simples, estojo de disfarces, ração de viagem x5.",beneficio:"Você recebe +2 em Percepção e pode lançar Visão Mística. Se aprender a magia novamente, seu custo diminui em -1 PM."});
  add("desertor_supremacia",{nome:"Desertor da Supremacia",fonte:A,tipo:"regional",regiao:"Supremacia Purista",pericias:["Guerra"],itens:"Brunea com símbolo purista raspado, escudo pesado, espada bastarda, ração de viagem x10.",beneficio:"Você é treinado em Guerra e recebe proficiência com espadas bastardas e escudos. Com espada bastarda e escudo pesado, recebe +2 em ataques."});
  add("duplo_feerico",{nome:"Duplo Feérico",fonte:A,tipo:"regional",regiao:"Pondsmânia",itens:"Essência de mana, marca ou característica física da sua versão original.",beneficio:"Escolha uma habilidade de classe de 1º nível de outra classe. Você a recebe e usa como se tivesse 1 nível. Se escolher Magias, aprende uma magia e recebe +1 PM."});
  add("atlas_duyshidakk_infiltrado",{nome:"Duyshidakk Infiltrado",fonte:A,tipo:"regional",regiao:"Ruínas de Tyrondir",itens:"Arma marcial, peças sobressalentes.",beneficio:"Você recebe +2 em Furtividade e Vontade e pode usar Sabedoria como atributo-chave de Enganação."});
  add("atlas_emissario_ubaneri",{nome:"Emissário Ubaneri",fonte:A,tipo:"regional",regiao:"Ubani",itens:"Essência de mana, mochila de aventureiro.",beneficio:"Você recebe um alikunhá, parceiro iniciante que não conta em seu limite, e pode usar Sabedoria como atributo-chave de Misticismo."});
  add("atlas_escudeiro_da_luz",{nome:"Escudeiro da Luz",fonte:A,tipo:"regional",regiao:"Bielefeld",pericias:["Nobreza"],itens:"Cota de malha ou escudo pesado, enfeite de elmo com símbolo da Ordem da Luz.",beneficio:"Você é treinado em Nobreza, recebe +2 na Defesa e +3 PM."});
  add("atlas_escudeiro_solitario",{nome:"Escudeiro Solitário",fonte:A,tipo:"regional",regiao:"Bielefeld",pericias:["Enganação","Ladinagem"],itens:"Cota de malha, escudo pesado, enfeite de elmo.",beneficio:"Você é treinado em Enganação e Ladinagem, recebe +10 para se disfarçar como cavaleiro da Luz e atacar pelas costas não viola Código de Honra."});
  add("atlas_estandarte_vivo",{nome:"Estandarte Vivo",fonte:A,tipo:"regional",regiao:"Ermos Púrpuras",itens:"Arma simples ou marcial, gibão de peles, fragmento de estandarte do povo.",beneficio:"Você recebe +2 em Sobrevivência e um poder de combate ou da Tormenta à sua escolha."});
  add("atlas_estudante_da_academia",{nome:"Estudante da Academia",fonte:A,tipo:"regional",regiao:"Academia Arcana",itens:"Coleção de livros, essência de mana x2.",beneficio:"Você aprende e pode lançar uma magia arcana de 1º círculo com Inteligência. Pode fazer Misticismo sem treino; se for treinado, recebe +2 em Misticismo."});
  add("atlas_estudante_do_colegio_real",{nome:"Estudante do Colégio Real",fonte:A,tipo:"regional",regiao:"Salistick",pericias:["Cura"],itens:"Bálsamo restaurador x3, maleta de medicamentos.",beneficio:"Você é treinado em Cura. Seus efeitos de cura recuperam +2 PV por dado. Perde esse benefício se se tornar devoto."});
  add("atlas_explorador_de_ruinas",{nome:"Explorador de Ruínas",fonte:A,tipo:"regional",regiao:"Ruínas de Tyrondir",itens:"Mochila de aventureiro, tocha, vara de madeira.",beneficio:"Você recebe +2 em Ladinagem, Percepção e Reflexos e +3m em seu deslocamento."});
  add("atlas_filhote_da_revoada",{nome:"Filhote da Revoada",fonte:A,tipo:"regional",regiao:"Lamnor",pericias:["Acrobacia","Pilotagem"],itens:"Instrumentos de Ofício (artesão), T$ 100.",beneficio:"Você é treinado em Acrobacia e Pilotagem. Ao fazer teste de uma delas, pode gastar 1 PM para rolar um dado adicional e usar o melhor."});
  add("atlas_futura_lenda",{nome:"Futura Lenda",fonte:A,tipo:"regional",regiao:"Nova Malpetrim",itens:"Arma simples ou marcial com nome pomposo, essência de mana x2.",beneficio:"Escolha um poder de sua classe normalmente disponível a partir do 2º nível. Você recebe esse poder."});
  add("atlas_ginete_de_tumarkhan",{nome:"Ginete de Tumarkhân",fonte:A,tipo:"regional",regiao:"Khubar",pericias:["Cavalgar"],itens:"Bálsamo restaurador, sela.",beneficio:"Você é treinado em Cavalgar e possui parceiro tumarkhân iniciante, com +2 em Adestramento e Cavalgar. Pode usá-lo como montaria especial se receber uma."});
  add("atlas_grumete_pirata",{nome:"Grumete Pirata",fonte:A,tipo:"regional",regiao:"Três Mares",pericias:["Acrobacia","Atletismo","Reflexos"],itens:"Adaga, corda, tatuagem da antiga tripulação.",beneficio:"Você é treinado em Acrobacia, Atletismo e Reflexos. Ao se equilibrar, escalar ou nadar, só cai ou afunda se falhar por 10 ou mais."});
  add("atlas_guardiao_glacial",{nome:"Guardião Glacial",fonte:A,tipo:"regional",regiao:"Montanhas Uivantes",itens:"Casaco longo, cavalo glacial.",beneficio:"Você recebe redução de frio 5 e proficiência em arco longo e machado de batalha. Se já for proficiente, recebe +2 em dano com essas armas."});
  add("atlas_iniciado_dos_caca_monstros",{nome:"Iniciado dos Caça-Monstros",fonte:A,tipo:"regional",regiao:"Montanhas Sanguinárias",itens:"Arma simples ou marcial, gibão de peles.",beneficio:"Você pode identificar criaturas com ação de movimento. Quando acerta ataque em criatura não humanoide, pode gastar 1 PM para causar +1d8 dano."});
  add("atlas_insurgente_tapistano",{nome:"Insurgente Tapistano",fonte:A,tipo:"regional",regiao:"Império de Tauron",itens:"Amuleto da resistência, arma simples.",beneficio:"Você recebe +1 em Fortitude, Reflexos e Vontade, +3 PV no 1º nível e +1 PV por nível seguinte."});
  add("atlas_irmao_sem_esporas",{nome:"Irmão sem Esporas",fonte:A,tipo:"regional",regiao:"Namalkah",itens:"Bálsamo restaurador, sela.",beneficio:"Você possui um irmão cavalo, parceiro iniciante que fornece +1 em ataques e Reflexos. Pode usá-lo como montaria especial, acumulando benefícios."});
  add("atlas_legionario",{nome:"Legionário",fonte:A,tipo:"regional",regiao:"Império de Tauron",pericias:["Guerra"],itens:"Brunea de legião, escudo pesado, gládio, ração de viagem x10.",beneficio:"Você é treinado em Guerra e recebe proficiência com gládios e escudos. Com gládio e escudo pesado, recebe +1 margem de ameaça e +1 Defesa."});
  add("atlas_lenhador_de_tollon",{nome:"Lenhador de Tollon",fonte:A,tipo:"regional",regiao:"Floresta de Tollon",pericias:["Ofício (artesão)"],itens:"Item superior de madeira Tollon.",beneficio:"Você é treinado em Ofício (artesão), recebe +5 em testes relacionados a madeira e proficiência com machadinhas e machados de batalha; se já tiver, +2 dano."});
  add("atlas_liricista_de_lenorienn",{nome:"Liricista de Lenórienn",fonte:A,tipo:"regional",regiao:"Lamnor",pericias:["Atuação"],itens:"Alaúde élfico, réplica artística élfica.",beneficio:"Você é treinado em Atuação e recebe +2 nela. Pode usar Carisma como atributo-chave de Misticismo."});
  add("atlas_membro_do_principado",{nome:"Membro do Principado",fonte:A,tipo:"regional",regiao:"Repúblicas Livres de Sambúrdia",pericias:["Diplomacia","Intuição"],itens:"Carroça, mercadorias sortidas.",beneficio:"Você é treinado em Diplomacia e Intuição. Ao chegar em cidade pela primeira vez na aventura, Diplomacia CD 20 dá 10% de desconto em compras locais."});
  add("atlas_nitamuraniano",{nome:"Nitamuraniano",fonte:A,tipo:"regional",regiao:"Valkaria",itens:"Arco longo ou katana, camisa bufante ou traje de seda.",beneficio:"Você recebe proficiência em katana e arco longo; se receber de novo, +2 dano. Ao falhar em perícia de Sabedoria, pode gastar 2 PM para refazer o teste uma vez."});
  add("atlas_nobre_zakharoviano",{nome:"Nobre Zakharoviano",fonte:A,tipo:"regional",regiao:"Zakharov",pericias:["Ofício (armeiro)"],itens:"Traje da corte.",beneficio:"Você é treinado em Ofício (armeiro) e recebe uma arma superior com uma melhoria, exceto material especial. De posse dela após um dia, recebe +2 PM por patamar."});
  add("atlas_nomade_sar_allan",{nome:"Nômade Sar-Allan",fonte:A,tipo:"regional",regiao:"Halak-Tûr",itens:"Arma simples ou marcial, corcel do deserto ou dromedário, manto camuflado do deserto.",beneficio:"Você recebe +2 em Fortitude e Sobrevivência e +2 em dano com alfanges, arcos curtos e cimitarras."});
  add("atlas_pescador_parrudo",{nome:"Pescador Parrudo",fonte:A,tipo:"regional",regiao:"Khubar",itens:"Vara de pesca, peixes raros salgados.",beneficio:"Você recebe +2 em Atletismo, Fortitude e Sobrevivência e +3 PV. Quando passa em Atletismo para nadar, avança seu deslocamento inteiro."});
  add("atlas_plebeu_arcano",{nome:"Plebeu Arcano",fonte:A,tipo:"regional",regiao:"Wynlla",itens:"Bandoleira de poções, gorro de ervas, poção arcana de 1º círculo.",beneficio:"Você recebe +2 PM. Uma vez por rodada, quando falha em resistência contra efeito mágico, pode gastar 1 PM para rolar novamente."});
  add("atlas_prisioneiro_das_catacumbas",{nome:"Prisioneiro das Catacumbas",fonte:A,tipo:"regional",regiao:"Catacumbas de Leverick",pericias:["Percepção","Reflexos"],itens:"Arma marcial encontrada nas Catacumbas.",beneficio:"Você é treinado em Percepção e Reflexos e recebe resistência a armadilhas e efeitos de movimento +5."});
  add("atlas_procurado_vivo_ou_morto",{nome:"Procurado: Vivo ou Morto",fonte:A,tipo:"regional",regiao:"Smokestone",itens:"Pistola, balas cruéis (20).",beneficio:"Você recebe proficiência com armas de fogo. Contra quem reconhece sua fama, recebe +5 Intimidação e -5 Diplomacia."});
  add("atlas_profeta_do_akzath",{nome:"Profeta do Akzath",fonte:A,tipo:"regional",regiao:"Lamnor",pericias:["Religião"],itens:"Arma simples ou marcial, bordão, pergaminho com diagrama do Akzath.",beneficio:"Você é treinado em Religião e pode lançar magias mesmo sob Fúria Divina."});
  add("atlas_querido_filho",{nome:"Querido Filho",fonte:A,tipo:"regional",regiao:"Aslothia",itens:"Essência de sombra, manto camuflado urbano.",beneficio:"Você recebe redução de frio e trevas 5 e visão no escuro. Se já possuir visão no escuro, recebe +2 em Percepção."});
  add("atlas_rebelde_agitador",{nome:"Rebelde Agitador",fonte:A,tipo:"regional",regiao:"Sckharshantallas",pericias:["Iniciativa"],itens:"Arma simples ou marcial, panfleto revolucionário, T$ 6d12.",beneficio:"Você é treinado em Iniciativa. Uma vez por aventura, pode gastar 1 dia e fazer Diplomacia CD 10 para convencer pessoas comuns a ajudarem como parceiros iniciantes por uma cena."});
  add("atlas_receptador_das_nuvens",{nome:"Receptador das Nuvens",fonte:A,tipo:"regional",regiao:"Vectora",itens:"Mercadorias raras e variadas.",beneficio:"Em cidade ou lugar com acesso a contatos, pode gastar 1 dia para obter até 2 aparatos mágicos sem valor comercial, cada um lançando uma magia de 1º círculo com Inteligência."});
  add("atlas_recruta_arcano",{nome:"Recruta Arcano",fonte:A,tipo:"regional",regiao:"Wynlla",itens:"Essência de mana x2, varinha arcana.",beneficio:"A CD para resistir a suas magias arcanas aumenta em +1 e elas causam +1 ponto de dano."});
  add("atlas_recruta_da_fenix",{nome:"Recruta da Fênix",fonte:A,tipo:"regional",regiao:"Triunphus",pericias:["Cavalgar"],itens:"Arma marcial, brunea, grifo iniciante.",beneficio:"Você recebe +1 PV por nível, redução de fogo 5 e é treinado em Cavalgar."});
  add("atlas_sabio_matematico",{nome:"Sábio Matemático",fonte:A,tipo:"regional",regiao:"Halak-Tûr",pericias:["Conhecimento"],itens:"Coleção de livros, luneta.",beneficio:"Você é treinado em Conhecimento e aprende Concentração de Combate e Orientação. Esses efeitos não contam como magias, exceto para acúmulo, e não são mágicos."});
  add("atlas_selvagem_sanguinario",{nome:"Selvagem Sanguinário",fonte:A,tipo:"regional",regiao:"Montanhas Sanguinárias",pericias:["Sobrevivência"],itens:"Arma marcial, gibão de peles.",beneficio:"Você é treinado em Sobrevivência e, se não estiver usando armadura pesada, recebe +1 em dano com armas e RD 1."});
  add("atlas_sucateiro_de_batalhas",{nome:"Sucateiro de Batalhas",fonte:A,tipo:"regional",regiao:"Conflagração do Aço",pericias:["Guerra","Investigação"],itens:"Arma simples ou marcial, bálsamo restaurador, escudo, essência de mana, ração x5, T$ 4d6.",beneficio:"Você é treinado em Guerra e Investigação. Ao rolar tesouro por ND, pode rolar novamente uma vez para cada tipo de tesouro."});
  add("atlas_tamalu",{nome:"Tamalu",fonte:A,tipo:"regional",regiao:"Khubar",pericias:["Diplomacia","Nobreza"],itens:"Traje da corte.",beneficio:"Você é treinado em Diplomacia e Nobreza e recebe uma tatuagem mística à sua escolha."});
  add("atlas_tocado_pela_dama_altiva",{nome:"Tocado pela Dama Altiva",fonte:A,tipo:"regional",regiao:"Moreania",pericias:["Adestramento"],itens:"Bordão, ração de viagem x5.",beneficio:"Você é treinado em Adestramento. Com 1 minuto e 1 PM, convoca um animal Minúsculo para fornecer +2 em uma perícia adequada até o fim da cena."});
  add("atlas_tocado_pelo_indomavel",{nome:"Tocado pelo Indomável",fonte:A,tipo:"regional",regiao:"Moreania",pericias:["Atletismo"],itens:"Trapos surrados, carcaça de couro com estatísticas de gibão de peles.",beneficio:"Você é treinado em Atletismo e recebe +2 em dano com armas naturais e ataques desarmados."});
  add("atlas_tradicionalista_svalano",{nome:"Tradicionalista Svalano",fonte:A,tipo:"regional",regiao:"Svalas",itens:"Arma simples ou marcial, corda, mochila de aventureiro, vara de madeira.",beneficio:"Você pode usar Sabedoria como atributo-chave de Conhecimento e Nobreza e fazer testes dessas perícias sem treino. Além disso, recebe +1 em Fortitude e Vontade."});
  add("atlas_trapaceiro_ahleniense",{nome:"Trapaceiro Ahleniense",fonte:A,tipo:"regional",regiao:"Ahlen",itens:"Essência de sombra, gazua, estojo de disfarces.",beneficio:"Você recebe +2 em Enganação e Furtividade e pode usar Carisma como atributo-chave de Ladinagem."});
  add("atlas_turista_da_academia",{nome:"Turista da Academia",fonte:A,tipo:"regional",regiao:"Academia Arcana",itens:"Três pergaminhos de magias arcanas de 1º círculo à sua escolha.",beneficio:"Você recebe resistência a magia +2 e pode ativar pergaminhos de todas as magias arcanas de 1º círculo como se as conhecesse."});
  add("atlas_um_com_os_kami",{nome:"Um com os Kami",fonte:A,tipo:"regional",regiao:"Tamu-ra",itens:"Bálsamo restaurador, essência de mana.",beneficio:"Você pode usar Sabedoria como atributo-chave de Misticismo. É acompanhado por um kami parceiro especial, que permite ver e afetar criaturas incorpóreas invisíveis, e pode gastar 1 PM por rodada para manipular objeto solto em alcance curto."});

  Object.assign(window.T20_ORIGINS,data);

  const powerEntries=Object.entries(data).map(([id,o])=>({
    name:o.nome,
    type:"Origem",
    subtype:o.tipo==="regional"?"Regional":"Especial",
    source:o.fonte,
    desc:o.beneficio,
    cost:costFromBenefit(o.beneficio),
    action:"",
    originIds:[id],
    origins:[o.nome]
  }));
  window.T20_POWER_CATALOG=(window.T20_POWER_CATALOG||[]).filter(power=>!(power.type==="Origem"&&ORIGIN_SOURCES.has(power.source)));
  window.T20_POWER_CATALOG.push(...powerEntries);
})();
