(() => {
  if (!window.T20_DATA) return;

  const racas = window.T20_DATA.racas || {};
  if (racas.suraggel) {
    const baseSuraggel = racas.suraggel;
    racas.suraggel_aggelus = {
      ...baseSuraggel,
      nome: "Suraggel (Aggelus)",
      atributos: "Sab +2, Car +1"
    };
    racas.suraggel_sulfure = {
      ...baseSuraggel,
      nome: "Suraggel (Sulfure)",
      atributos: "Des +2, Int +1"
    };
    delete racas.suraggel;
  }

  const ameacasRacas = {
    bugbear: { nome: "Bugbear", fonte: "Ameaças de Arton", atributos: "For +2, Des +1, Car -1", pagina: 79 },
    centauro: { nome: "Centauro", fonte: "Ameaças de Arton", atributos: "Sab +2, For +1, Int -1", pagina: 105 },
    ceratops: { nome: "Ceratops", fonte: "Ameaças de Arton", atributos: "Con +2, For +1, Des -1, Int -1", pagina: 265 },
    elfo_do_mar: { nome: "Elfo-do-mar", fonte: "Ameaças de Arton", atributos: "Des +2, Con +1, Int -1", pagina: 316 },
    finntroll: { nome: "Finntroll", fonte: "Ameaças de Arton", atributos: "Int +2, Con +1, For -1", pagina: 339 },
    gnoll: { nome: "Gnoll", fonte: "Ameaças de Arton", atributos: "Con +2, Sab +1, Int -1", pagina: 115 },
    golem_ameacas: { nome: "Golem", fonte: "Ameaças de Arton", atributos: "For +1, Car -1, mais especial", pagina: 134 },
    harpia: { nome: "Harpia", fonte: "Ameaças de Arton", atributos: "Des +2, Car +1, Int -1", pagina: 201 },
    hobgoblin: { nome: "Hobgoblin", fonte: "Ameaças de Arton", atributos: "Con +2, Des +1, Car -1", pagina: 84 },
    kallyanach: { nome: "Kallyanach", fonte: "Ameaças de Arton", atributos: "+2 em um atributo ou +1 em dois atributos", pagina: 151 },
    kaijin: { nome: "Kaijin", fonte: "Ameaças de Arton", atributos: "For +2, Con +1, Car -2", pagina: 157 },
    kappa: { nome: "Kappa", fonte: "Ameaças de Arton", atributos: "Des +2, Con +1, Car -1", pagina: 158 },
    kobolds: { nome: "Kobolds", fonte: "Ameaças de Arton", atributos: "Des +2, For -1", pagina: 182 },
    mashin: { nome: "Mashin", fonte: "Ameaças de Arton", atributos: "For +1, Car -1, mais especial", pagina: 160 },
    meio_orc: { nome: "Meio-orc", fonte: "Ameaças de Arton", atributos: "For +2, +1 em outro atributo (exceto Car)", pagina: 31 },
    minauro: { nome: "Minauro", fonte: "Ameaças de Arton", atributos: "For +1, +1 em dois atributos", pagina: 175 },
    moreau: { nome: "Moreau", fonte: "Ameaças de Arton", atributos: "+1 no atributo da herança, +1 em dois atributos", pagina: 303 },
    nagah: { nome: "Nagah", fonte: "Ameaças de Arton", atributos: "For +1, Des +1, Con +1 (macho), Int +1, Sab +1, Car +1 (fêmea)", pagina: 333 },
    nezumi: { nome: "Nezumi", fonte: "Ameaças de Arton", atributos: "Con +2, Des +1, Int -1", pagina: 162 },
    ogro: { nome: "Ogro", fonte: "Ameaças de Arton", atributos: "For +3, Con +2, Int -1, Car -1", pagina: 40 },
    orc: { nome: "Orc", fonte: "Ameaças de Arton", atributos: "For +2, Con +1, Int -1", pagina: 33 },
    pteros: { nome: "Pteros", fonte: "Ameaças de Arton", atributos: "Sab +2, Des +1, Int -1", pagina: 267 },
    soterrado: { nome: "Soterrado", fonte: "Ameaças de Arton", atributos: "+1 em três atributos diferentes (exceto Con), Con -1", pagina: 354 },
    tabrachi: { nome: "Tabrachi", fonte: "Ameaças de Arton", atributos: "Con +2, For +1, Car -1", pagina: 37 },
    tengu: { nome: "Tengu", fonte: "Ameaças de Arton", atributos: "Des +2, Int +1", pagina: 164 },
    troganao: { nome: "Troganão", fonte: "Ameaças de Arton", atributos: "Con +2, For +1, Des -1, Int -1", pagina: 39 },
    velocis: { nome: "Velocis", fonte: "Ameaças de Arton", atributos: "Des +2, Sab +1, Int -1", pagina: 268 },
    voracis: { nome: "Voracis", fonte: "Ameaças de Arton", atributos: "Des +2, Con +1, Int -1", pagina: 270 },
    yidishan: { nome: "Yidishan", fonte: "Ameaças de Arton", atributos: "+1 em três atributos diferentes (exceto Car), Car -2", pagina: 300 }
  };

  Object.assign(window.T20_DATA.racas, ameacasRacas);
  Object.assign(window.T20_DATA.classes, {
    sentinela: {
      nome: "Sentinela",
      pv1: 12,
      pvNivel: 4,
      pmNivel: 5,
      fonte: "Dragão Brasil 222",
      pericias: ["Luta", "Misticismo"],
      idBase: "arcanista",
      variante: true,
      classeBase: "Arcanista"
    }
  });

  const classProgressions = {
    arcanista: {
      1: "Caminho do arcanista, magias (1º círculo)",
      2: "Poder de arcanista",
      3: "Poder de arcanista",
      4: "Poder de arcanista",
      5: "Magias (2º círculo), poder de arcanista",
      6: "Poder de arcanista",
      7: "Poder de arcanista",
      8: "Poder de arcanista",
      9: "Magias (3º círculo), poder de arcanista",
      10: "Poder de arcanista",
      11: "Poder de arcanista",
      12: "Poder de arcanista",
      13: "Magias (4º círculo), poder de arcanista",
      14: "Poder de arcanista",
      15: "Poder de arcanista",
      16: "Poder de arcanista",
      17: "Magias (5º círculo), poder de arcanista",
      18: "Poder de arcanista",
      19: "Poder de arcanista",
      20: "Alta arcana, poder de arcanista"
    },
    sentinela: {
      1: "Caminho do sentinela, gladiomancia, magias (1º círculo)",
      2: "Poder de arcanista",
      3: "Mago de combate, poder de arcanista",
      4: "Poder de arcanista",
      5: "Magias (2º círculo), poder de arcanista",
      6: "Poder de arcanista",
      7: "Poder de arcanista",
      8: "Ataque extra, poder de arcanista",
      9: "Magias (3º círculo), poder de arcanista",
      10: "Poder de arcanista",
      11: "Poder de arcanista",
      12: "Poder de arcanista",
      13: "Magias (4º círculo), poder de arcanista",
      14: "Poder de arcanista",
      15: "Poder de arcanista",
      16: "Poder de arcanista",
      17: "Magias (5º círculo), poder de arcanista",
      18: "Poder de arcanista",
      19: "Poder de arcanista",
      20: "Mestre arcano-combatente, poder de arcanista"
    },
    barbaro: {
      1: "Fúria +2",
      2: "Poder de bárbaro",
      3: "Instinto selvagem +1, poder de bárbaro",
      4: "Poder de bárbaro",
      5: "Poder de bárbaro, redução de dano 2",
      6: "Fúria +3, poder de bárbaro",
      7: "Poder de bárbaro",
      8: "Poder de bárbaro, redução de dano 4",
      9: "Instinto selvagem +2, poder de bárbaro",
      10: "Poder de bárbaro",
      11: "Fúria +4, poder de bárbaro, redução de dano 6",
      12: "Poder de bárbaro",
      13: "Poder de bárbaro",
      14: "Poder de bárbaro, redução de dano 8",
      15: "Instinto selvagem +3, poder de bárbaro",
      16: "Fúria +5, poder de bárbaro",
      17: "Poder de bárbaro, redução de dano 10",
      18: "Poder de bárbaro",
      19: "Poder de bárbaro",
      20: "Fúria titânica, poder de bárbaro"
    },
    bardo: {
      1: "Inspiração +1, magias (1º círculo)",
      2: "Poder de bardo, eclético",
      3: "Poder de bardo",
      4: "Poder de bardo",
      5: "Inspiração +2, poder de bardo",
      6: "Magias (2º círculo), poder de bardo",
      7: "Poder de bardo",
      8: "Poder de bardo",
      9: "Inspiração +3, poder de bardo",
      10: "Magias (3º círculo), poder de bardo",
      11: "Poder de bardo",
      12: "Poder de bardo",
      13: "Inspiração +4, poder de bardo",
      14: "Magias (4º círculo), poder de bardo",
      15: "Poder de bardo",
      16: "Poder de bardo",
      17: "Inspiração +5, poder de bardo",
      18: "Poder de bardo",
      19: "Poder de bardo",
      20: "Artista completo, poder de bardo"
    },
    bucaneiro: {
      1: "Audácia, insolência",
      2: "Evasão, poder de bucaneiro",
      3: "Esquiva sagaz +1, poder de bucaneiro",
      4: "Poder de bucaneiro",
      5: "Panache, poder de bucaneiro",
      6: "Poder de bucaneiro",
      7: "Esquiva sagaz +2, poder de bucaneiro",
      8: "Poder de bucaneiro",
      9: "Poder de bucaneiro",
      10: "Evasão aprimorada, poder de bucaneiro",
      11: "Esquiva sagaz +3, poder de bucaneiro",
      12: "Poder de bucaneiro",
      13: "Poder de bucaneiro",
      14: "Poder de bucaneiro",
      15: "Esquiva sagaz +4, poder de bucaneiro",
      16: "Poder de bucaneiro",
      17: "Poder de bucaneiro",
      18: "Poder de bucaneiro",
      19: "Esquiva sagaz +5, poder de bucaneiro",
      20: "Poder de bucaneiro, sorte de Nimb"
    },
    cacador: {
      1: "Marca da presa +1d4, rastreador",
      2: "Poder de caçador",
      3: "Explorador, poder de caçador",
      4: "Poder de caçador",
      5: "Caminho do explorador, marca da presa +1d8, poder de caçador",
      6: "Poder de caçador",
      7: "Explorador, poder de caçador",
      8: "Poder de caçador",
      9: "Marca da presa +1d12, poder de caçador",
      10: "Poder de caçador",
      11: "Explorador, poder de caçador",
      12: "Poder de caçador",
      13: "Marca da presa +2d8, poder de caçador",
      14: "Poder de caçador",
      15: "Explorador, poder de caçador",
      16: "Poder de caçador",
      17: "Marca da presa +2d10, poder de caçador",
      18: "Poder de caçador",
      19: "Explorador, poder de caçador",
      20: "Mestre caçador, poder de caçador"
    },
    cavaleiro: {
      1: "Baluarte +2, código de honra",
      2: "Duelo +2, poder de cavaleiro",
      3: "Poder de cavaleiro",
      4: "Poder de cavaleiro",
      5: "Caminho do cavaleiro, baluarte +4, poder de cavaleiro",
      6: "Poder de cavaleiro",
      7: "Baluarte (aliados adjacentes), duelo +3, poder de cavaleiro",
      8: "Poder de cavaleiro",
      9: "Baluarte +6, poder de cavaleiro",
      10: "Poder de cavaleiro",
      11: "Poder de cavaleiro, resoluto",
      12: "Duelo +4, poder de cavaleiro",
      13: "Baluarte +8, poder de cavaleiro",
      14: "Poder de cavaleiro",
      15: "Baluarte (aliados em alcance curto), poder de cavaleiro",
      16: "Poder de cavaleiro",
      17: "Baluarte +10, duelo +5, poder de cavaleiro",
      18: "Poder de cavaleiro",
      19: "Poder de cavaleiro",
      20: "Bravura final, poder de cavaleiro"
    },
    clerigo: {
      1: "Devoto fiel, magias (1º círculo)",
      2: "Poder de clérigo",
      3: "Poder de clérigo",
      4: "Poder de clérigo",
      5: "Magias (2º círculo), poder de clérigo",
      6: "Poder de clérigo",
      7: "Poder de clérigo",
      8: "Poder de clérigo",
      9: "Magias (3º círculo), poder de clérigo",
      10: "Poder de clérigo",
      11: "Poder de clérigo",
      12: "Poder de clérigo",
      13: "Magias (4º círculo), poder de clérigo",
      14: "Poder de clérigo",
      15: "Poder de clérigo",
      16: "Poder de clérigo",
      17: "Magias (5º círculo), poder de clérigo",
      18: "Poder de clérigo",
      19: "Poder de clérigo",
      20: "Mão da divindade, poder de clérigo"
    },
    druida: {
      1: "Devoto fiel, empatia selvagem, magias (1º círculo)",
      2: "Caminho dos ermos, poder de druida",
      3: "Poder de druida",
      4: "Poder de druida",
      5: "Poder de druida",
      6: "Magias (2º círculo), poder de druida",
      7: "Poder de druida",
      8: "Poder de druida",
      9: "Poder de druida",
      10: "Magias (3º círculo), poder de druida",
      11: "Poder de druida",
      12: "Poder de druida",
      13: "Poder de druida",
      14: "Magias (4º círculo), poder de druida",
      15: "Poder de druida",
      16: "Poder de druida",
      17: "Poder de druida",
      18: "Poder de druida",
      19: "Poder de druida",
      20: "Força da natureza, poder de druida"
    },
    guerreiro: {
      1: "Ataque especial +4",
      2: "Poder de guerreiro",
      3: "Durão, poder de guerreiro",
      4: "Poder de guerreiro",
      5: "Ataque especial +8, poder de guerreiro",
      6: "Ataque extra, poder de guerreiro",
      7: "Poder de guerreiro",
      8: "Poder de guerreiro",
      9: "Ataque especial +12, poder de guerreiro",
      10: "Poder de guerreiro",
      11: "Poder de guerreiro",
      12: "Poder de guerreiro",
      13: "Ataque especial +16, poder de guerreiro",
      14: "Poder de guerreiro",
      15: "Poder de guerreiro",
      16: "Poder de guerreiro",
      17: "Ataque especial +20, poder de guerreiro",
      18: "Poder de guerreiro",
      19: "Poder de guerreiro",
      20: "Campeão, poder de guerreiro"
    },
    inventor: {
      1: "Engenhosidade, protótipo",
      2: "Fabricar item superior (1 melhoria), poder de inventor",
      3: "Comerciante, poder de inventor",
      4: "Poder de inventor",
      5: "Fabricar item superior (2 melhorias), poder de inventor",
      6: "Poder de inventor",
      7: "Encontrar fraqueza, poder de inventor",
      8: "Fabricar item superior (3 melhorias), poder de inventor",
      9: "Fabricar item mágico (menor), poder de inventor",
      10: "Olho do dragão, poder de inventor",
      11: "Fabricar item superior (4 melhorias), poder de inventor",
      12: "Poder de inventor",
      13: "Fabricar item mágico (médio), poder de inventor",
      14: "Poder de inventor",
      15: "Poder de inventor",
      16: "Poder de inventor",
      17: "Fabricar item mágico (maior), poder de inventor",
      18: "Poder de inventor",
      19: "Poder de inventor",
      20: "Obra-prima, poder de inventor"
    },
    ladino: {
      1: "Ataque furtivo +1d6, especialista",
      2: "Evasão, poder de ladino",
      3: "Ataque furtivo +2d6, poder de ladino",
      4: "Esquiva sobrenatural, poder de ladino",
      5: "Ataque furtivo +3d6, poder de ladino",
      6: "Poder de ladino",
      7: "Ataque furtivo +4d6, poder de ladino",
      8: "Olhos nas costas, poder de ladino",
      9: "Ataque furtivo +5d6, poder de ladino",
      10: "Evasão aprimorada, poder de ladino",
      11: "Ataque furtivo +6d6, poder de ladino",
      12: "Poder de ladino",
      13: "Ataque furtivo +7d6, poder de ladino",
      14: "Poder de ladino",
      15: "Ataque furtivo +8d6, poder de ladino",
      16: "Poder de ladino",
      17: "Ataque furtivo +9d6, poder de ladino",
      18: "Poder de ladino",
      19: "Ataque furtivo +10d6, poder de ladino",
      20: "A pessoa certa para o trabalho, poder de ladino"
    },
    lutador: {
      1: "Briga (1d6), golpe relâmpago",
      2: "Poder de lutador",
      3: "Casca grossa (Con), poder de lutador",
      4: "Poder de lutador",
      5: "Briga (1d8), golpe cruel, poder de lutador",
      6: "Poder de lutador",
      7: "Casca grossa (Con+1), poder de lutador",
      8: "Poder de lutador",
      9: "Briga (1d10), golpe violento, poder de lutador",
      10: "Poder de lutador",
      11: "Casca grossa (Con+2), poder de lutador",
      12: "Poder de lutador",
      13: "Briga (2d6), poder de lutador",
      14: "Poder de lutador",
      15: "Casca grossa (Con+3), poder de lutador",
      16: "Poder de lutador",
      17: "Briga (2d8), poder de lutador",
      18: "Poder de lutador",
      19: "Casca grossa (Con+4), poder de lutador",
      20: "Dono da rua (2d10), poder de lutador"
    },
    nobre: {
      1: "Autoconfiança, espólio, orgulho",
      2: "Palavras afiadas (2d6), poder de nobre",
      3: "Poder de nobre, riqueza",
      4: "Gritar ordens, poder de nobre",
      5: "Poder de nobre, presença aristocrática",
      6: "Palavras afiadas (4d6), poder de nobre",
      7: "Poder de nobre",
      8: "Poder de nobre",
      9: "Poder de nobre",
      10: "Palavras afiadas (6d6), poder de nobre",
      11: "Poder de nobre",
      12: "Poder de nobre",
      13: "Poder de nobre",
      14: "Palavras afiadas (8d6), poder de nobre",
      15: "Poder de nobre",
      16: "Poder de nobre",
      17: "Poder de nobre",
      18: "Palavras afiadas (10d6), poder de nobre",
      19: "Poder de nobre",
      20: "Realeza, poder de nobre"
    },
    paladino: {
      1: "Abençoado, código do herói, golpe divino (+1d8)",
      2: "Cura pelas mãos (1d8+1 PV), poder de paladino",
      3: "Aura sagrada, poder de paladino",
      4: "Poder de paladino",
      5: "Bênção da justiça, golpe divino (+2d8), poder de paladino",
      6: "Cura pelas mãos (2d8+2 PV), poder de paladino",
      7: "Poder de paladino",
      8: "Poder de paladino",
      9: "Golpe divino (+3d8), poder de paladino",
      10: "Cura pelas mãos (3d8+3 PV), poder de paladino",
      11: "Poder de paladino",
      12: "Poder de paladino",
      13: "Golpe divino (+4d8), poder de paladino",
      14: "Cura pelas mãos (4d8+4 PV), poder de paladino",
      15: "Poder de paladino",
      16: "Poder de paladino",
      17: "Golpe divino (+5d8), poder de paladino",
      18: "Cura pelas mãos (5d8+5 PV), poder de paladino",
      19: "Poder de paladino",
      20: "Poder de paladino, vingador sagrado"
    },
    treinador: {
      1: "Direcionar, melhor amigo (2 truques)",
      2: "Domar criatura (2d8), poder de treinador",
      3: "Poder de treinador",
      4: "Melhor amigo (3 truques), poder de treinador",
      5: "Domar criatura (cena), poder de treinador, treino especializado",
      6: "Domar criatura (4d8), poder de treinador, sincronia de combate",
      7: "Melhor amigo (4 truques), poder de treinador",
      8: "Domar criatura (dia), poder de treinador",
      9: "Poder de treinador",
      10: "Domar criatura (6d8), melhor amigo (5 truques), poder de treinador",
      11: "Poder de treinador",
      12: "Poder de treinador",
      13: "Melhor amigo (6 truques), poder de treinador",
      14: "Domar criatura (8d8), poder de treinador",
      15: "Poder de treinador",
      16: "Melhor amigo (7 truques), poder de treinador",
      17: "Poder de treinador",
      18: "Domar criatura (10d8), poder de treinador",
      19: "Melhor amigo (8 truques), poder de treinador",
      20: "Poder de treinador, sincronia perfeita"
    },
    frade: {
      1: "Devoto fiel, erudição, magias (1º círculo)",
      2: "Poder de frade, versiculário",
      3: "Poder de frade",
      4: "Poder de frade",
      5: "Dádiva da fé, magias (2º círculo), poder de frade",
      6: "Poder de frade",
      7: "Poder de frade",
      8: "Poder de frade",
      9: "Magias (3º círculo), poder de frade",
      10: "Poder de frade",
      11: "Poder de frade",
      12: "Poder de frade",
      13: "Magias (4º círculo), poder de frade",
      14: "Poder de frade",
      15: "Poder de frade",
      16: "Poder de frade",
      17: "Magias (5º círculo), poder de frade",
      18: "Poder de frade",
      19: "Poder de frade",
      20: "Poder de frade, solo santificado"
    },
    alquimista: {
      1: "Engenhosidade, laboratório pessoal",
      2: "Alquimista iniciado, poder de inventor",
      3: "Mistura básica, poder de inventor",
      4: "Poder de inventor",
      5: "Aplicação rápida, poder de inventor",
      6: "Poder de inventor",
      7: "Magia engarrafada, poder de inventor",
      8: "Odores alquímicos, poder de inventor",
      9: "Fabricar emulsão (1 encanto), poder de inventor",
      10: "Mestre alquimista, poder de inventor",
      11: "Bombardeio eficiente, poder de inventor",
      12: "Poder de inventor",
      13: "Fabricar emulsão (2 encantos), poder de inventor",
      14: "Poder de inventor",
      15: "Poder de inventor",
      16: "Poder de inventor",
      17: "Fabricar emulsão (3 encantos), poder de inventor",
      18: "Poder de inventor",
      19: "Poder de inventor",
      20: "Pedra filosofal, poder de inventor"
    },
    atleta: {
      1: "Briga (1d6), façanha atlética",
      2: "Arremesso atlético, poder de lutador, poderio muscular",
      3: "Casca grossa (Con), poder de lutador",
      4: "Poder de lutador",
      5: "Briga (1d8), mais alto e mais rápido, poder de lutador",
      6: "Poder de lutador",
      7: "Casca grossa (Con+1), poder de lutador",
      8: "Poder de lutador",
      9: "Briga (1d10), disciplina atlética, poder de lutador",
      10: "Poder de lutador",
      11: "Casca grossa (Con+2), poder de lutador",
      12: "Poder de lutador",
      13: "Briga (2d6), poder de lutador",
      14: "Poder de lutador",
      15: "Casca grossa (Con+3), poder de lutador",
      16: "Poder de lutador",
      17: "Briga (2d8), poder de lutador",
      18: "Poder de lutador",
      19: "Casca grossa (Con+4), poder de lutador",
      20: "Corpo ideal (2d10), poder de lutador"
    },
    burgues: {
      1: "Meios de produção, orgulho, poder monetário",
      2: "Desmoralizar -1, poder de nobre",
      3: "Negociante nato, poder de nobre",
      4: "Poder de nobre, suborno",
      5: "Ostentação, poder de nobre",
      6: "Desmoralizar -2, poder de nobre",
      7: "Poder de nobre",
      8: "Poder de nobre",
      9: "Novo rico, poder de nobre",
      10: "Desmoralizar -3, poder de nobre",
      11: "Poder de nobre",
      12: "Poder de nobre",
      13: "Poder de nobre",
      14: "Desmoralizar -4, poder de nobre",
      15: "Poder de nobre",
      16: "Poder de nobre",
      17: "Poder de nobre",
      18: "Desmoralizar -5, poder de nobre",
      19: "Poder de nobre",
      20: "Magnata"
    },
    duelista: {
      1: "Duelo +2, insolência",
      2: "Escola de duelo, poder de bucaneiro",
      3: "Esquiva sagaz +1, poder de bucaneiro",
      4: "Poder de bucaneiro, truques de capa",
      5: "Poder de bucaneiro",
      6: "Duelo +3, poder de bucaneiro",
      7: "Esquiva sagaz +2, poder de bucaneiro",
      8: "Poder de bucaneiro",
      9: "Poder de bucaneiro",
      10: "Poder de bucaneiro, técnica avançada",
      11: "Duelo +4, esquiva sagaz +3, poder de bucaneiro",
      12: "Poder de bucaneiro",
      13: "Poder de bucaneiro",
      14: "Poder de bucaneiro",
      15: "Esquiva sagaz +4, poder de bucaneiro",
      16: "Duelo +5, poder de bucaneiro",
      17: "Poder de bucaneiro",
      18: "Poder de bucaneiro",
      19: "Esquiva sagaz +5, poder de bucaneiro",
      20: "Duelista lendário, poder de bucaneiro"
    },
    ermitao: {
      1: "Devoto fiel, empatia selvagem, magias (1º círculo)",
      2: "Poder de druida",
      3: "Poder de druida, sítio sagrado",
      4: "Poder de druida",
      5: "Poder de druida, vínculo com a terra",
      6: "Magias (2º círculo), poder de druida",
      7: "Poder de druida",
      8: "Poder de druida",
      9: "Poder de druida",
      10: "Magias (3º círculo), poder de druida",
      11: "Poder de druida, temperado pelo clima",
      12: "Poder de druida",
      13: "Poder de druida",
      14: "Magias (4º círculo), poder de druida",
      15: "Poder de druida",
      16: "Poder de druida",
      17: "Poder de druida",
      18: "Poder de druida",
      19: "Poder de druida",
      20: "Eixo de pedras, poder de druida"
    },
    inovador: {
      1: "Do bom e do melhor, sequência especial +2",
      2: "Bombardeio sequencial, poder de guerreiro",
      3: "Acrobacia defensiva, poder de guerreiro",
      4: "Domínio excêntrico, poder de guerreiro",
      5: "Poder de guerreiro, sequência especial +4",
      6: "Poder de guerreiro",
      7: "Poder de guerreiro, técnica excêntrica",
      8: "Poder de guerreiro",
      9: "Poder de guerreiro, sequência especial +6",
      10: "Poder de guerreiro",
      11: "Poder de guerreiro",
      12: "Poder de guerreiro",
      13: "Poder de guerreiro, sequência especial +8",
      14: "Poder de guerreiro",
      15: "Poder de guerreiro",
      16: "Poder de guerreiro",
      17: "Poder de guerreiro, sequência especial +10",
      18: "Poder de guerreiro",
      19: "Poder de guerreiro",
      20: "Estilo único, poder de guerreiro"
    },
    machado_de_pedra: {
      1: "Fúria +2, grunhidos, machado de pedra, tanga de peles (Con)",
      2: "Fúria primitiva, poder de bárbaro",
      3: "Instinto selvagem +1, poder de bárbaro, tanga de peles (Def +1)",
      4: "Poder de bárbaro",
      5: "Poder de bárbaro, resiliência primal 3",
      6: "Fúria +3, poder de bárbaro",
      7: "Poder de bárbaro, tanga de peles (Def +2)",
      8: "Poder de bárbaro, resiliência primal 6",
      9: "Instinto selvagem +2, poder de bárbaro",
      10: "Poder de bárbaro",
      11: "Fúria +4, poder de bárbaro, resiliência primal 9, tanga de peles (Def +3)",
      12: "Poder de bárbaro",
      13: "Poder de bárbaro",
      14: "Poder de bárbaro, resiliência primal 12",
      15: "Instinto selvagem +3, poder de bárbaro, tanga de peles (Def +4)",
      16: "Fúria +5, poder de bárbaro",
      17: "Poder de bárbaro, resiliência primal 15",
      18: "Poder de bárbaro",
      19: "Poder de bárbaro, tanga de peles (Def +5)",
      20: "Fúria rústica, poder de bárbaro"
    },
    magimarcialista: {
      1: "Cadência magimarcial, magificação +2, magias (1º círculo)",
      2: "Bravado magimarcial, poder de bardo",
      3: "Dança defensiva, poder de bardo",
      4: "Poder de bardo",
      5: "Poder de bardo",
      6: "Magias (2º círculo), magificação +3, poder de bardo",
      7: "Arte sublime, poder de bardo",
      8: "Poder de bardo",
      9: "Poder de bardo",
      10: "Magias (3º círculo), poder de bardo",
      11: "Magificação +4, poder de bardo",
      12: "Poder de bardo",
      13: "Poder de bardo",
      14: "Magias (4º círculo), poder de bardo",
      15: "Poder de bardo",
      16: "Magificação +5, poder de bardo",
      17: "Poder de bardo",
      18: "Poder de bardo",
      19: "Poder de bardo",
      20: "Crescendo vitorioso, poder de bardo"
    },
    necromante: {
      1: "Caminho do necromante, falar com mortos, magias (1º círculo)",
      2: "Animar cadáver, poder de arcanista",
      3: "Necrologia +2, poder de arcanista",
      4: "Distorção necrótica, poder de arcanista",
      5: "Magias (2º círculo), necropotência, poder de arcanista",
      6: "Poder de arcanista",
      7: "Poder de arcanista",
      8: "Necrologia +3, poder de arcanista",
      9: "Magias (3º círculo), poder de arcanista",
      10: "Poder de arcanista",
      11: "Poder de arcanista",
      12: "Poder de arcanista",
      13: "Magias (4º círculo), necrologia +4, poder de arcanista",
      14: "Poder de arcanista",
      15: "Poder de arcanista",
      16: "Poder de arcanista",
      17: "Magias (5º círculo), poder de arcanista",
      18: "Necrologia +5, poder de arcanista",
      19: "Poder de arcanista",
      20: "Domínio sobre a morte, poder de arcanista"
    },
    santo: {
      1: "Abençoado, código do herói, ladainha de combate (+1)",
      2: "Poder de paladino, santo curandeiro",
      3: "Poder de paladino, vaso sagrado",
      4: "Poder de paladino",
      5: "Ladainha de combate (+2, sacra), poder de paladino",
      6: "Mártir, poder de paladino",
      7: "Poder de paladino",
      8: "Pira santa, poder de paladino",
      9: "Ladainha de combate (+3, veloz), poder de paladino",
      10: "Poder de paladino",
      11: "Poder de paladino",
      12: "Poder de paladino",
      13: "Ladainha de combate (+4), poder de paladino",
      14: "Poder de paladino",
      15: "Poder de paladino",
      16: "Poder de paladino",
      17: "Ladainha de combate (+5), poder de paladino",
      18: "Poder de paladino",
      19: "Poder de paladino",
      20: "Poder de paladino, vingador santificado"
    },
    seteiro: {
      1: "Caminho do atirador, marca da presa +1d4, tiro de supressão",
      2: "Poder de caçador",
      3: "Evasão, poder de caçador",
      4: "Poder de caçador",
      5: "Disparo constritor, marca da presa +1d8, poder de caçador",
      6: "Poder de caçador",
      7: "Poder de caçador",
      8: "Poder de caçador",
      9: "Marca da presa +1d12, poder de caçador",
      10: "Poder de caçador, rajada de flechas",
      11: "Poder de caçador",
      12: "Poder de caçador",
      13: "Evasão aprimorada, marca da presa +2d8, poder de caçador",
      14: "Poder de caçador",
      15: "Poder de caçador, sentinela",
      16: "Poder de caçador",
      17: "Marca da presa +2d10, poder de caçador",
      18: "Poder de caçador",
      19: "Poder de caçador",
      20: "Poder de caçador, mestre do disparo"
    },
    usurpador: {
      1: "Inimigo dos deuses, magias (1º círculo), usurpar",
      2: "Canalização falsa, poder de clérigo",
      3: "Discrição divina +1, poder de clérigo",
      4: "Poder capturado, poder de clérigo",
      5: "Magias (2º círculo), poder de clérigo",
      6: "Poder de clérigo",
      7: "Poder de clérigo",
      8: "Poder de clérigo",
      9: "Discrição divina +2, magias (3º círculo), poder de clérigo",
      10: "Poder de clérigo",
      11: "Poder de clérigo",
      12: "Poder de clérigo",
      13: "Magias (4º círculo), poder de clérigo",
      14: "Poder de clérigo",
      15: "Discrição divina +3, poder de clérigo",
      16: "Poder de clérigo",
      17: "Magias (5º círculo), poder de clérigo",
      18: "Poder de clérigo",
      19: "Poder de clérigo",
      20: "Poder de clérigo, roubo divino"
    },
    vassalo: {
      1: "Baluarte +2, código de honra, jovem pajem, suserano",
      2: "Valete",
      3: "Escudeiro aprendiz",
      4: "Guarda do castelo",
      5: "Baluarte +4, vigilante das estradas",
      6: "Cavaleiro do reino",
      7: "Sargento do reino",
      8: "Capitão do reino",
      9: "Baluarte +6, lorde",
      10: "Barão",
      11: "Visconde",
      12: "Conde",
      13: "Baluarte +8, marquês",
      14: "Duque",
      15: "Arquiduque",
      16: "Conselheiro real",
      17: "Baluarte +10, rei mercenário",
      18: "Rei",
      19: "Alto rei",
      20: "Imperador"
    },
    ventanista: {
      1: "Charme, truques do ofício",
      2: "Evasão, poder de ladino",
      3: "Disfarce elaborado (1 poder), poder de ladino",
      4: "Esquiva sobrenatural, poder de ladino",
      5: "Poder de ladino",
      6: "Poder de ladino",
      7: "Poder de ladino, virar a casaca",
      8: "Olhos nas costas, poder de ladino",
      9: "Disfarce elaborado (2 poderes), poder de ladino",
      10: "Evasão aprimorada, poder de ladino",
      11: "Poder de ladino, provocação ousada",
      12: "Poder de ladino",
      13: "Poder de ladino",
      14: "Poder de ladino",
      15: "Disfarce elaborado (3 poderes), poder de ladino",
      16: "Poder de ladino",
      17: "Poder de ladino",
      18: "Poder de ladino",
      19: "Poder de ladino",
      20: "O grande golpe, poder de ladino"
    }
  };

  Object.entries(classProgressions).forEach(([classId, progressao]) => {
    if (window.T20_DATA.classes[classId]) {
      window.T20_DATA.classes[classId].progressao = progressao;
    }
  });
})();
